/*
Generated by EigenEinSum

Recommended filename:
D_mu,nu,w...AO_g,mu...AO_g,nu---Rho_g,w.hpp

Einsum expression:
D(mu, nu, w), AO(g, mu), AO(g, nu) -> Rho(g, w)

The einsum expression is decomposed into:
D(mu, nu, w), AO(g, mu) -> DAO(g, nu, w)
DAO(g, nu, w), AO(g, nu) -> Rho(g, w)

The index paths are derived to be:
TOP
└── w
    └── nu
        ├── mu
        │   └── g
        └── g
*/
{
	[[maybe_unused]] const int g_len = AO.dimension(0);
	assert( g_len == AO.dimension(0) );
	assert( g_len == Rho.dimension(0) );
	[[maybe_unused]] const int w_len = D.dimension(2);
	assert( w_len == Rho.dimension(1) );
	[[maybe_unused]] const int mu_len = D.dimension(0);
	assert( mu_len == AO.dimension(1) );
	[[maybe_unused]] const int nu_len = D.dimension(1);
	assert( nu_len == AO.dimension(1) );
	Eigen::Tensor<double, 1> DAOwnu(g_len);
	for ( int w = 0; w < w_len; w++ ){
		for ( int nu = 0; nu < nu_len; nu++ ){
			DAOwnu.setZero();
			for ( int mu = 0; mu < mu_len; mu++ ){
				double* DAOwnu_ = &DAOwnu(0);
				const double* AO_mu = &AO(0, mu);
				#pragma omp simd simdlen(8) aligned(DAOwnu_, AO_mu: 64)
				for ( int g = 0; g < g_len; g++ ){
					DAOwnu_[g] += D(mu, nu, w) * AO_mu[g];
				}
			}
			double* Rho_w = &Rho(0, w);
			const double* DAOwnu_ = &DAOwnu(0);
			const double* AO_nu = &AO(0, nu);
			#pragma omp simd simdlen(8) aligned(Rho_w, DAOwnu_, AO_nu: 64)
			for ( int g = 0; g < g_len; g++ ){
				Rho_w[g] += DAOwnu_[g] * AO_nu[g];
			}
		}
	}
}
