/*
Generated by EigenEinSum

Recommended filename:
D_mu,nu,mat,w...AO1_g,mu,r...AO_g,nu---Rho1U_g,r,mat,w.hpp

Einsum expression:
D(mu, nu, mat, w), AO1(g, mu, r), AO(g, nu) -> Rho1U(g, r, mat, w)

The einsum expression is decomposed into:
D(mu, nu, mat, w), AO1(g, mu, r) -> DAO1(g, nu, r, mat, w)
DAO1(g, nu, r, mat, w), AO(g, nu) -> Rho1U(g, r, mat, w)

The index paths are derived to be:
TOP
└── w
    └── mat
        └── r
            └── nu
                ├── mu
                │   └── g
                └── g
*/
{
	[[maybe_unused]] const int g_len = AO1.dimension(0);
	assert( g_len == AO.dimension(0) );
	assert( g_len == Rho1U.dimension(0) );
	[[maybe_unused]] const int r_len = AO1.dimension(2);
	assert( r_len == Rho1U.dimension(1) );
	[[maybe_unused]] const int mat_len = D.dimension(2);
	assert( mat_len == Rho1U.dimension(2) );
	[[maybe_unused]] const int w_len = D.dimension(3);
	assert( w_len == Rho1U.dimension(3) );
	[[maybe_unused]] const int mu_len = D.dimension(0);
	assert( mu_len == AO1.dimension(1) );
	[[maybe_unused]] const int nu_len = D.dimension(1);
	assert( nu_len == AO.dimension(1) );
	Eigen::Tensor<double, 1> DAO1wmatrnu(g_len);
	for ( int w = 0; w < w_len; w++ ){
		for ( int mat = 0; mat < mat_len; mat++ ){
			for ( int r = 0; r < r_len; r++ ){
				for ( int nu = 0; nu < nu_len; nu++ ){
					DAO1wmatrnu.setZero();
					for ( int mu = 0; mu < mu_len; mu++ ){
						double* DAO1wmatrnu_ = &DAO1wmatrnu(0);
						const double* AO1_mur = &AO1(0, mu, r);
						#pragma omp simd simdlen(8) aligned(DAO1wmatrnu_, AO1_mur: 64)
						for ( int g = 0; g < g_len; g++ ){
							DAO1wmatrnu_[g] += D(mu, nu, mat, w) * AO1_mur[g];
						}
					}
					double* Rho1U_rmatw = &Rho1U(0, r, mat, w);
					const double* DAO1wmatrnu_ = &DAO1wmatrnu(0);
					const double* AO_nu = &AO(0, nu);
					#pragma omp simd simdlen(8) aligned(Rho1U_rmatw, DAO1wmatrnu_, AO_nu: 64)
					for ( int g = 0; g < g_len; g++ ){
						Rho1U_rmatw[g] += DAO1wmatrnu_[g] * AO_nu[g];
					}
				}
			}
		}
	}
}
