/*
Generated by EigenEinSum

Recommended filename:
D_mu,nu...AO1_g,mu,r...AO1_g,nu,r---Tau_g.hpp

Einsum expression:
D(mu, nu), AO1(g, mu, r), AO1(g, nu, r) -> Tau(g)

The einsum expression is decomposed into:
D(mu, nu), AO1(g, mu, r) -> DAO1(g, r, nu)
DAO1(g, r, nu), AO1(g, nu, r) -> Tau(g)

The index paths are derived to be:
TOP
└── nu
    └── r
        ├── mu
        │   └── g
        └── g
*/
{
	[[maybe_unused]] const int g_len = AO1.dimension(0);
	assert( g_len == AO1.dimension(0) );
	assert( g_len == Tau.dimension(0) );
	[[maybe_unused]] const int mu_len = D.dimension(0);
	assert( mu_len == AO1.dimension(1) );
	[[maybe_unused]] const int nu_len = D.dimension(1);
	assert( nu_len == AO1.dimension(1) );
	[[maybe_unused]] const int r_len = AO1.dimension(2);
	assert( r_len == AO1.dimension(2) );
	Eigen::Tensor<double, 1> DAO1nur(g_len);
	for ( int nu = 0; nu < nu_len; nu++ ){
		for ( int r = 0; r < r_len; r++ ){
			DAO1nur.setZero();
			for ( int mu = 0; mu < mu_len; mu++ ){
				double* DAO1nur_ = &DAO1nur(0);
				const double* AO1_mur = &AO1(0, mu, r);
				#pragma omp simd simdlen(8) aligned(DAO1nur_, AO1_mur: 64)
				for ( int g = 0; g < g_len; g++ ){
					DAO1nur_[g] += D(mu, nu) * AO1_mur[g];
				}
			}
			double* Tau_ = &Tau(0);
			const double* DAO1nur_ = &DAO1nur(0);
			const double* AO1_nur = &AO1(0, nu, r);
			#pragma omp simd simdlen(8) aligned(Tau_, DAO1nur_, AO1_nur: 64)
			for ( int g = 0; g < g_len; g++ ){
				Tau_[g] += DAO1nur_[g] * AO1_nur[g];
			}
		}
	}
}
