/*
Generated by EigenEinSum

Recommended filename:
D_mu,nu,mat...AO1_g,mu,r...AO_g,nu---Rho1U_g,r,mat.hpp

Einsum expression:
D(mu, nu, mat), AO1(g, mu, r), AO(g, nu) -> Rho1U(g, r, mat)

The einsum expression is decomposed into:
D(mu, nu, mat), AO1(g, mu, r) -> DAO1(g, nu, r, mat)
DAO1(g, nu, r, mat), AO(g, nu) -> Rho1U(g, r, mat)

The index paths are derived to be:
TOP
└── mat
    └── r
        ├── mu
        │   └── nu
        │       └── g
        └── nu
            └── g
*/
{
	[[maybe_unused]] const int g_len = AO1.dimension(0);
	assert( g_len == AO.dimension(0) );
	assert( g_len == Rho1U.dimension(0) );
	[[maybe_unused]] const int r_len = AO1.dimension(2);
	assert( r_len == Rho1U.dimension(1) );
	[[maybe_unused]] const int mat_len = D.dimension(2);
	assert( mat_len == Rho1U.dimension(2) );
	[[maybe_unused]] const int mu_len = D.dimension(0);
	assert( mu_len == AO1.dimension(1) );
	[[maybe_unused]] const int nu_len = D.dimension(1);
	assert( nu_len == AO.dimension(1) );
	EigenTensor<2> DAO1matr(g_len, nu_len);
	for ( int mat = 0; mat < mat_len; mat++ ){
		for ( int r = 0; r < r_len; r++ ){
			DAO1matr.setZero();
			for ( int mu = 0; mu < mu_len; mu++ ){
				for ( int nu = 0; nu < nu_len; nu++ ){
					double* DAO1matr_nu = &DAO1matr(0, nu);
					const double* AO1_mur = &AO1(0, mu, r);
					#pragma omp simd simdlen(8) aligned(DAO1matr_nu, AO1_mur: 64)
					for ( int g = 0; g < g_len; g++ ){
						DAO1matr_nu[g] += D(mu, nu, mat) * AO1_mur[g];
					}
				}
			}
			for ( int nu = 0; nu < nu_len; nu++ ){
				double* Rho1U_rmat = &Rho1U(0, r, mat);
				const double* DAO1matr_nu = &DAO1matr(0, nu);
				const double* AO_nu = &AO(0, nu);
				#pragma omp simd simdlen(8) aligned(Rho1U_rmat, DAO1matr_nu, AO_nu: 64)
				for ( int g = 0; g < g_len; g++ ){
					Rho1U_rmat[g] += DAO1matr_nu[g] * AO_nu[g];
				}
			}
		}
	}
}
