/*
Generated by EigenEinSum

Recommended filename:
D_mu,nu,mat...AO_g,mu...AO_g,nu---RhoU_g,mat.hpp

Einsum expression:
D(mu, nu, mat), AO(g, mu), AO(g, nu) -> RhoU(g, mat)

The einsum expression is decomposed into:
D(mu, nu, mat), AO(g, mu) -> DAO(g, nu, mat)
DAO(g, nu, mat), AO(g, nu) -> RhoU(g, mat)

The index paths are derived to be:
TOP
└── mat
    ├── mu
    │   └── nu
    │       └── g
    └── nu
        └── g
*/
{
	[[maybe_unused]] const int g_len = AO.dimension(0);
	assert( g_len == AO.dimension(0) );
	assert( g_len == RhoU.dimension(0) );
	[[maybe_unused]] const int mat_len = D.dimension(2);
	assert( mat_len == RhoU.dimension(1) );
	[[maybe_unused]] const int mu_len = D.dimension(0);
	assert( mu_len == AO.dimension(1) );
	[[maybe_unused]] const int nu_len = D.dimension(1);
	assert( nu_len == AO.dimension(1) );
	EigenTensor<2> DAOmat(g_len, nu_len);
	for ( int mat = 0; mat < mat_len; mat++ ){
		DAOmat.setZero();
		for ( int mu = 0; mu < mu_len; mu++ ){
			for ( int nu = 0; nu < nu_len; nu++ ){
				double* DAOmat_nu = &DAOmat(0, nu);
				const double* AO_mu = &AO(0, mu);
				#pragma omp simd simdlen(8) aligned(DAOmat_nu, AO_mu: 64)
				for ( int g = 0; g < g_len; g++ ){
					DAOmat_nu[g] += D(mu, nu, mat) * AO_mu[g];
				}
			}
		}
		for ( int nu = 0; nu < nu_len; nu++ ){
			double* RhoU_mat = &RhoU(0, mat);
			const double* DAOmat_nu = &DAOmat(0, nu);
			const double* AO_nu = &AO(0, nu);
			#pragma omp simd simdlen(8) aligned(RhoU_mat, DAOmat_nu, AO_nu: 64)
			for ( int g = 0; g < g_len; g++ ){
				RhoU_mat[g] += DAOmat_nu[g] * AO_nu[g];
			}
		}
	}
}
