/*
Generated by EigenEinSum

Recommended filename:
D_mu,nu...AO2L_g,mu...AO_g,nu---Lapl_g.hpp

Einsum expression:
D(mu, nu), AO2L(g, mu), AO(g, nu) -> Lapl(g)

The einsum expression is decomposed into:
D(mu, nu), AO2L(g, mu) -> DAO2L(g, nu)
DAO2L(g, nu), AO(g, nu) -> Lapl(g)

The index paths are derived to be:
TOP
└── nu
    ├── mu
    │   └── g
    └── g
*/
{
	[[maybe_unused]] const int g_len = AO2L.dimension(0);
	assert( g_len == AO.dimension(0) );
	assert( g_len == Lapl.dimension(0) );
	[[maybe_unused]] const int mu_len = D.dimension(0);
	assert( mu_len == AO2L.dimension(1) );
	[[maybe_unused]] const int nu_len = D.dimension(1);
	assert( nu_len == AO.dimension(1) );
	EigenTensor<1> DAO2Lnu(g_len);
	for ( int nu = 0; nu < nu_len; nu++ ){
		DAO2Lnu.setZero();
		for ( int mu = 0; mu < mu_len; mu++ ){
			double* DAO2Lnu_ = &DAO2Lnu(0);
			const double* AO2L_mu = &AO2L(0, mu);
			#pragma omp simd simdlen(8) aligned(DAO2Lnu_, AO2L_mu: 64)
			for ( int g = 0; g < g_len; g++ ){
				DAO2Lnu_[g] += D(mu, nu) * AO2L_mu[g];
			}
		}
		double* Lapl_ = &Lapl(0);
		const double* DAO2Lnu_ = &DAO2Lnu(0);
		const double* AO_nu = &AO(0, nu);
		#pragma omp simd simdlen(8) aligned(Lapl_, DAO2Lnu_, AO_nu: 64)
		for ( int g = 0; g < g_len; g++ ){
			Lapl_[g] += DAO2Lnu_[g] * AO_nu[g];
		}
	}
}
