/*
Generated by EigenEinSum

Recommended filename:
D_mu,nu...AO_g,mu...AO_g,nu---Rho_g.hpp

Einsum expression:
D(mu, nu), AO(g, mu), AO(g, nu) -> Rho(g)

The einsum expression is decomposed into:
D(mu, nu), AO(g, mu) -> DAO(g, nu)
DAO(g, nu), AO(g, nu) -> Rho(g)

The index paths are derived to be:
TOP
└── nu
    ├── mu
    │   └── g
    └── g
*/
{
	const int g_len = AO.dimensions()[0];
	assert( g_len == AO.dimensions()[0] );
	assert( g_len == Rho.dimensions()[0] );
	const int mu_len = D.dimensions()[0];
	assert( mu_len == AO.dimensions()[1] );
	const int nu_len = D.dimensions()[1];
	assert( nu_len == AO.dimensions()[1] );
	EigenTensor<1> DAOnu(g_len);
	for ( int nu = 0; nu < nu_len; nu++ ){
		DAOnu.setZero();
		for ( int mu = 0; mu < mu_len; mu++ ){
			double* DAOnu_ = &DAOnu(0);
			const double* AO_mu = &AO(0, mu);
			#pragma omp simd simdlen(8) aligned(DAOnu_, AO_mu: 64)
			for ( int g = 0; g < g_len; g++ ){
				DAOnu_[g] += D(mu, nu) * AO_mu[g];
			}
		}
		double* Rho_ = &Rho(0);
		const double* DAOnu_ = &DAOnu(0);
		const double* AO_nu = &AO(0, nu);
		#pragma omp simd simdlen(8) aligned(Rho_, DAOnu_, AO_nu: 64) 
		for ( int g = 0; g < g_len; g++ ){
			Rho_[g] += DAOnu_[g] * AO_nu[g];
		}
	}
}
