/*
Generated by EigenEinSum

Recommended filename:
D_mu,nu...AO1s_g,mu,r...AOs_g,nu---Rho1s_g,r.hpp

Einsum expression:
D(mu, nu), AO1s(g, mu, r), AOs(g, nu) -> Rho1s(g, r)

The einsum expression is decomposed into:
D(mu, nu), AO1s(g, mu, r) -> DAO1s(g, r, nu)
DAO1s(g, r, nu), AOs(g, nu) -> Rho1s(g, r)

The index paths are derived to be:
TOP
└── nu
    └── r
        ├── mu
        │   └── g
        └── g
*/
{
	const int g_len = AO1s.dimensions()[0];
	assert( g_len == AOs.dimensions()[0] );
	assert( g_len == Rho1s.dimensions()[0] );
	const int r_len = AO1s.dimensions()[2];
	assert( r_len == Rho1s.dimensions()[1] );
	const int mu_len = D.dimensions()[0];
	assert( mu_len == AO1s.dimensions()[1] );
	const int nu_len = D.dimensions()[1];
	assert( nu_len == AOs.dimensions()[1] );
	Eigen::Tensor<double, 1> DAO1snur(g_len);
	for ( int nu = 0; nu < nu_len; nu++ ){
		for ( int r = 0; r < r_len; r++ ){
			DAO1snur.setZero();
			for ( int mu = 0; mu < mu_len; mu++ ){
				for ( int g = 0; g < g_len; g++ ){
					DAO1snur(g) += D(mu, nu) * AO1s(g, mu, r);
				}
			}
			for ( int g = 0; g < g_len; g++ ){
				Rho1s(g, r) += DAO1snur(g) * AOs(g, nu);
			}
		}
	}
}
