/*
Generated by EigenEinSum

Recommended filename:
D_mu,nu,mat,w...AO2L_g,mu...AO_g,nu---LaplU_g,mat,w.hpp

Einsum expression:
D(mu, nu, mat, w), AO2L(g, mu), AO(g, nu) -> LaplU(g, mat, w)

The einsum expression is decomposed into:
D(mu, nu, mat, w), AO2L(g, mu) -> DAO2L(g, nu, mat, w)
DAO2L(g, nu, mat, w), AO(g, nu) -> LaplU(g, mat, w)

The index paths are derived to be:
TOP
└── w
    └── mat
        └── nu
            ├── mu
            │   └── g
            └── g
*/
{
	[[maybe_unused]] const int g_len = AO2L.dimension(0);
	assert( g_len == AO.dimension(0) );
	assert( g_len == LaplU.dimension(0) );
	[[maybe_unused]] const int mat_len = D.dimension(2);
	assert( mat_len == LaplU.dimension(1) );
	[[maybe_unused]] const int w_len = D.dimension(3);
	assert( w_len == LaplU.dimension(2) );
	[[maybe_unused]] const int mu_len = D.dimension(0);
	assert( mu_len == AO2L.dimension(1) );
	[[maybe_unused]] const int nu_len = D.dimension(1);
	assert( nu_len == AO.dimension(1) );
	Eigen::Tensor<double, 1> DAO2Lwmatnu(g_len);
	for ( int w = 0; w < w_len; w++ ){
		for ( int mat = 0; mat < mat_len; mat++ ){
			for ( int nu = 0; nu < nu_len; nu++ ){
				DAO2Lwmatnu.setZero();
				for ( int mu = 0; mu < mu_len; mu++ ){
					double* DAO2Lwmatnu_ = &DAO2Lwmatnu(0);
					const double* AO2L_mu = &AO2L(0, mu);
					#pragma omp simd simdlen(8) aligned(DAO2Lwmatnu_, AO2L_mu: 64)
					for ( int g = 0; g < g_len; g++ ){
						DAO2Lwmatnu_[g] += D(mu, nu, mat, w) * AO2L_mu[g];
					}
				}
				double* LaplU_matw = &LaplU(0, mat, w);
				const double* DAO2Lwmatnu_ = &DAO2Lwmatnu(0);
				const double* AO_nu = &AO(0, nu);
				#pragma omp simd simdlen(8) aligned(LaplU_matw, DAO2Lwmatnu_, AO_nu: 64)
				for ( int g = 0; g < g_len; g++ ){
					LaplU_matw[g] += DAO2Lwmatnu_[g] * AO_nu[g];
				}
			}
		}
	}
}
