/*
Generated by EigenEinSum

Recommended filename:
D_mu,nu...AO1_g,mu,r...AO_g,nu---Rho1_g,r.hpp

Einsum expression:
D(mu, nu), AO1(g, mu, r), AO(g, nu) -> Rho1(g, r)

The einsum expression is decomposed into:
D(mu, nu), AO1(g, mu, r) -> DAO1(g, r, nu)
DAO1(g, r, nu), AO(g, nu) -> Rho1(g, r)

The index paths are derived to be:
TOP
└── nu
    └── r
        ├── mu
        │   └── g
        └── g
*/
{
	const int g_len = AO1.dimensions()[0];
	assert( g_len == AO.dimensions()[0] );
	assert( g_len == Rho1.dimensions()[0] );
	const int r_len = AO1.dimensions()[2];
	assert( r_len == Rho1.dimensions()[1] );
	const int mu_len = D.dimensions()[0];
	assert( mu_len == AO1.dimensions()[1] );
	const int nu_len = D.dimensions()[1];
	assert( nu_len == AO.dimensions()[1] );
	EigenTensor<1> DAO1nur(g_len);
	for ( int nu = 0; nu < nu_len; nu++ ){
		for ( int r = 0; r < r_len; r++ ){
			DAO1nur.setZero();
			for ( int mu = 0; mu < mu_len; mu++ ){
				double* DAO1nur_ = &DAO1nur(0);
				const double* AO1_mur = &AO1(0, mu, r);
				#pragma omp simd simdlen(8) aligned(DAO1nur_, AO1_mur: 64)
				for ( int g = 0; g < g_len; g++ ){
					DAO1nur_[g] += D(mu, nu) * AO1_mur[g];
				}
			}
			double* Rho1_r = &Rho1(0, r);
			const double* DAO1nur_ = &DAO1nur(0);
			const double* AO_nu = &AO(0, nu);
			#pragma omp simd simdlen(8) aligned(Rho1_r, DAO1nur_, AO_nu: 64)
			for ( int g = 0; g < g_len; g++ ){
				Rho1_r[g] += DAO1nur_[g] * AO_nu[g];
			}
		}
	}
}
