/*
Generated by EigenEinSum

Recommended filename:
D_mu,nu,w...AO2L_g,mu...AO_g,nu---Lapl_g,w.hpp

Einsum expression:
D(mu, nu, w), AO2L(g, mu), AO(g, nu) -> Lapl(g, w)

The einsum expression is decomposed into:
D(mu, nu, w), AO2L(g, mu) -> DAO2L(g, nu, w)
DAO2L(g, nu, w), AO(g, nu) -> Lapl(g, w)

The index paths are derived to be:
TOP
└── w
    └── nu
        ├── mu
        │   └── g
        └── g
*/
{
	[[maybe_unused]] const int g_len = AO2L.dimension(0);
	assert( g_len == AO.dimension(0) );
	assert( g_len == Lapl.dimension(0) );
	[[maybe_unused]] const int w_len = D.dimension(2);
	assert( w_len == Lapl.dimension(1) );
	[[maybe_unused]] const int mu_len = D.dimension(0);
	assert( mu_len == AO2L.dimension(1) );
	[[maybe_unused]] const int nu_len = D.dimension(1);
	assert( nu_len == AO.dimension(1) );
	Eigen::Tensor<double, 1> DAO2Lwnu(g_len);
	for ( int w = 0; w < w_len; w++ ){
		for ( int nu = 0; nu < nu_len; nu++ ){
			DAO2Lwnu.setZero();
			for ( int mu = 0; mu < mu_len; mu++ ){
				double* DAO2Lwnu_ = &DAO2Lwnu(0);
				const double* AO2L_mu = &AO2L(0, mu);
				#pragma omp simd simdlen(8) aligned(DAO2Lwnu_, AO2L_mu: 64)
				for ( int g = 0; g < g_len; g++ ){
					DAO2Lwnu_[g] += D(mu, nu, w) * AO2L_mu[g];
				}
			}
			double* Lapl_w = &Lapl(0, w);
			const double* DAO2Lwnu_ = &DAO2Lwnu(0);
			const double* AO_nu = &AO(0, nu);
			#pragma omp simd simdlen(8) aligned(Lapl_w, DAO2Lwnu_, AO_nu: 64)
			for ( int g = 0; g < g_len; g++ ){
				Lapl_w[g] += DAO2Lwnu_[g] * AO_nu[g];
			}
		}
	}
}
