/*
Generated by EigenEinSum

Recommended filename:
D_mu,nu,w...AO1_g,mu,r...AO_g,nu---Rho1_g,r,w.hpp

Einsum expression:
D(mu, nu, w), AO1(g, mu, r), AO(g, nu) -> Rho1(g, r, w)

The einsum expression is decomposed into:
D(mu, nu, w), AO1(g, mu, r) -> DAO1(g, nu, r, w)
DAO1(g, nu, r, w), AO(g, nu) -> Rho1(g, r, w)

The index paths are derived to be:
TOP
└── w
    └── r
        └── nu
            ├── mu
            │   └── g
            └── g
*/
{
	[[maybe_unused]] const int g_len = AO1.dimension(0);
	assert( g_len == AO.dimension(0) );
	assert( g_len == Rho1.dimension(0) );
	[[maybe_unused]] const int r_len = AO1.dimension(2);
	assert( r_len == Rho1.dimension(1) );
	[[maybe_unused]] const int w_len = D.dimension(2);
	assert( w_len == Rho1.dimension(2) );
	[[maybe_unused]] const int mu_len = D.dimension(0);
	assert( mu_len == AO1.dimension(1) );
	[[maybe_unused]] const int nu_len = D.dimension(1);
	assert( nu_len == AO.dimension(1) );
	Eigen::Tensor<double, 1> DAO1wrnu(g_len);
	for ( int w = 0; w < w_len; w++ ){
		for ( int r = 0; r < r_len; r++ ){
			for ( int nu = 0; nu < nu_len; nu++ ){
				DAO1wrnu.setZero();
				for ( int mu = 0; mu < mu_len; mu++ ){
					double* DAO1wrnu_ = &DAO1wrnu(0);
					const double* AO1_mur = &AO1(0, mu, r);
					#pragma omp simd simdlen(8) aligned(DAO1wrnu_, AO1_mur: 64)
					for ( int g = 0; g < g_len; g++ ){
						DAO1wrnu_[g] += D(mu, nu, w) * AO1_mur[g];
					}
				}
				double* Rho1_rw = &Rho1(0, r, w);
				const double* DAO1wrnu_ = &DAO1wrnu(0);
				const double* AO_nu = &AO(0, nu);
				#pragma omp simd simdlen(8) aligned(Rho1_rw, DAO1wrnu_, AO_nu: 64)
				for ( int g = 0; g < g_len; g++ ){
					Rho1_rw[g] += DAO1wrnu_[g] * AO_nu[g];
				}
			}
		}
	}
}
