/*
Generated by EigenEinSum

Recommended filename:
D_mu,nu,mat,w...AO_g,mu...AO_g,nu---RhoU_g,mat,w.hpp

Einsum expression:
D(mu, nu, mat, w), AO(g, mu), AO(g, nu) -> RhoU(g, mat, w)

The einsum expression is decomposed into:
D(mu, nu, mat, w), AO(g, mu) -> DAO(g, nu, mat, w)
DAO(g, nu, mat, w), AO(g, nu) -> RhoU(g, mat, w)

The index paths are derived to be:
TOP
└── w
    └── mat
        └── nu
            ├── mu
            │   └── g
            └── g
*/
{
	[[maybe_unused]] const int g_len = AO.dimension(0);
	assert( g_len == AO.dimension(0) );
	assert( g_len == RhoU.dimension(0) );
	[[maybe_unused]] const int mat_len = D.dimension(2);
	assert( mat_len == RhoU.dimension(1) );
	[[maybe_unused]] const int w_len = D.dimension(3);
	assert( w_len == RhoU.dimension(2) );
	[[maybe_unused]] const int mu_len = D.dimension(0);
	assert( mu_len == AO.dimension(1) );
	[[maybe_unused]] const int nu_len = D.dimension(1);
	assert( nu_len == AO.dimension(1) );
	Eigen::Tensor<double, 1> DAOwmatnu(g_len);
	for ( int w = 0; w < w_len; w++ ){
		for ( int mat = 0; mat < mat_len; mat++ ){
			for ( int nu = 0; nu < nu_len; nu++ ){
				DAOwmatnu.setZero();
				for ( int mu = 0; mu < mu_len; mu++ ){
					double* DAOwmatnu_ = &DAOwmatnu(0);
					const double* AO_mu = &AO(0, mu);
					#pragma omp simd simdlen(8) aligned(DAOwmatnu_, AO_mu: 64)
					for ( int g = 0; g < g_len; g++ ){
						DAOwmatnu_[g] += D(mu, nu, mat, w) * AO_mu[g];
					}
				}
				double* RhoU_matw = &RhoU(0, mat, w);
				const double* DAOwmatnu_ = &DAOwmatnu(0);
				const double* AO_nu = &AO(0, nu);
				#pragma omp simd simdlen(8) aligned(RhoU_matw, DAOwmatnu_, AO_nu: 64)
				for ( int g = 0; g < g_len; g++ ){
					RhoU_matw[g] += DAOwmatnu_[g] * AO_nu[g];
				}
			}
		}
	}
}
