/*
Generated by EigenEinSum

Recommended filename:
Da_mu,nu,w...AO3a_g,mu,r+t+s...AO_g,nu---Rho1Hessaa_g,r,t,s,w.hpp

Einsum expression:
Da(mu, nu, w), AO3a(g, mu, r+t+s), AO(g, nu) -> Rho1Hessaa(g, r, t, s, w)

The einsum expression is decomposed into:
Da(mu, nu, w), AO3a(g, mu, r+t+s) -> DaAO3a(g, nu, r+t+s, w)
DaAO3a(g, nu, r+t+s, w), AO(g, nu) -> Rho1Hessaa(g, r, t, s, w)

The index paths are derived to be:
TOP
└── w
    └── s
        └── t
            └── r
                └── nu
                    ├── mu
                    │   └── g
                    └── g
*/
{
	[[maybe_unused]] const int g_len = AO3a.dimension(0);
	assert( g_len == AO.dimension(0) );
	assert( g_len == Rho1Hessaa.dimension(0) );
	[[maybe_unused]] const int r_len = Rho1Hessaa.dimension(1);
	[[maybe_unused]] const int t_len = Rho1Hessaa.dimension(2);
	[[maybe_unused]] const int s_len = Rho1Hessaa.dimension(3);
	[[maybe_unused]] const int w_len = Da.dimension(2);
	assert( w_len == Rho1Hessaa.dimension(4) );
	[[maybe_unused]] const int mu_len = Da.dimension(0);
	assert( mu_len == AO3a.dimension(1) );
	[[maybe_unused]] const int nu_len = Da.dimension(1);
	assert( nu_len == AO.dimension(1) );
	[[maybe_unused]] const int r_t_s_len = AO3a.dimension(2);
	Eigen::Tensor<double, 1> DaAO3awstrnu(g_len);
	for ( int w = 0; w < w_len; w++ ){
		for ( int s = 0; s < s_len; s++ ){
			for ( int t = 0; t < t_len; t++ ){
				for ( int r = 0; r < r_len; r++ ){
					int index_array_r_t_s[] = {r, t, s}; std::sort(index_array_r_t_s, index_array_r_t_s + 3); [[maybe_unused]] const int r_t_s = ( index_array_r_t_s[0] + 0 ) / 1 + ( index_array_r_t_s[1] + 0 ) * ( index_array_r_t_s[1] + 1 ) / 2 + ( index_array_r_t_s[2] + 0 ) * ( index_array_r_t_s[2] + 1 ) * ( index_array_r_t_s[2] + 2 ) / 6;
					for ( int nu = 0; nu < nu_len; nu++ ){
						DaAO3awstrnu.setZero();
						for ( int mu = 0; mu < mu_len; mu++ ){
							double* DaAO3awstrnu_ = &DaAO3awstrnu(0);
							const double* AO3a_mur_t_s = &AO3a(0, mu, r_t_s);
							#pragma omp simd simdlen(8) aligned(DaAO3awstrnu_, AO3a_mur_t_s: 64)
							for ( int g = 0; g < g_len; g++ ){
								DaAO3awstrnu_[g] += Da(mu, nu, w) * AO3a_mur_t_s[g];
							}
						}
						double* Rho1Hessaa_rtsw = &Rho1Hessaa(0, r, t, s, w);
						const double* DaAO3awstrnu_ = &DaAO3awstrnu(0);
						const double* AO_nu = &AO(0, nu);
						#pragma omp simd simdlen(8) aligned(Rho1Hessaa_rtsw, DaAO3awstrnu_, AO_nu: 64)
						for ( int g = 0; g < g_len; g++ ){
							Rho1Hessaa_rtsw[g] += DaAO3awstrnu_[g] * AO_nu[g];
						}
					}
				}
			}
		}
	}
}
