/*
Generated by EigenEinSum

Recommended filename:
Da_mu,nu...AO1a_g,mu,t...AO_g,nu---RhoGrada_g,t.hpp

Einsum expression:
Da(mu, nu), AO1a(g, mu, t), AO(g, nu) -> RhoGrada(g, t)

The einsum expression is decomposed into:
Da(mu, nu), AO1a(g, mu, t) -> DaAO1a(g, nu, t)
DaAO1a(g, nu, t), AO(g, nu) -> RhoGrada(g, t)

The index paths are derived to be:
TOP
└── t
    ├── mu
    │   └── nu
    │       └── g
    └── nu
        └── g
*/
{
	[[maybe_unused]] const int g_len = AO1a.dimension(0);
	assert( g_len == AO.dimension(0) );
	assert( g_len == RhoGrada.dimension(0) );
	[[maybe_unused]] const int t_len = AO1a.dimension(2);
	assert( t_len == RhoGrada.dimension(1) );
	[[maybe_unused]] const int mu_len = Da.dimension(0);
	assert( mu_len == AO1a.dimension(1) );
	[[maybe_unused]] const int nu_len = Da.dimension(1);
	assert( nu_len == AO.dimension(1) );
	EigenTensor<2> DaAO1at(g_len, nu_len);
	for ( int t = 0; t < t_len; t++ ){
		DaAO1at.setZero();
		for ( int mu = 0; mu < mu_len; mu++ ){
			for ( int nu = 0; nu < nu_len; nu++ ){
				double* DaAO1at_nu = &DaAO1at(0, nu);
				const double* AO1a_mut = &AO1a(0, mu, t);
				#pragma omp simd simdlen(8) aligned(DaAO1at_nu, AO1a_mut: 64)
				for ( int g = 0; g < g_len; g++ ){
					DaAO1at_nu[g] += Da(mu, nu) * AO1a_mut[g];
				}
			}
		}
		for ( int nu = 0; nu < nu_len; nu++ ){
			double* RhoGrada_t = &RhoGrada(0, t);
			const double* DaAO1at_nu = &DaAO1at(0, nu);
			const double* AO_nu = &AO(0, nu);
			#pragma omp simd simdlen(8) aligned(RhoGrada_t, DaAO1at_nu, AO_nu: 64)
			for ( int g = 0; g < g_len; g++ ){
				RhoGrada_t[g] += DaAO1at_nu[g] * AO_nu[g];
			}
		}
	}
}
