/*
Generated by EigenEinSum

Recommended filename:
Da_mu,nu...AO2sa_g,mu,t,s...AOs_g,nu---RhoHesssaa_g,t,s.hpp

Einsum expression:
Da(mu, nu), AO2sa(g, mu, t|s), AOs(g, nu) -> RhoHesssaa(g, t, s)

The einsum expression is decomposed into:
Da(mu, nu), AO2sa(g, mu, t|s) -> DaAO2sa(g, t|s, nu)
DaAO2sa(g, t|s, nu), AOs(g, nu) -> RhoHesssaa(g, t, s)

The index paths are derived to be:
TOP
└── nu
    └── s
        └── t
            ├── mu
            │   └── g
            └── g
*/
{
	const int g_len = AO2sa.dimensions()[0];
	assert( g_len == AOs.dimensions()[0] );
	assert( g_len == RhoHesssaa.dimensions()[0] );
	const int t_len = RhoHesssaa.dimensions()[1];
	const int s_len = RhoHesssaa.dimensions()[2];
	const int mu_len = Da.dimensions()[0];
	assert( mu_len == AO2sa.dimensions()[1] );
	const int nu_len = Da.dimensions()[1];
	assert( nu_len == AOs.dimensions()[1] );
	Eigen::Tensor<double, 1> DaAO2sanust(g_len);
	for ( int nu = 0; nu < nu_len; nu++ ){
		for ( int s = 0; s < s_len; s++ ){
			for ( int t = 0; t < t_len; t++ ){
				DaAO2sanust.setZero();
				int index_array_t_s[] = {t, s}; std::sort(index_array_t_s, index_array_t_s + 2); const int t_s = ( index_array_t_s[0] + 0 ) / 1 + ( index_array_t_s[1] + 0 ) * ( index_array_t_s[1] + 1 ) / 2;
				for ( int mu = 0; mu < mu_len; mu++ ){
					for ( int g = 0; g < g_len; g++ ){
						DaAO2sanust(g) += Da(mu, nu) * AO2sa(g, mu, t_s);
					}
				}
				for ( int g = 0; g < g_len; g++ ){
					RhoHesssaa(g, t, s) += DaAO2sanust(g) * AOs(g, nu);
				}
			}
		}
	}
}
