/*
Generated by EigenEinSum

Recommended filename:
Da_mu,nu,w...AO2a_g,mu,t+s...AO_g,nu---RhoHessaa_g,t,s,w.hpp

Einsum expression:
Da(mu, nu, w), AO2a(g, mu, t+s), AO(g, nu) -> RhoHessaa(g, t, s, w)

The einsum expression is decomposed into:
Da(mu, nu, w), AO2a(g, mu, t+s) -> DaAO2a(g, nu, t+s, w)
DaAO2a(g, nu, t+s, w), AO(g, nu) -> RhoHessaa(g, t, s, w)

The index paths are derived to be:
TOP
└── w
    └── s
        └── t
            └── nu
                ├── mu
                │   └── g
                └── g
*/
{
	[[maybe_unused]] const int g_len = AO2a.dimension(0);
	assert( g_len == AO.dimension(0) );
	assert( g_len == RhoHessaa.dimension(0) );
	[[maybe_unused]] const int t_len = RhoHessaa.dimension(1);
	[[maybe_unused]] const int s_len = RhoHessaa.dimension(2);
	[[maybe_unused]] const int w_len = Da.dimension(2);
	assert( w_len == RhoHessaa.dimension(3) );
	[[maybe_unused]] const int mu_len = Da.dimension(0);
	assert( mu_len == AO2a.dimension(1) );
	[[maybe_unused]] const int nu_len = Da.dimension(1);
	assert( nu_len == AO.dimension(1) );
	[[maybe_unused]] const int t_s_len = AO2a.dimension(2);
	Eigen::Tensor<double, 1> DaAO2awstnu(g_len);
	for ( int w = 0; w < w_len; w++ ){
		for ( int s = 0; s < s_len; s++ ){
			for ( int t = 0; t < t_len; t++ ){
				int index_array_t_s[] = {t, s}; std::sort(index_array_t_s, index_array_t_s + 2); [[maybe_unused]] const int t_s = ( index_array_t_s[0] + 0 ) / 1 + ( index_array_t_s[1] + 0 ) * ( index_array_t_s[1] + 1 ) / 2;
				for ( int nu = 0; nu < nu_len; nu++ ){
					DaAO2awstnu.setZero();
					for ( int mu = 0; mu < mu_len; mu++ ){
						double* DaAO2awstnu_ = &DaAO2awstnu(0);
						const double* AO2a_mut_s = &AO2a(0, mu, t_s);
						#pragma omp simd simdlen(8) aligned(DaAO2awstnu_, AO2a_mut_s: 64)
						for ( int g = 0; g < g_len; g++ ){
							DaAO2awstnu_[g] += Da(mu, nu, w) * AO2a_mut_s[g];
						}
					}
					double* RhoHessaa_tsw = &RhoHessaa(0, t, s, w);
					const double* DaAO2awstnu_ = &DaAO2awstnu(0);
					const double* AO_nu = &AO(0, nu);
					#pragma omp simd simdlen(8) aligned(RhoHessaa_tsw, DaAO2awstnu_, AO_nu: 64)
					for ( int g = 0; g < g_len; g++ ){
						RhoHessaa_tsw[g] += DaAO2awstnu_[g] * AO_nu[g];
					}
				}
			}
		}
	}
}
