/*
Generated by EigenEinSum

Recommended filename:
Da_mu,nu...AO2a_g,mu,r,t...AO_g,nu---Rho1Grada_g,r,t.hpp

Einsum expression:
Da(mu, nu), AO2a(g, mu, r|t), AO(g, nu) -> Rho1Grada(g, r, t)

The einsum expression is decomposed into:
Da(mu, nu), AO2a(g, mu, r|t) -> DaAO2a(g, nu, r|t)
DaAO2a(g, nu, r|t), AO(g, nu) -> Rho1Grada(g, r, t)

The index paths are derived to be:
TOP
└── t
    └── r
        ├── mu
        │   └── nu
        │       └── g
        └── nu
            └── g
*/
{
	[[maybe_unused]] const int g_len = AO2a.dimension(0);
	assert( g_len == AO.dimension(0) );
	assert( g_len == Rho1Grada.dimension(0) );
	[[maybe_unused]] const int r_len = Rho1Grada.dimension(1);
	[[maybe_unused]] const int t_len = Rho1Grada.dimension(2);
	[[maybe_unused]] const int mu_len = Da.dimension(0);
	assert( mu_len == AO2a.dimension(1) );
	[[maybe_unused]] const int nu_len = Da.dimension(1);
	assert( nu_len == AO.dimension(1) );
	[[maybe_unused]] const int r_t_len = AO2a.dimension(2);
	EigenTensor<2> DaAO2atr(g_len, nu_len);
	for ( int t = 0; t < t_len; t++ ){
		for ( int r = 0; r < r_len; r++ ){
			int index_array_r_t[] = {r, t}; std::sort(index_array_r_t, index_array_r_t + 2); const int r_t = ( index_array_r_t[0] + 0 ) / 1 + ( index_array_r_t[1] + 0 ) * ( index_array_r_t[1] + 1 ) / 2;
			DaAO2atr.setZero();
			for ( int mu = 0; mu < mu_len; mu++ ){
				for ( int nu = 0; nu < nu_len; nu++ ){
					double* DaAO2atr_nu = &DaAO2atr(0, nu);
					const double* AO2a_mur_t = &AO2a(0, mu, r_t);
					#pragma omp simd simdlen(8) aligned(DaAO2atr_nu, AO2a_mur_t: 64)
					for ( int g = 0; g < g_len; g++ ){
						DaAO2atr_nu[g] += Da(mu, nu) * AO2a_mur_t[g];
					}
				}
			}
			for ( int nu = 0; nu < nu_len; nu++ ){
				double* Rho1Grada_rt = &Rho1Grada(0, r, t);
				const double* DaAO2atr_nu = &DaAO2atr(0, nu);
				const double* AO_nu = &AO(0, nu);
				#pragma omp simd simdlen(8) aligned(Rho1Grada_rt, DaAO2atr_nu, AO_nu: 64)
				for ( int g = 0; g < g_len; g++ ){
					Rho1Grada_rt[g] += DaAO2atr_nu[g] * AO_nu[g];
				}
			}
		}
	}
}
