/*
Generated by EigenEinSum

Recommended filename:
Da_mu,nu...AO1a_g,mu,t...AO1_g,nu,r---Rho1Grada_g,r,t.hpp

Einsum expression:
Da(mu, nu), AO1a(g, mu, t), AO1(g, nu, r) -> Rho1Grada(g, r, t)

The einsum expression is decomposed into:
Da(mu, nu), AO1a(g, mu, t) -> DaAO1a(g, nu, t)
DaAO1a(g, nu, t), AO1(g, nu, r) -> Rho1Grada(g, r, t)

The index paths are derived to be:
TOP
└── t
    ├── nu
    │   └── mu
    │       └── g
    └── r
        └── nu
            └── g
*/
{
	[[maybe_unused]] const int g_len = AO1a.dimension(0);
	assert( g_len == AO1.dimension(0) );
	assert( g_len == Rho1Grada.dimension(0) );
	[[maybe_unused]] const int r_len = AO1.dimension(2);
	assert( r_len == Rho1Grada.dimension(1) );
	[[maybe_unused]] const int t_len = AO1a.dimension(2);
	assert( t_len == Rho1Grada.dimension(2) );
	[[maybe_unused]] const int mu_len = Da.dimension(0);
	assert( mu_len == AO1a.dimension(1) );
	[[maybe_unused]] const int nu_len = Da.dimension(1);
	assert( nu_len == AO1.dimension(1) );
	EigenTensor<2> DaAO1at(g_len, nu_len);
	for ( int t = 0; t < t_len; t++ ){
		DaAO1at.setZero();
		for ( int nu = 0; nu < nu_len; nu++ ){
			for ( int mu = 0; mu < mu_len; mu++ ){
				double* DaAO1at_nu = &DaAO1at(0, nu);
				const double* AO1a_mut = &AO1a(0, mu, t);
				#pragma omp simd simdlen(8) aligned(DaAO1at_nu, AO1a_mut: 64)
				for ( int g = 0; g < g_len; g++ ){
					DaAO1at_nu[g] += Da(mu, nu) * AO1a_mut[g];
				}
			}
		}
		for ( int r = 0; r < r_len; r++ ){
			for ( int nu = 0; nu < nu_len; nu++ ){
				double* Rho1Grada_rt = &Rho1Grada(0, r, t);
				const double* DaAO1at_nu = &DaAO1at(0, nu);
				const double* AO1_nur = &AO1(0, nu, r);
				#pragma omp simd simdlen(8) aligned(Rho1Grada_rt, DaAO1at_nu, AO1_nur: 64)
				for ( int g = 0; g < g_len; g++ ){
					Rho1Grada_rt[g] += DaAO1at_nu[g] * AO1_nur[g];
				}
			}
		}
	}
}
