/*
Generated by EigenEinSum

Recommended filename:
Da_mu,nu,w...AO1a_g,mu,t...AO_g,nu---RhoGrada_g,t,w.hpp

Einsum expression:
Da(mu, nu, w), AO1a(g, mu, t), AO(g, nu) -> RhoGrada(g, t, w)

The einsum expression is decomposed into:
Da(mu, nu, w), AO1a(g, mu, t) -> DaAO1a(g, nu, t, w)
DaAO1a(g, nu, t, w), AO(g, nu) -> RhoGrada(g, t, w)

The index paths are derived to be:
TOP
└── w
    └── t
        └── nu
            ├── mu
            │   └── g
            └── g
*/
{
	[[maybe_unused]] const int g_len = AO1a.dimension(0);
	assert( g_len == AO.dimension(0) );
	assert( g_len == RhoGrada.dimension(0) );
	[[maybe_unused]] const int t_len = AO1a.dimension(2);
	assert( t_len == RhoGrada.dimension(1) );
	[[maybe_unused]] const int w_len = Da.dimension(2);
	assert( w_len == RhoGrada.dimension(2) );
	[[maybe_unused]] const int mu_len = Da.dimension(0);
	assert( mu_len == AO1a.dimension(1) );
	[[maybe_unused]] const int nu_len = Da.dimension(1);
	assert( nu_len == AO.dimension(1) );
	Eigen::Tensor<double, 1> DaAO1awtnu(g_len);
	for ( int w = 0; w < w_len; w++ ){
		for ( int t = 0; t < t_len; t++ ){
			for ( int nu = 0; nu < nu_len; nu++ ){
				DaAO1awtnu.setZero();
				for ( int mu = 0; mu < mu_len; mu++ ){
					double* DaAO1awtnu_ = &DaAO1awtnu(0);
					const double* AO1a_mut = &AO1a(0, mu, t);
					#pragma omp simd simdlen(8) aligned(DaAO1awtnu_, AO1a_mut: 64)
					for ( int g = 0; g < g_len; g++ ){
						DaAO1awtnu_[g] += Da(mu, nu, w) * AO1a_mut[g];
					}
				}
				double* RhoGrada_tw = &RhoGrada(0, t, w);
				const double* DaAO1awtnu_ = &DaAO1awtnu(0);
				const double* AO_nu = &AO(0, nu);
				#pragma omp simd simdlen(8) aligned(RhoGrada_tw, DaAO1awtnu_, AO_nu: 64)
				for ( int g = 0; g < g_len; g++ ){
					RhoGrada_tw[g] += DaAO1awtnu_[g] * AO_nu[g];
				}
			}
		}
	}
}
