/*
Generated by EigenEinSum

Recommended filename:
Da_mu,nu...AO3a_g,mu,r,t,s...AO_g,nu---Rho1Hessaa_g,r,t,s.hpp

Einsum expression:
Da(mu, nu), AO3a(g, mu, r|t|s), AO(g, nu) -> Rho1Hessaa(g, r, t, s)

The einsum expression is decomposed into:
Da(mu, nu), AO3a(g, mu, r|t|s) -> DaAO3a(g, nu, r|t|s)
DaAO3a(g, nu, r|t|s), AO(g, nu) -> Rho1Hessaa(g, r, t, s)

The index paths are derived to be:
TOP
└── s
    └── t
        └── r
            └── nu
                ├── mu
                │   └── g
                └── g
*/
{
	[[maybe_unused]] const int g_len = AO3a.dimension(0);
	assert( g_len == AO.dimension(0) );
	assert( g_len == Rho1Hessaa.dimension(0) );
	[[maybe_unused]] const int r_len = Rho1Hessaa.dimension(1);
	[[maybe_unused]] const int t_len = Rho1Hessaa.dimension(2);
	[[maybe_unused]] const int s_len = Rho1Hessaa.dimension(3);
	[[maybe_unused]] const int mu_len = Da.dimension(0);
	assert( mu_len == AO3a.dimension(1) );
	[[maybe_unused]] const int nu_len = Da.dimension(1);
	assert( nu_len == AO.dimension(1) );
	[[maybe_unused]] const int r_t_s_len = AO3a.dimension(2);
	EigenTensor<1> DaAO3astrnu(g_len);
	for ( int s = 0; s < s_len; s++ ){
		for ( int t = 0; t < t_len; t++ ){
			for ( int r = 0; r < r_len; r++ ){
				int index_array_r_t_s[] = {r, t, s}; std::sort(index_array_r_t_s, index_array_r_t_s + 3); const int r_t_s = ( index_array_r_t_s[0] + 0 ) / 1 + ( index_array_r_t_s[1] + 0 ) * ( index_array_r_t_s[1] + 1 ) / 2 + ( index_array_r_t_s[2] + 0 ) * ( index_array_r_t_s[2] + 1 ) * ( index_array_r_t_s[2] + 2 ) / 6;
				for ( int nu = 0; nu < nu_len; nu++ ){
					DaAO3astrnu.setZero();
					for ( int mu = 0; mu < mu_len; mu++ ){
						double* DaAO3astrnu_ = &DaAO3astrnu(0);
						const double* AO3a_mur_t_s = &AO3a(0, mu, r_t_s);
						#pragma omp simd simdlen(8) aligned(DaAO3astrnu_, AO3a_mur_t_s: 64)
						for ( int g = 0; g < g_len; g++ ){
							DaAO3astrnu_[g] += Da(mu, nu) * AO3a_mur_t_s[g];
						}
					}
					double* Rho1Hessaa_rts = &Rho1Hessaa(0, r, t, s);
					const double* DaAO3astrnu_ = &DaAO3astrnu(0);
					const double* AO_nu = &AO(0, nu);
					#pragma omp simd simdlen(8) aligned(Rho1Hessaa_rts, DaAO3astrnu_, AO_nu: 64)
					for ( int g = 0; g < g_len; g++ ){
						Rho1Hessaa_rts[g] += DaAO3astrnu_[g] * AO_nu[g];
					}
				}
			}
		}
	}
}
