/*
Generated by EigenEinSum

Recommended filename:
Da_mu,nu...AO2a_g,mu,t,s...AO1_g,nu,r---Rho1Hessaa_g,r,t,s.hpp

Einsum expression:
Da(mu, nu), AO2a(g, mu, t|s), AO1(g, nu, r) -> Rho1Hessaa(g, r, t, s)

The einsum expression is decomposed into:
Da(mu, nu), AO2a(g, mu, t|s) -> DaAO2a(g, nu, t|s)
DaAO2a(g, nu, t|s), AO1(g, nu, r) -> Rho1Hessaa(g, r, t, s)

The index paths are derived to be:
TOP
└── s
    └── t
        ├── nu
        │   └── mu
        │       └── g
        └── r
            └── nu
                └── g
*/
{
	[[maybe_unused]] const int g_len = AO2a.dimension(0);
	assert( g_len == AO1.dimension(0) );
	assert( g_len == Rho1Hessaa.dimension(0) );
	[[maybe_unused]] const int r_len = AO1.dimension(2);
	assert( r_len == Rho1Hessaa.dimension(1) );
	[[maybe_unused]] const int t_len = Rho1Hessaa.dimension(2);
	[[maybe_unused]] const int s_len = Rho1Hessaa.dimension(3);
	[[maybe_unused]] const int mu_len = Da.dimension(0);
	assert( mu_len == AO2a.dimension(1) );
	[[maybe_unused]] const int nu_len = Da.dimension(1);
	assert( nu_len == AO1.dimension(1) );
	[[maybe_unused]] const int t_s_len = AO2a.dimension(2);
	EigenTensor<2> DaAO2ast(g_len, nu_len);
	for ( int s = 0; s < s_len; s++ ){
		for ( int t = 0; t < t_len; t++ ){
			int index_array_t_s[] = {t, s}; std::sort(index_array_t_s, index_array_t_s + 2); const int t_s = ( index_array_t_s[0] + 0 ) / 1 + ( index_array_t_s[1] + 0 ) * ( index_array_t_s[1] + 1 ) / 2;
			DaAO2ast.setZero();
			for ( int nu = 0; nu < nu_len; nu++ ){
				for ( int mu = 0; mu < mu_len; mu++ ){
					double* DaAO2ast_nu = &DaAO2ast(0, nu);
					const double* AO2a_mut_s = &AO2a(0, mu, t_s);
					#pragma omp simd simdlen(8) aligned(DaAO2ast_nu, AO2a_mut_s: 64)
					for ( int g = 0; g < g_len; g++ ){
						DaAO2ast_nu[g] += Da(mu, nu) * AO2a_mut_s[g];
					}
				}
			}
			for ( int r = 0; r < r_len; r++ ){
				for ( int nu = 0; nu < nu_len; nu++ ){
					double* Rho1Hessaa_rts = &Rho1Hessaa(0, r, t, s);
					const double* DaAO2ast_nu = &DaAO2ast(0, nu);
					const double* AO1_nur = &AO1(0, nu, r);
					#pragma omp simd simdlen(8) aligned(Rho1Hessaa_rts, DaAO2ast_nu, AO1_nur: 64)
					for ( int g = 0; g < g_len; g++ ){
						Rho1Hessaa_rts[g] += DaAO2ast_nu[g] * AO1_nur[g];
					}
				}
			}
		}
	}
}
