/*
Generated by EigenEinSum

Recommended filename:
Da_mu,nu...AO2a_g,mu,t,s...AO_g,nu---RhoHessaa_g,t,s.hpp

Einsum expression:
Da(mu, nu), AO2a(g, mu, t|s), AO(g, nu) -> RhoHessaa(g, t, s)

The einsum expression is decomposed into:
Da(mu, nu), AO2a(g, mu, t|s) -> DaAO2a(g, nu, t|s)
DaAO2a(g, nu, t|s), AO(g, nu) -> RhoHessaa(g, t, s)

The index paths are derived to be:
TOP
└── s
    └── t
        ├── mu
        │   └── nu
        │       └── g
        └── nu
            └── g
*/
{
	[[maybe_unused]] const int g_len = AO2a.dimension(0);
	assert( g_len == AO.dimension(0) );
	assert( g_len == RhoHessaa.dimension(0) );
	[[maybe_unused]] const int t_len = RhoHessaa.dimension(1);
	[[maybe_unused]] const int s_len = RhoHessaa.dimension(2);
	[[maybe_unused]] const int mu_len = Da.dimension(0);
	assert( mu_len == AO2a.dimension(1) );
	[[maybe_unused]] const int nu_len = Da.dimension(1);
	assert( nu_len == AO.dimension(1) );
	[[maybe_unused]] const int t_s_len = AO2a.dimension(2);
	EigenTensor<2> DaAO2ast(g_len, nu_len);
	for ( int s = 0; s < s_len; s++ ){
		for ( int t = 0; t < t_len; t++ ){
			int index_array_t_s[] = {t, s}; std::sort(index_array_t_s, index_array_t_s + 2); const int t_s = ( index_array_t_s[0] + 0 ) / 1 + ( index_array_t_s[1] + 0 ) * ( index_array_t_s[1] + 1 ) / 2;
			DaAO2ast.setZero();
			for ( int mu = 0; mu < mu_len; mu++ ){
				for ( int nu = 0; nu < nu_len; nu++ ){
					double* DaAO2ast_nu = &DaAO2ast(0, nu);
					const double* AO2a_mut_s = &AO2a(0, mu, t_s);
					#pragma omp simd simdlen(8) aligned(DaAO2ast_nu, AO2a_mut_s: 64)
					for ( int g = 0; g < g_len; g++ ){
						DaAO2ast_nu[g] += Da(mu, nu) * AO2a_mut_s[g];
					}
				}
			}
			for ( int nu = 0; nu < nu_len; nu++ ){
				double* RhoHessaa_ts = &RhoHessaa(0, t, s);
				const double* DaAO2ast_nu = &DaAO2ast(0, nu);
				const double* AO_nu = &AO(0, nu);
				#pragma omp simd simdlen(8) aligned(RhoHessaa_ts, DaAO2ast_nu, AO_nu: 64)
				for ( int g = 0; g < g_len; g++ ){
					RhoHessaa_ts[g] += DaAO2ast_nu[g] * AO_nu[g];
				}
			}
		}
	}
}
