/*
Generated by EigenEinSum

Recommended filename:
Daa_mu,nu,w...AO2a_g,mu,r+t...AO1a_g,nu,s---Rho1Hessaa_g,r,t,s,w.hpp

Einsum expression:
Daa(mu, nu, w), AO2a(g, mu, r+t), AO1a(g, nu, s) -> Rho1Hessaa(g, r, t, s, w)

The einsum expression is decomposed into:
Daa(mu, nu, w), AO2a(g, mu, r+t) -> DaaAO2a(g, nu, r+t, w)
DaaAO2a(g, nu, r+t, w), AO1a(g, nu, s) -> Rho1Hessaa(g, r, t, s, w)

The index paths are derived to be:
TOP
└── w
    ├── t
    │   └── r
    │       └── nu
    │           └── mu
    │               └── g
    └── s
        └── t
            └── r
                └── nu
                    └── g
*/
{
	[[maybe_unused]] const int g_len = AO2a.dimension(0);
	assert( g_len == AO1a.dimension(0) );
	assert( g_len == Rho1Hessaa.dimension(0) );
	[[maybe_unused]] const int r_len = Rho1Hessaa.dimension(1);
	[[maybe_unused]] const int t_len = Rho1Hessaa.dimension(2);
	[[maybe_unused]] const int s_len = AO1a.dimension(2);
	assert( s_len == Rho1Hessaa.dimension(3) );
	[[maybe_unused]] const int w_len = Daa.dimension(2);
	assert( w_len == Rho1Hessaa.dimension(4) );
	[[maybe_unused]] const int mu_len = Daa.dimension(0);
	assert( mu_len == AO2a.dimension(1) );
	[[maybe_unused]] const int nu_len = Daa.dimension(1);
	assert( nu_len == AO1a.dimension(1) );
	[[maybe_unused]] const int r_t_len = AO2a.dimension(2);
	Eigen::Tensor<double, 3> DaaAO2aw(g_len, nu_len, r_t_len);
	for ( int w = 0; w < w_len; w++ ){
		DaaAO2aw.setZero();
		for ( int t = 0; t < t_len; t++ ){
			for ( int r = 0; r < r_len; r++ ){
				int index_array_r_t[] = {r, t}; std::sort(index_array_r_t, index_array_r_t + 2); [[maybe_unused]] const int r_t = ( index_array_r_t[0] + 0 ) / 1 + ( index_array_r_t[1] + 0 ) * ( index_array_r_t[1] + 1 ) / 2;
				if ( !(r <= t) ) continue;
				for ( int nu = 0; nu < nu_len; nu++ ){
					for ( int mu = 0; mu < mu_len; mu++ ){
						double* DaaAO2aw_nur_t = &DaaAO2aw(0, nu, r_t);
						const double* AO2a_mur_t = &AO2a(0, mu, r_t);
						#pragma omp simd simdlen(8) aligned(DaaAO2aw_nur_t, AO2a_mur_t: 64)
						for ( int g = 0; g < g_len; g++ ){
							DaaAO2aw_nur_t[g] += Daa(mu, nu, w) * AO2a_mur_t[g];
						}
					}
				}
			}
		}
		for ( int s = 0; s < s_len; s++ ){
			for ( int t = 0; t < t_len; t++ ){
				for ( int r = 0; r < r_len; r++ ){
					int index_array_r_t[] = {r, t}; std::sort(index_array_r_t, index_array_r_t + 2); [[maybe_unused]] const int r_t = ( index_array_r_t[0] + 0 ) / 1 + ( index_array_r_t[1] + 0 ) * ( index_array_r_t[1] + 1 ) / 2;
					for ( int nu = 0; nu < nu_len; nu++ ){
						double* Rho1Hessaa_rtsw = &Rho1Hessaa(0, r, t, s, w);
						const double* DaaAO2aw_nur_t = &DaaAO2aw(0, nu, r_t);
						const double* AO1a_nus = &AO1a(0, nu, s);
						#pragma omp simd simdlen(8) aligned(Rho1Hessaa_rtsw, DaaAO2aw_nur_t, AO1a_nus: 64)
						for ( int g = 0; g < g_len; g++ ){
							Rho1Hessaa_rtsw[g] += DaaAO2aw_nur_t[g] * AO1a_nus[g];
						}
					}
				}
			}
		}
	}
}
