/*
Generated by EigenEinSum

Recommended filename:
Daa_mu,nu...AO2sa_g,mu,r,t...AO1sa_g,nu,s---Rho1Hesssaa_g,r,t,s.hpp

Einsum expression:
Daa(mu, nu), AO2sa(g, mu, r|t), AO1sa(g, nu, s) -> Rho1Hesssaa(g, r, t, s)

The einsum expression is decomposed into:
Daa(mu, nu), AO2sa(g, mu, r|t) -> DaaAO2sa(g, r|t, nu)
DaaAO2sa(g, r|t, nu), AO1sa(g, nu, s) -> Rho1Hesssaa(g, r, t, s)

The index paths are derived to be:
TOP
└── nu
    ├── mu
    │   └── t
    │       └── r
    │           └── g
    └── s
        └── t
            └── r
                └── g
*/
{
	const int g_len = AO2sa.dimension(0);
	assert( g_len == AO1sa.dimension(0) );
	assert( g_len == Rho1Hesssaa.dimension(0) );
	const int r_len = Rho1Hesssaa.dimension(1);
	const int t_len = Rho1Hesssaa.dimension(2);
	const int s_len = AO1sa.dimension(2);
	assert( s_len == Rho1Hesssaa.dimension(3) );
	const int mu_len = Daa.dimension(0);
	assert( mu_len == AO2sa.dimension(1) );
	const int nu_len = Daa.dimension(1);
	assert( nu_len == AO1sa.dimension(1) );
	const int r_t_len = AO2sa.dimension(2);
	Eigen::Tensor<double, 2> DaaAO2sanu(g_len, r_t_len);
	for ( int nu = 0; nu < nu_len; nu++ ){
		DaaAO2sanu.setZero();
		for ( int mu = 0; mu < mu_len; mu++ ){
			for ( int t = 0; t < t_len; t++ ){
				for ( int r = 0; r < r_len; r++ ){
					int index_array_r_t[] = {r, t}; std::sort(index_array_r_t, index_array_r_t + 2); const int r_t = ( index_array_r_t[0] + 0 ) / 1 + ( index_array_r_t[1] + 0 ) * ( index_array_r_t[1] + 1 ) / 2;
					if ( r > t ) continue;
					for ( int g = 0; g < g_len; g++ ){
						DaaAO2sanu(g, r_t) += Daa(mu, nu) * AO2sa(g, mu, r_t);
					}
				}
			}
		}
		for ( int s = 0; s < s_len; s++ ){
			for ( int t = 0; t < t_len; t++ ){
				for ( int r = 0; r < r_len; r++ ){
					int index_array_r_t[] = {r, t}; std::sort(index_array_r_t, index_array_r_t + 2); const int r_t = ( index_array_r_t[0] + 0 ) / 1 + ( index_array_r_t[1] + 0 ) * ( index_array_r_t[1] + 1 ) / 2;
					for ( int g = 0; g < g_len; g++ ){
						Rho1Hesssaa(g, r, t, s) += DaaAO2sanu(g, r_t) * AO1sa(g, nu, s);
					}
				}
			}
		}
	}
}
