/*
Generated by EigenEinSum

Recommended filename:
Daa_mu,nu...AO1a_g,mu,t...AO1a_g,nu,s---RhoHessaa_g,t,s.hpp

Einsum expression:
Daa(mu, nu), AO1a(g, mu, t), AO1a(g, nu, s) -> RhoHessaa(g, t, s)

The einsum expression is decomposed into:
Daa(mu, nu), AO1a(g, mu, t) -> DaaAO1a(g, nu, t)
DaaAO1a(g, nu, t), AO1a(g, nu, s) -> RhoHessaa(g, t, s)

The index paths are derived to be:
TOP
├── t
│   └── nu
│       └── mu
│           └── g
└── s
    └── t
        └── nu
            └── g
*/
{
	[[maybe_unused]] const int g_len = AO1a.dimension(0);
	assert( g_len == AO1a.dimension(0) );
	assert( g_len == RhoHessaa.dimension(0) );
	[[maybe_unused]] const int t_len = AO1a.dimension(2);
	assert( t_len == RhoHessaa.dimension(1) );
	[[maybe_unused]] const int s_len = AO1a.dimension(2);
	assert( s_len == RhoHessaa.dimension(2) );
	[[maybe_unused]] const int mu_len = Daa.dimension(0);
	assert( mu_len == AO1a.dimension(1) );
	[[maybe_unused]] const int nu_len = Daa.dimension(1);
	assert( nu_len == AO1a.dimension(1) );
	EigenTensor<3> DaaAO1a(g_len, nu_len, t_len);
	DaaAO1a.setZero();
	for ( int t = 0; t < t_len; t++ ){
		for ( int nu = 0; nu < nu_len; nu++ ){
			for ( int mu = 0; mu < mu_len; mu++ ){
				double* DaaAO1a_nut = &DaaAO1a(0, nu, t);
				const double* AO1a_mut = &AO1a(0, mu, t);
				#pragma omp simd simdlen(8) aligned(DaaAO1a_nut, AO1a_mut: 64)
				for ( int g = 0; g < g_len; g++ ){
					DaaAO1a_nut[g] += Daa(mu, nu) * AO1a_mut[g];
				}
			}
		}
	}
	for ( int s = 0; s < s_len; s++ ){
		for ( int t = 0; t < t_len; t++ ){
			for ( int nu = 0; nu < nu_len; nu++ ){
				double* RhoHessaa_ts = &RhoHessaa(0, t, s);
				const double* DaaAO1a_nut = &DaaAO1a(0, nu, t);
				const double* AO1a_nus = &AO1a(0, nu, s);
				#pragma omp simd simdlen(8) aligned(RhoHessaa_ts, DaaAO1a_nut, AO1a_nus: 64)
				for ( int g = 0; g < g_len; g++ ){
					RhoHessaa_ts[g] += DaaAO1a_nut[g] * AO1a_nus[g];
				}
			}
		}
	}
}
