/*
Generated by EigenEinSum

Recommended filename:
Daa_mu,nu,w...AO1a_g,mu,t...AO1a_g,nu,s---RhoHessaa_g,t,s,w.hpp

Einsum expression:
Daa(mu, nu, w), AO1a(g, mu, t), AO1a(g, nu, s) -> RhoHessaa(g, t, s, w)

The einsum expression is decomposed into:
Daa(mu, nu, w), AO1a(g, mu, t) -> DaaAO1a(g, nu, t, w)
DaaAO1a(g, nu, t, w), AO1a(g, nu, s) -> RhoHessaa(g, t, s, w)

The index paths are derived to be:
TOP
└── w
    ├── t
    │   └── nu
    │       └── mu
    │           └── g
    └── s
        └── t
            └── nu
                └── g
*/
{
	[[maybe_unused]] const int g_len = AO1a.dimension(0);
	assert( g_len == AO1a.dimension(0) );
	assert( g_len == RhoHessaa.dimension(0) );
	[[maybe_unused]] const int t_len = AO1a.dimension(2);
	assert( t_len == RhoHessaa.dimension(1) );
	[[maybe_unused]] const int s_len = AO1a.dimension(2);
	assert( s_len == RhoHessaa.dimension(2) );
	[[maybe_unused]] const int w_len = Daa.dimension(2);
	assert( w_len == RhoHessaa.dimension(3) );
	[[maybe_unused]] const int mu_len = Daa.dimension(0);
	assert( mu_len == AO1a.dimension(1) );
	[[maybe_unused]] const int nu_len = Daa.dimension(1);
	assert( nu_len == AO1a.dimension(1) );
	Eigen::Tensor<double, 3> DaaAO1aw(g_len, nu_len, t_len);
	for ( int w = 0; w < w_len; w++ ){
		DaaAO1aw.setZero();
		for ( int t = 0; t < t_len; t++ ){
			for ( int nu = 0; nu < nu_len; nu++ ){
				for ( int mu = 0; mu < mu_len; mu++ ){
					double* DaaAO1aw_nut = &DaaAO1aw(0, nu, t);
					const double* AO1a_mut = &AO1a(0, mu, t);
					#pragma omp simd simdlen(8) aligned(DaaAO1aw_nut, AO1a_mut: 64)
					for ( int g = 0; g < g_len; g++ ){
						DaaAO1aw_nut[g] += Daa(mu, nu, w) * AO1a_mut[g];
					}
				}
			}
		}
		for ( int s = 0; s < s_len; s++ ){
			for ( int t = 0; t < t_len; t++ ){
				for ( int nu = 0; nu < nu_len; nu++ ){
					double* RhoHessaa_tsw = &RhoHessaa(0, t, s, w);
					const double* DaaAO1aw_nut = &DaaAO1aw(0, nu, t);
					const double* AO1a_nus = &AO1a(0, nu, s);
					#pragma omp simd simdlen(8) aligned(RhoHessaa_tsw, DaaAO1aw_nut, AO1a_nus: 64)
					for ( int g = 0; g < g_len; g++ ){
						RhoHessaa_tsw[g] += DaaAO1aw_nut[g] * AO1a_nus[g];
					}
				}
			}
		}
	}
}
