/*
Generated by EigenEinSum

Recommended filename:
Dab_mu,nu,w...AO1a_g,mu,t...AO1b_g,nu,s---RhoHessab_g,t,s,w.hpp

Einsum expression:
Dab(mu, nu, w), AO1a(g, mu, t), AO1b(g, nu, s) -> RhoHessab(g, t, s, w)

The einsum expression is decomposed into:
Dab(mu, nu, w), AO1a(g, mu, t) -> DabAO1a(g, nu, t, w)
DabAO1a(g, nu, t, w), AO1b(g, nu, s) -> RhoHessab(g, t, s, w)

The index paths are derived to be:
TOP
└── w
    ├── t
    │   └── nu
    │       └── mu
    │           └── g
    └── s
        └── t
            └── nu
                └── g
*/
{
	[[maybe_unused]] const int g_len = AO1a.dimension(0);
	assert( g_len == AO1b.dimension(0) );
	assert( g_len == RhoHessab.dimension(0) );
	[[maybe_unused]] const int t_len = AO1a.dimension(2);
	assert( t_len == RhoHessab.dimension(1) );
	[[maybe_unused]] const int s_len = AO1b.dimension(2);
	assert( s_len == RhoHessab.dimension(2) );
	[[maybe_unused]] const int w_len = Dab.dimension(2);
	assert( w_len == RhoHessab.dimension(3) );
	[[maybe_unused]] const int mu_len = Dab.dimension(0);
	assert( mu_len == AO1a.dimension(1) );
	[[maybe_unused]] const int nu_len = Dab.dimension(1);
	assert( nu_len == AO1b.dimension(1) );
	Eigen::Tensor<double, 3> DabAO1aw(g_len, nu_len, t_len);
	for ( int w = 0; w < w_len; w++ ){
		DabAO1aw.setZero();
		for ( int t = 0; t < t_len; t++ ){
			for ( int nu = 0; nu < nu_len; nu++ ){
				for ( int mu = 0; mu < mu_len; mu++ ){
					double* DabAO1aw_nut = &DabAO1aw(0, nu, t);
					const double* AO1a_mut = &AO1a(0, mu, t);
					#pragma omp simd simdlen(8) aligned(DabAO1aw_nut, AO1a_mut: 64)
					for ( int g = 0; g < g_len; g++ ){
						DabAO1aw_nut[g] += Dab(mu, nu, w) * AO1a_mut[g];
					}
				}
			}
		}
		for ( int s = 0; s < s_len; s++ ){
			for ( int t = 0; t < t_len; t++ ){
				for ( int nu = 0; nu < nu_len; nu++ ){
					double* RhoHessab_tsw = &RhoHessab(0, t, s, w);
					const double* DabAO1aw_nut = &DabAO1aw(0, nu, t);
					const double* AO1b_nus = &AO1b(0, nu, s);
					#pragma omp simd simdlen(8) aligned(RhoHessab_tsw, DabAO1aw_nut, AO1b_nus: 64)
					for ( int g = 0; g < g_len; g++ ){
						RhoHessab_tsw[g] += DabAO1aw_nut[g] * AO1b_nus[g];
					}
				}
			}
		}
	}
}
