/*
Generated by EigenEinSum

Recommended filename:
Dab_mu,nu,w...AO2b_g,nu,r+s...AO1a_g,mu,t---Rho1Hessab_g,r,t,s,w.hpp

Einsum expression:
Dab(mu, nu, w), AO2b(g, nu, r+s), AO1a(g, mu, t) -> Rho1Hessab(g, r, t, s, w)

The einsum expression is decomposed into:
Dab(mu, nu, w), AO2b(g, nu, r+s) -> DabAO2b(g, mu, s+r, w)
DabAO2b(g, mu, s+r, w), AO1a(g, mu, t) -> Rho1Hessab(g, r, t, s, w)

The index paths are derived to be:
TOP
└── w
    └── r
        └── s
            └── mu
                ├── nu
                │   └── g
                └── t
                    └── g
*/
{
	[[maybe_unused]] const int g_len = AO2b.dimension(0);
	assert( g_len == AO1a.dimension(0) );
	assert( g_len == Rho1Hessab.dimension(0) );
	[[maybe_unused]] const int r_len = Rho1Hessab.dimension(1);
	[[maybe_unused]] const int t_len = AO1a.dimension(2);
	assert( t_len == Rho1Hessab.dimension(2) );
	[[maybe_unused]] const int s_len = Rho1Hessab.dimension(3);
	[[maybe_unused]] const int w_len = Dab.dimension(2);
	assert( w_len == Rho1Hessab.dimension(4) );
	[[maybe_unused]] const int mu_len = Dab.dimension(0);
	assert( mu_len == AO1a.dimension(1) );
	[[maybe_unused]] const int nu_len = Dab.dimension(1);
	assert( nu_len == AO2b.dimension(1) );
	[[maybe_unused]] const int r_s_len = AO2b.dimension(2);
	Eigen::Tensor<double, 1> DabAO2bwrsmu(g_len);
	for ( int w = 0; w < w_len; w++ ){
		for ( int r = 0; r < r_len; r++ ){
			for ( int s = 0; s < s_len; s++ ){
				int index_array_r_s[] = {r, s}; std::sort(index_array_r_s, index_array_r_s + 2); [[maybe_unused]] const int r_s = ( index_array_r_s[0] + 0 ) / 1 + ( index_array_r_s[1] + 0 ) * ( index_array_r_s[1] + 1 ) / 2;
				for ( int mu = 0; mu < mu_len; mu++ ){
					DabAO2bwrsmu.setZero();
					for ( int nu = 0; nu < nu_len; nu++ ){
						double* DabAO2bwrsmu_ = &DabAO2bwrsmu(0);
						const double* AO2b_nur_s = &AO2b(0, nu, r_s);
						#pragma omp simd simdlen(8) aligned(DabAO2bwrsmu_, AO2b_nur_s: 64)
						for ( int g = 0; g < g_len; g++ ){
							DabAO2bwrsmu_[g] += Dab(mu, nu, w) * AO2b_nur_s[g];
						}
					}
					for ( int t = 0; t < t_len; t++ ){
						double* Rho1Hessab_rtsw = &Rho1Hessab(0, r, t, s, w);
						const double* DabAO2bwrsmu_ = &DabAO2bwrsmu(0);
						const double* AO1a_mut = &AO1a(0, mu, t);
						#pragma omp simd simdlen(8) aligned(Rho1Hessab_rtsw, DabAO2bwrsmu_, AO1a_mut: 64)
						for ( int g = 0; g < g_len; g++ ){
							Rho1Hessab_rtsw[g] += DabAO2bwrsmu_[g] * AO1a_mut[g];
						}
					}
				}
			}
		}
	}
}
