/*
Generated by EigenEinSum

Recommended filename:
Dab_mu,nu...AO1a_g,mu,t...AO1b_g,nu,s---RhoHessab_g,t,s.hpp

Einsum expression:
Dab(mu, nu), AO1a(g, mu, t), AO1b(g, nu, s) -> RhoHessab(g, t, s)

The einsum expression is decomposed into:
Dab(mu, nu), AO1a(g, mu, t) -> DabAO1a(g, nu, t)
DabAO1a(g, nu, t), AO1b(g, nu, s) -> RhoHessab(g, t, s)

The index paths are derived to be:
TOP
├── t
│   └── nu
│       └── mu
│           └── g
└── s
    └── t
        └── nu
            └── g
*/
{
	[[maybe_unused]] const int g_len = AO1a.dimension(0);
	assert( g_len == AO1b.dimension(0) );
	assert( g_len == RhoHessab.dimension(0) );
	[[maybe_unused]] const int t_len = AO1a.dimension(2);
	assert( t_len == RhoHessab.dimension(1) );
	[[maybe_unused]] const int s_len = AO1b.dimension(2);
	assert( s_len == RhoHessab.dimension(2) );
	[[maybe_unused]] const int mu_len = Dab.dimension(0);
	assert( mu_len == AO1a.dimension(1) );
	[[maybe_unused]] const int nu_len = Dab.dimension(1);
	assert( nu_len == AO1b.dimension(1) );
	EigenTensor<3> DabAO1a(g_len, nu_len, t_len);
	DabAO1a.setZero();
	for ( int t = 0; t < t_len; t++ ){
		for ( int nu = 0; nu < nu_len; nu++ ){
			for ( int mu = 0; mu < mu_len; mu++ ){
				double* DabAO1a_nut = &DabAO1a(0, nu, t);
				const double* AO1a_mut = &AO1a(0, mu, t);
				#pragma omp simd simdlen(8) aligned(DabAO1a_nut, AO1a_mut: 64)
				for ( int g = 0; g < g_len; g++ ){
					DabAO1a_nut[g] += Dab(mu, nu) * AO1a_mut[g];
				}
			}
		}
	}
	for ( int s = 0; s < s_len; s++ ){
		for ( int t = 0; t < t_len; t++ ){
			for ( int nu = 0; nu < nu_len; nu++ ){
				double* RhoHessab_ts = &RhoHessab(0, t, s);
				const double* DabAO1a_nut = &DabAO1a(0, nu, t);
				const double* AO1b_nus = &AO1b(0, nu, s);
				#pragma omp simd simdlen(8) aligned(RhoHessab_ts, DabAO1a_nut, AO1b_nus: 64)
				for ( int g = 0; g < g_len; g++ ){
					RhoHessab_ts[g] += DabAO1a_nut[g] * AO1b_nus[g];
				}
			}
		}
	}
}
