/*
Generated by EigenEinSum

Recommended filename:
Dab_mu,nu...AO2a_g,mu,r,t...AO1b_g,nu,s---Rho1Hessab_g,r,t,s.hpp

Einsum expression:
Dab(mu, nu), AO2a(g, mu, r|t), AO1b(g, nu, s) -> Rho1Hessab(g, r, t, s)

The einsum expression is decomposed into:
Dab(mu, nu), AO2a(g, mu, r|t) -> DabAO2a(g, nu, r|t)
DabAO2a(g, nu, r|t), AO1b(g, nu, s) -> Rho1Hessab(g, r, t, s)

The index paths are derived to be:
TOP
├── t
│   └── r
│       └── nu
│           └── mu
│               └── g
└── s
    └── t
        └── r
            └── nu
                └── g
*/
{
	[[maybe_unused]] const int g_len = AO2a.dimension(0);
	assert( g_len == AO1b.dimension(0) );
	assert( g_len == Rho1Hessab.dimension(0) );
	[[maybe_unused]] const int r_len = Rho1Hessab.dimension(1);
	[[maybe_unused]] const int t_len = Rho1Hessab.dimension(2);
	[[maybe_unused]] const int s_len = AO1b.dimension(2);
	assert( s_len == Rho1Hessab.dimension(3) );
	[[maybe_unused]] const int mu_len = Dab.dimension(0);
	assert( mu_len == AO2a.dimension(1) );
	[[maybe_unused]] const int nu_len = Dab.dimension(1);
	assert( nu_len == AO1b.dimension(1) );
	[[maybe_unused]] const int r_t_len = AO2a.dimension(2);
	EigenTensor<3> DabAO2a(g_len, nu_len, r_t_len);
	DabAO2a.setZero();
	for ( int t = 0; t < t_len; t++ ){
		for ( int r = 0; r < r_len; r++ ){
			int index_array_r_t[] = {r, t}; std::sort(index_array_r_t, index_array_r_t + 2); const int r_t = ( index_array_r_t[0] + 0 ) / 1 + ( index_array_r_t[1] + 0 ) * ( index_array_r_t[1] + 1 ) / 2;
			if ( !(r <= t) ) continue;
			for ( int nu = 0; nu < nu_len; nu++ ){
				for ( int mu = 0; mu < mu_len; mu++ ){
					double* DabAO2a_nur_t = &DabAO2a(0, nu, r_t);
					const double* AO2a_mur_t = &AO2a(0, mu, r_t);
					#pragma omp simd simdlen(8) aligned(DabAO2a_nur_t, AO2a_mur_t: 64)
					for ( int g = 0; g < g_len; g++ ){
						DabAO2a_nur_t[g] += Dab(mu, nu) * AO2a_mur_t[g];
					}
				}
			}
		}
	}
	for ( int s = 0; s < s_len; s++ ){
		for ( int t = 0; t < t_len; t++ ){
			for ( int r = 0; r < r_len; r++ ){
				int index_array_r_t[] = {r, t}; std::sort(index_array_r_t, index_array_r_t + 2); const int r_t = ( index_array_r_t[0] + 0 ) / 1 + ( index_array_r_t[1] + 0 ) * ( index_array_r_t[1] + 1 ) / 2;
				for ( int nu = 0; nu < nu_len; nu++ ){
					double* Rho1Hessab_rts = &Rho1Hessab(0, r, t, s);
					const double* DabAO2a_nur_t = &DabAO2a(0, nu, r_t);
					const double* AO1b_nus = &AO1b(0, nu, s);
					#pragma omp simd simdlen(8) aligned(Rho1Hessab_rts, DabAO2a_nur_t, AO1b_nus: 64)
					for ( int g = 0; g < g_len; g++ ){
						Rho1Hessab_rts[g] += DabAO2a_nur_t[g] * AO1b_nus[g];
					}
				}
			}
		}
	}
}
