/*
Generated by EigenEinSum

Recommended filename:
Dab_mu,nu,w...AO2a_g,mu,r+t...AO1b_g,nu,s---Rho1Hessab_g,r,t,s,w.hpp

Einsum expression:
Dab(mu, nu, w), AO2a(g, mu, r+t), AO1b(g, nu, s) -> Rho1Hessab(g, r, t, s, w)

The einsum expression is decomposed into:
Dab(mu, nu, w), AO2a(g, mu, r+t) -> DabAO2a(g, nu, t+r, w)
DabAO2a(g, nu, t+r, w), AO1b(g, nu, s) -> Rho1Hessab(g, r, t, s, w)

The index paths are derived to be:
TOP
└── w
    └── r
        └── t
            └── nu
                ├── mu
                │   └── g
                └── s
                    └── g
*/
{
	[[maybe_unused]] const int g_len = AO2a.dimension(0);
	assert( g_len == AO1b.dimension(0) );
	assert( g_len == Rho1Hessab.dimension(0) );
	[[maybe_unused]] const int r_len = Rho1Hessab.dimension(1);
	[[maybe_unused]] const int t_len = Rho1Hessab.dimension(2);
	[[maybe_unused]] const int s_len = AO1b.dimension(2);
	assert( s_len == Rho1Hessab.dimension(3) );
	[[maybe_unused]] const int w_len = Dab.dimension(2);
	assert( w_len == Rho1Hessab.dimension(4) );
	[[maybe_unused]] const int mu_len = Dab.dimension(0);
	assert( mu_len == AO2a.dimension(1) );
	[[maybe_unused]] const int nu_len = Dab.dimension(1);
	assert( nu_len == AO1b.dimension(1) );
	[[maybe_unused]] const int r_t_len = AO2a.dimension(2);
	Eigen::Tensor<double, 1> DabAO2awrtnu(g_len);
	for ( int w = 0; w < w_len; w++ ){
		for ( int r = 0; r < r_len; r++ ){
			for ( int t = 0; t < t_len; t++ ){
				int index_array_r_t[] = {r, t}; std::sort(index_array_r_t, index_array_r_t + 2); [[maybe_unused]] const int r_t = ( index_array_r_t[0] + 0 ) / 1 + ( index_array_r_t[1] + 0 ) * ( index_array_r_t[1] + 1 ) / 2;
				for ( int nu = 0; nu < nu_len; nu++ ){
					DabAO2awrtnu.setZero();
					for ( int mu = 0; mu < mu_len; mu++ ){
						double* DabAO2awrtnu_ = &DabAO2awrtnu(0);
						const double* AO2a_mur_t = &AO2a(0, mu, r_t);
						#pragma omp simd simdlen(8) aligned(DabAO2awrtnu_, AO2a_mur_t: 64)
						for ( int g = 0; g < g_len; g++ ){
							DabAO2awrtnu_[g] += Dab(mu, nu, w) * AO2a_mur_t[g];
						}
					}
					for ( int s = 0; s < s_len; s++ ){
						double* Rho1Hessab_rtsw = &Rho1Hessab(0, r, t, s, w);
						const double* DabAO2awrtnu_ = &DabAO2awrtnu(0);
						const double* AO1b_nus = &AO1b(0, nu, s);
						#pragma omp simd simdlen(8) aligned(Rho1Hessab_rtsw, DabAO2awrtnu_, AO1b_nus: 64)
						for ( int g = 0; g < g_len; g++ ){
							Rho1Hessab_rtsw[g] += DabAO2awrtnu_[g] * AO1b_nus[g];
						}
					}
				}
			}
		}
	}
}
