/*
Generated by EigenEinSum

Recommended filename:
Dab_mu,nu...AO1a_g,mu,t...AO2b_g,nu,r,s---Rho1Hessab_g,r,t,s.hpp

Einsum expression:
Dab(mu, nu), AO1a(g, mu, t), AO2b(g, nu, r|s) -> Rho1Hessab(g, r, t, s)

The einsum expression is decomposed into:
Dab(mu, nu), AO1a(g, mu, t) -> DabAO1a(g, nu, t)
DabAO1a(g, nu, t), AO2b(g, nu, r|s) -> Rho1Hessab(g, r, t, s)

The index paths are derived to be:
TOP
├── t
│   └── nu
│       └── mu
│           └── g
└── s
    └── r
        └── t
            └── nu
                └── g
*/
{
	[[maybe_unused]] const int g_len = AO1a.dimension(0);
	assert( g_len == AO2b.dimension(0) );
	assert( g_len == Rho1Hessab.dimension(0) );
	[[maybe_unused]] const int r_len = Rho1Hessab.dimension(1);
	[[maybe_unused]] const int t_len = AO1a.dimension(2);
	assert( t_len == Rho1Hessab.dimension(2) );
	[[maybe_unused]] const int s_len = Rho1Hessab.dimension(3);
	[[maybe_unused]] const int mu_len = Dab.dimension(0);
	assert( mu_len == AO1a.dimension(1) );
	[[maybe_unused]] const int nu_len = Dab.dimension(1);
	assert( nu_len == AO2b.dimension(1) );
	[[maybe_unused]] const int r_s_len = AO2b.dimension(2);
	EigenTensor<3> DabAO1a(g_len, nu_len, t_len);
	DabAO1a.setZero();
	for ( int t = 0; t < t_len; t++ ){
		for ( int nu = 0; nu < nu_len; nu++ ){
			for ( int mu = 0; mu < mu_len; mu++ ){
				double* DabAO1a_nut = &DabAO1a(0, nu, t);
				const double* AO1a_mut = &AO1a(0, mu, t);
				#pragma omp simd simdlen(8) aligned(DabAO1a_nut, AO1a_mut: 64)
				for ( int g = 0; g < g_len; g++ ){
					DabAO1a_nut[g] += Dab(mu, nu) * AO1a_mut[g];
				}
			}
		}
	}
	for ( int s = 0; s < s_len; s++ ){
		for ( int r = 0; r < r_len; r++ ){
			int index_array_r_s[] = {r, s}; std::sort(index_array_r_s, index_array_r_s + 2); const int r_s = ( index_array_r_s[0] + 0 ) / 1 + ( index_array_r_s[1] + 0 ) * ( index_array_r_s[1] + 1 ) / 2;
			for ( int t = 0; t < t_len; t++ ){
				for ( int nu = 0; nu < nu_len; nu++ ){
					double* Rho1Hessab_rts = &Rho1Hessab(0, r, t, s);
					const double* DabAO1a_nut = &DabAO1a(0, nu, t);
					const double* AO2b_nur_s = &AO2b(0, nu, r_s);
					#pragma omp simd simdlen(8) aligned(Rho1Hessab_rts, DabAO1a_nut, AO2b_nur_s: 64)
					for ( int g = 0; g < g_len; g++ ){
						Rho1Hessab_rts[g] += DabAO1a_nut[g] * AO2b_nur_s[g];
					}
				}
			}
		}
	}
}
