/*
Generated by EigenEinSum

Recommended filename:
DU_mu,nu...AOs_g,mu...AOs_g,nu---RhoUs_g.hpp

Einsum expression:
DU(mu, nu), AOs(g, mu), AOs(g, nu) -> RhoUs(g)

The einsum expression is decomposed into:
DU(mu, nu), AOs(g, mu) -> DUAOs(g, nu)
DUAOs(g, nu), AOs(g, nu) -> RhoUs(g)

The index paths are derived to be:
TOP
└── nu
    ├── mu
    │   └── g
    └── g
*/
{
	const int g_len = AOs.dimensions()[0];
	assert( g_len == AOs.dimensions()[0] );
	assert( g_len == RhoUs.dimensions()[0] );
	const int mu_len = DU.dimensions()[0];
	assert( mu_len == AOs.dimensions()[1] );
	const int nu_len = DU.dimensions()[1];
	assert( nu_len == AOs.dimensions()[1] );
	Eigen::Tensor<double, 1> DUAOsnu(g_len);
	for ( int nu = 0; nu < nu_len; nu++ ){
		DUAOsnu.setZero();
		for ( int mu = 0; mu < mu_len; mu++ ){
			for ( int g = 0; g < g_len; g++ ){
				DUAOsnu(g) += DU(mu, nu) * AOs(g, mu);
			}
		}
		for ( int g = 0; g < g_len; g++ ){
			RhoUs(g) += DUAOsnu(g) * AOs(g, nu);
		}
	}
}
