/*
Generated by EigenEinSum

Recommended filename:
Rho1s_g,r...Rho1s_g,r---Sigmas_g.hpp

Einsum expression:
Rho1s(g, r), Rho1s(g, r) -> Sigmas(g)

The einsum expression is decomposed into:
Rho1s(g, r), Rho1s(g, r) -> Sigmas(g)

The index paths are derived to be:
TOP
└── r
    └── g
*/
{
	const int g_len = Rho1s.dimensions()[0];
	assert( g_len == Rho1s.dimensions()[0] );
	assert( g_len == Sigmas.dimensions()[0] );
	const int r_len = Rho1s.dimensions()[1];
	assert( r_len == Rho1s.dimensions()[1] );
	for ( int r = 0; r < r_len; r++ ){
		for ( int g = 0; g < g_len; g++ ){
			Sigmas(g) += Rho1s(g, r) * Rho1s(g, r);
		}
	}
}
