/*
Generated by EigenEinSum

Recommended filename:
Rho1U_g,r,mat,u...Rho1_g,r,v---SigmaU_g,mat,u+v.hpp

Einsum expression:
Rho1U(g, r, mat, u), Rho1(g, r, v) -> SigmaU(g, mat, u+v)

The einsum expression is decomposed into:
Rho1U(g, r, mat, u), Rho1(g, r, v) -> SigmaU(g, mat, u+v)

The index paths are derived to be:
TOP
└── v
    └── u
        └── mat
            └── r
                └── g
*/
{
	[[maybe_unused]] const int g_len = Rho1U.dimension(0);
	assert( g_len == Rho1.dimension(0) );
	assert( g_len == SigmaU.dimension(0) );
	[[maybe_unused]] const int mat_len = Rho1U.dimension(2);
	assert( mat_len == SigmaU.dimension(1) );
	[[maybe_unused]] const int u_v_len = SigmaU.dimension(2);
	[[maybe_unused]] const int r_len = Rho1U.dimension(1);
	assert( r_len == Rho1.dimension(1) );
	[[maybe_unused]] const int u_len = Rho1U.dimension(3);
	[[maybe_unused]] const int v_len = Rho1.dimension(2);
	for ( int v = 0; v < v_len; v++ ){
		for ( int u = 0; u < u_len; u++ ){
			if ( !(u <= v) ) continue;
			int index_array_u_v[] = {u, v}; std::sort(index_array_u_v, index_array_u_v + 2); [[maybe_unused]] const int u_v = ( index_array_u_v[0] + 0 ) / 1 + ( index_array_u_v[1] + 0 ) * ( index_array_u_v[1] + 1 ) / 2;
			for ( int mat = 0; mat < mat_len; mat++ ){
				for ( int r = 0; r < r_len; r++ ){
					double* SigmaU_matu_v = &SigmaU(0, mat, u_v);
					const double* Rho1U_rmatu = &Rho1U(0, r, mat, u);
					const double* Rho1_rv = &Rho1(0, r, v);
					#pragma omp simd simdlen(8) aligned(SigmaU_matu_v, Rho1U_rmatu, Rho1_rv: 64)
					for ( int g = 0; g < g_len; g++ ){
						SigmaU_matu_v[g] += Rho1U_rmatu[g] * Rho1_rv[g];
					}
				}
			}
		}
	}
}
