/*
Generated by EigenEinSum

Recommended filename:
Rho1Hess_g,r,t,a,s,b...Rho1_g,r---SigmaHess_g,t,a,s,b.hpp

Einsum expression:
Rho1Hess(g, r, t, a, s, b), Rho1(g, r) -> SigmaHess(g, t, a, s, b)

The einsum expression is decomposed into:
Rho1Hess(g, r, t, a, s, b), Rho1(g, r) -> SigmaHess(g, t, a, s, b)

The index paths are derived to be:
TOP
└── b
    └── s
        └── a
            └── t
                └── r
                    └── g
*/
{
	[[maybe_unused]] const int g_len = Rho1Hess.dimension(0);
	assert( g_len == Rho1.dimension(0) );
	assert( g_len == SigmaHess.dimension(0) );
	[[maybe_unused]] const int t_len = Rho1Hess.dimension(2);
	assert( t_len == SigmaHess.dimension(1) );
	[[maybe_unused]] const int a_len = Rho1Hess.dimension(3);
	assert( a_len == SigmaHess.dimension(2) );
	[[maybe_unused]] const int s_len = Rho1Hess.dimension(4);
	assert( s_len == SigmaHess.dimension(3) );
	[[maybe_unused]] const int b_len = Rho1Hess.dimension(5);
	assert( b_len == SigmaHess.dimension(4) );
	[[maybe_unused]] const int r_len = Rho1Hess.dimension(1);
	assert( r_len == Rho1.dimension(1) );
	for ( int b = 0; b < b_len; b++ ){
		for ( int s = 0; s < s_len; s++ ){
			for ( int a = 0; a < a_len; a++ ){
				for ( int t = 0; t < t_len; t++ ){
					for ( int r = 0; r < r_len; r++ ){
						double* SigmaHess_tasb = &SigmaHess(0, t, a, s, b);
						const double* Rho1Hess_rtasb = &Rho1Hess(0, r, t, a, s, b);
						const double* Rho1_r = &Rho1(0, r);
						#pragma omp simd simdlen(8) aligned(SigmaHess_tasb, Rho1Hess_rtasb, Rho1_r: 64)
						for ( int g = 0; g < g_len; g++ ){
							SigmaHess_tasb[g] += Rho1Hess_rtasb[g] * Rho1_r[g];
						}
					}
				}
			}
		}
	}
}
