/*
Generated by EigenEinSum

Recommended filename:
Rho1U_g,r,mat...Rho1_g,r---SigmaU_g,mat.hpp

Einsum expression:
Rho1U(g, r, mat), Rho1(g, r) -> SigmaU(g, mat)

The einsum expression is decomposed into:
Rho1U(g, r, mat), Rho1(g, r) -> SigmaU(g, mat)

The index paths are derived to be:
TOP
└── mat
    └── r
        └── g
*/
{
	[[maybe_unused]] const int g_len = Rho1U.dimension(0);
	assert( g_len == Rho1.dimension(0) );
	assert( g_len == SigmaU.dimension(0) );
	[[maybe_unused]] const int mat_len = Rho1U.dimension(2);
	assert( mat_len == SigmaU.dimension(1) );
	[[maybe_unused]] const int r_len = Rho1U.dimension(1);
	assert( r_len == Rho1.dimension(1) );
	for ( int mat = 0; mat < mat_len; mat++ ){
		for ( int r = 0; r < r_len; r++ ){
			double* SigmaU_mat = &SigmaU(0, mat);
			const double* Rho1U_rmat = &Rho1U(0, r, mat);
			const double* Rho1_r = &Rho1(0, r);
			#pragma omp simd simdlen(8) aligned(SigmaU_mat, Rho1U_rmat, Rho1_r: 64)
			for ( int g = 0; g < g_len; g++ ){
				SigmaU_mat[g] += Rho1U_rmat[g] * Rho1_r[g];
			}
		}
	}
}
