/*
Generated by EigenEinSum

Recommended filename:
Rho1_g,r...Rho1_g,r---Sigma_g.hpp

Einsum expression:
Rho1(g, r), Rho1(g, r) -> Sigma(g)

The einsum expression is decomposed into:
Rho1(g, r), Rho1(g, r) -> Sigma(g)

The index paths are derived to be:
TOP
└── r
    └── g
*/
{
	const int g_len = Rho1.dimensions()[0];
	assert( g_len == Rho1.dimensions()[0] );
	assert( g_len == Sigma.dimensions()[0] );
	const int r_len = Rho1.dimensions()[1];
	assert( r_len == Rho1.dimensions()[1] );
	for ( int r = 0; r < r_len; r++ ){
		double* Sigma_ = &Sigma(0);
		const double* Rho1_r = &Rho1(0, r);
		#pragma omp simd simdlen(8) aligned(Sigma_, Rho1_r: 64)
		for ( int g = 0; g < g_len; g++ ){
			Sigma_[g] += Rho1_r[g] * Rho1_r[g];
		}
	}
}
