/*
Generated by EigenEinSum

Recommended filename:
Rho1_g,r...Rho1Grada_g,r,t---SigmaGrada_g,t.hpp

Einsum expression:
Rho1(g, r), Rho1Grada(g, r, t) -> SigmaGrada(g, t)

The einsum expression is decomposed into:
Rho1(g, r), Rho1Grada(g, r, t) -> SigmaGrada(g, t)

The index paths are derived to be:
TOP
└── t
    └── r
        └── g
*/
{
	[[maybe_unused]] const int g_len = Rho1.dimension(0);
	assert( g_len == Rho1Grada.dimension(0) );
	assert( g_len == SigmaGrada.dimension(0) );
	[[maybe_unused]] const int t_len = Rho1Grada.dimension(2);
	assert( t_len == SigmaGrada.dimension(1) );
	[[maybe_unused]] const int r_len = Rho1.dimension(1);
	assert( r_len == Rho1Grada.dimension(1) );
	for ( int t = 0; t < t_len; t++ ){
		for ( int r = 0; r < r_len; r++ ){
			double* SigmaGrada_t = &SigmaGrada(0, t);
			const double* Rho1_r = &Rho1(0, r);
			const double* Rho1Grada_rt = &Rho1Grada(0, r, t);
			#pragma omp simd simdlen(8) aligned(SigmaGrada_t, Rho1_r, Rho1Grada_rt: 64)
			for ( int g = 0; g < g_len; g++ ){
				SigmaGrada_t[g] += Rho1_r[g] * Rho1Grada_rt[g];
			}
		}
	}
}
