/*
Generated by EigenEinSum

Recommended filename:
Rho1s_g,r...Rho1Gradsa_g,r,t---SigmaGradsa_g,t.hpp

Einsum expression:
Rho1s(g, r), Rho1Gradsa(g, r, t) -> SigmaGradsa(g, t)

The einsum expression is decomposed into:
Rho1s(g, r), Rho1Gradsa(g, r, t) -> SigmaGradsa(g, t)

The index paths are derived to be:
TOP
└── r
    └── t
        └── g
*/
{
	[[maybe_unused]] const int g_len = Rho1s.dimension(0);
	assert( g_len == Rho1Gradsa.dimension(0) );
	assert( g_len == SigmaGradsa.dimension(0) );
	[[maybe_unused]] const int t_len = Rho1Gradsa.dimension(2);
	assert( t_len == SigmaGradsa.dimension(1) );
	[[maybe_unused]] const int r_len = Rho1s.dimension(1);
	assert( r_len == Rho1Gradsa.dimension(1) );
	for ( int r = 0; r < r_len; r++ ){
		for ( int t = 0; t < t_len; t++ ){
			for ( int g = 0; g < g_len; g++ ){
				SigmaGradsa(g, t) += Rho1s(g, r) * Rho1Gradsa(g, r, t);
			}
		}
	}
}
