/*
Generated by EigenEinSum

Recommended filename:
Rho1_g,r,u...Rho1Grada_g,r,t,v---SigmaGradaFull_g,t,u,v.hpp

Einsum expression:
Rho1(g, r, u), Rho1Grada(g, r, t, v) -> SigmaGradaFull(g, t, u, v)

The einsum expression is decomposed into:
Rho1(g, r, u), Rho1Grada(g, r, t, v) -> SigmaGradaFull(g, t, u, v)

The index paths are derived to be:
TOP
└── v
    └── u
        └── t
            └── r
                └── g
*/
{
	[[maybe_unused]] const int g_len = Rho1.dimension(0);
	assert( g_len == Rho1Grada.dimension(0) );
	assert( g_len == SigmaGradaFull.dimension(0) );
	[[maybe_unused]] const int t_len = Rho1Grada.dimension(2);
	assert( t_len == SigmaGradaFull.dimension(1) );
	[[maybe_unused]] const int u_len = Rho1.dimension(2);
	assert( u_len == SigmaGradaFull.dimension(2) );
	[[maybe_unused]] const int v_len = Rho1Grada.dimension(3);
	assert( v_len == SigmaGradaFull.dimension(3) );
	[[maybe_unused]] const int r_len = Rho1.dimension(1);
	assert( r_len == Rho1Grada.dimension(1) );
	for ( int v = 0; v < v_len; v++ ){
		for ( int u = 0; u < u_len; u++ ){
			for ( int t = 0; t < t_len; t++ ){
				for ( int r = 0; r < r_len; r++ ){
					double* SigmaGradaFull_tuv = &SigmaGradaFull(0, t, u, v);
					const double* Rho1_ru = &Rho1(0, r, u);
					const double* Rho1Grada_rtv = &Rho1Grada(0, r, t, v);
					#pragma omp simd simdlen(8) aligned(SigmaGradaFull_tuv, Rho1_ru, Rho1Grada_rtv: 64)
					for ( int g = 0; g < g_len; g++ ){
						SigmaGradaFull_tuv[g] += Rho1_ru[g] * Rho1Grada_rtv[g];
					}
				}
			}
		}
	}
}
