/*
Generated by EigenEinSum

Recommended filename:
Rho1_g,r,u...Rho1_g,r,v---Sigma_g,u+v.hpp

Einsum expression:
Rho1(g, r, u), Rho1(g, r, v) -> Sigma(g, u+v)

The einsum expression is decomposed into:
Rho1(g, r, u), Rho1(g, r, v) -> Sigma(g, u+v)

The index paths are derived to be:
TOP
└── v
    └── u
        └── r
            └── g
*/
{
	[[maybe_unused]] const int g_len = Rho1.dimension(0);
	assert( g_len == Rho1.dimension(0) );
	assert( g_len == Sigma.dimension(0) );
	[[maybe_unused]] const int u_v_len = Sigma.dimension(1);
	[[maybe_unused]] const int r_len = Rho1.dimension(1);
	assert( r_len == Rho1.dimension(1) );
	[[maybe_unused]] const int u_len = Rho1.dimension(2);
	[[maybe_unused]] const int v_len = Rho1.dimension(2);
	for ( int v = 0; v < v_len; v++ ){
		for ( int u = 0; u < u_len; u++ ){
			if ( !(u <= v) ) continue;
			int index_array_u_v[] = {u, v}; std::sort(index_array_u_v, index_array_u_v + 2); [[maybe_unused]] const int u_v = ( index_array_u_v[0] + 0 ) / 1 + ( index_array_u_v[1] + 0 ) * ( index_array_u_v[1] + 1 ) / 2;
			for ( int r = 0; r < r_len; r++ ){
				double* Sigma_u_v = &Sigma(0, u_v);
				const double* Rho1_ru = &Rho1(0, r, u);
				const double* Rho1_rv = &Rho1(0, r, v);
				#pragma omp simd simdlen(8) aligned(Sigma_u_v, Rho1_ru, Rho1_rv: 64)
				for ( int g = 0; g < g_len; g++ ){
					Sigma_u_v[g] += Rho1_ru[g] * Rho1_rv[g];
				}
			}
		}
	}
}
