/*
Generated by EigenEinSum

Recommended filename:
Rho1Us_g,r...Rho1s_g,r---SigmaUs_g.hpp

Einsum expression:
Rho1Us(g, r), Rho1s(g, r) -> SigmaUs(g)

The einsum expression is decomposed into:
Rho1Us(g, r), Rho1s(g, r) -> SigmaUs(g)

The index paths are derived to be:
TOP
└── r
    └── g
*/
{
	[[maybe_unused]] const int g_len = Rho1Us.dimension(0);
	assert( g_len == Rho1s.dimension(0) );
	assert( g_len == SigmaUs.dimension(0) );
	[[maybe_unused]] const int r_len = Rho1Us.dimension(1);
	assert( r_len == Rho1s.dimension(1) );
	for ( int r = 0; r < r_len; r++ ){
		for ( int g = 0; g < g_len; g++ ){
			SigmaUs(g) += Rho1Us(g, r) * Rho1s(g, r);
		}
	}
}
