/*
Generated by EigenEinSum

Recommended filename:
Rho1Hess_g,r,t,a,s,b,u...Rho1_g,r,v---SigmaHess_g,t,a,s,b,u+v.hpp

Einsum expression:
Rho1Hess(g, r, t, a, s, b, u), Rho1(g, r, v) -> SigmaHess(g, t, a, s, b, u+v)

The einsum expression is decomposed into:
Rho1Hess(g, r, t, a, s, b, u), Rho1(g, r, v) -> SigmaHess(g, t, a, s, b, u+v)

The index paths are derived to be:
TOP
└── v
    └── u
        └── b
            └── s
                └── a
                    └── t
                        └── r
                            └── g
*/
{
	[[maybe_unused]] const int g_len = Rho1Hess.dimension(0);
	assert( g_len == Rho1.dimension(0) );
	assert( g_len == SigmaHess.dimension(0) );
	[[maybe_unused]] const int t_len = Rho1Hess.dimension(2);
	assert( t_len == SigmaHess.dimension(1) );
	[[maybe_unused]] const int a_len = Rho1Hess.dimension(3);
	assert( a_len == SigmaHess.dimension(2) );
	[[maybe_unused]] const int s_len = Rho1Hess.dimension(4);
	assert( s_len == SigmaHess.dimension(3) );
	[[maybe_unused]] const int b_len = Rho1Hess.dimension(5);
	assert( b_len == SigmaHess.dimension(4) );
	[[maybe_unused]] const int u_v_len = SigmaHess.dimension(5);
	[[maybe_unused]] const int r_len = Rho1Hess.dimension(1);
	assert( r_len == Rho1.dimension(1) );
	[[maybe_unused]] const int u_len = Rho1Hess.dimension(6);
	[[maybe_unused]] const int v_len = Rho1.dimension(2);
	for ( int v = 0; v < v_len; v++ ){
		for ( int u = 0; u < u_len; u++ ){
			if ( !(u <= v) ) continue;
			int index_array_u_v[] = {u, v}; std::sort(index_array_u_v, index_array_u_v + 2); [[maybe_unused]] const int u_v = ( index_array_u_v[0] + 0 ) / 1 + ( index_array_u_v[1] + 0 ) * ( index_array_u_v[1] + 1 ) / 2;
			for ( int b = 0; b < b_len; b++ ){
				for ( int s = 0; s < s_len; s++ ){
					for ( int a = 0; a < a_len; a++ ){
						for ( int t = 0; t < t_len; t++ ){
							for ( int r = 0; r < r_len; r++ ){
								double* SigmaHess_tasbu_v = &SigmaHess(0, t, a, s, b, u_v);
								const double* Rho1Hess_rtasbu = &Rho1Hess(0, r, t, a, s, b, u);
								const double* Rho1_rv = &Rho1(0, r, v);
								#pragma omp simd simdlen(8) aligned(SigmaHess_tasbu_v, Rho1Hess_rtasbu, Rho1_rv: 64)
								for ( int g = 0; g < g_len; g++ ){
									SigmaHess_tasbu_v[g] += Rho1Hess_rtasbu[g] * Rho1_rv[g];
								}
							}
						}
					}
				}
			}
		}
	}
}
