/*
Generated by EigenEinSum

Recommended filename:
SigmaGradaFull_g,t,u,v...One_u+v---SigmaGrada_g,t,u+v.hpp

Einsum expression:
SigmaGradaFull(g, t, u, v), One(u+v) -> SigmaGrada(g, t, u+v)

The einsum expression is decomposed into:
SigmaGradaFull(g, t, u, v), One(u+v) -> SigmaGrada(g, t, u+v)

The index paths are derived to be:
TOP
└── v
    └── u
        └── t
            └── g
*/
{
	[[maybe_unused]] const int g_len = SigmaGradaFull.dimension(0);
	assert( g_len == SigmaGrada.dimension(0) );
	[[maybe_unused]] const int t_len = SigmaGradaFull.dimension(1);
	assert( t_len == SigmaGrada.dimension(1) );
	[[maybe_unused]] const int u_v_len = One.dimension(0);
	assert( u_v_len == SigmaGrada.dimension(2) );
	[[maybe_unused]] const int u_len = SigmaGradaFull.dimension(2);
	[[maybe_unused]] const int v_len = SigmaGradaFull.dimension(3);
	for ( int v = 0; v < v_len; v++ ){
		for ( int u = 0; u < u_len; u++ ){
			int index_array_u_v[] = {u, v}; std::sort(index_array_u_v, index_array_u_v + 2); [[maybe_unused]] const int u_v = ( index_array_u_v[0] + 0 ) / 1 + ( index_array_u_v[1] + 0 ) * ( index_array_u_v[1] + 1 ) / 2;
			if ( !(u <= v) ) continue;
			for ( int t = 0; t < t_len; t++ ){
				double* SigmaGrada_tu_v = &SigmaGrada(0, t, u_v);
				const double* SigmaGradaFull_tuv = &SigmaGradaFull(0, t, u, v);
				#pragma omp simd simdlen(8) aligned(SigmaGrada_tu_v, SigmaGradaFull_tuv: 64)
				for ( int g = 0; g < g_len; g++ ){
					SigmaGrada_tu_v[g] += SigmaGradaFull_tuv[g] * One(u_v);
				}
			}
		}
	}
}
