/*
Generated by EigenEinSum

Recommended filename:
W_g...Rho_g,w---n_.hpp

Einsum expression:
W(g), Rho(g, w) -> n()

The einsum expression is decomposed into:
W(g), Rho(g, w) -> n()

The index paths are derived to be:
TOP
└── w
    └── g
*/
{
	[[maybe_unused]] const int g_len = W.dimension(0);
	assert( g_len == Rho.dimension(0) );
	[[maybe_unused]] const int w_len = Rho.dimension(1);
	for ( int w = 0; w < w_len; w++ ){
		double _n = 0;
		const double* W_ = &W(0);
		const double* Rho_w = &Rho(0, w);
		#pragma omp simd simdlen(8) reduction(+: _n) aligned(W_, Rho_w: 64)
		for ( int g = 0; g < g_len; g++ ){
			_n += W_[g] * Rho_w[g];
		}
		n() += _n;
	}
}
