Flags = $(GeneralFlags) $(EIGEN3Flags)

.PHONY: all

all: DIIS Mouse Ox Tiger Loong

DIIS: DIIS.cpp
	$(CXX) -o ../../obj/DIIS.o DIIS.cpp -c $(Flags)

Mouse: Mouse.cpp
	$(CXX) -o ../../obj/Mouse.o Mouse.cpp -c $(Flags)

Ox: Ox.cpp
	$(CXX) -o ../../obj/Ox.o Ox.cpp -c $(Flags)

Tiger: Tiger.cpp
	$(CXX) -o ../../obj/Tiger.o Tiger.cpp -c $(Flags)

Rabbit: Rabbit.cpp
	$(CXX) -o ../../obj/Rabbit.o Rabbit.cpp -c $(Flags)

Loong: Loong.cpp
	$(CXX) -o ../../obj/Loong.o Loong.cpp -c $(Flags)
