/*
Generated by EigenEinSum

Recommended filename:
E1Sigma_g...Rho1G_g,r,mat---TMP3_g,r,mat.hpp

Einsum expression:
E1Sigma(g), Rho1G(g, r, mat) -> TMP3(g, r, mat)

The einsum expression is decomposed into:
E1Sigma(g), Rho1G(g, r, mat) -> TMP3(g, r, mat)

The index paths are derived to be:
TOP
└── mat
    └── r
        └── g
*/
{
	[[maybe_unused]] const int g_len = E1Sigma.dimension(0);
	assert( g_len == Rho1G.dimension(0) );
	assert( g_len == TMP3.dimension(0) );
	[[maybe_unused]] const int r_len = Rho1G.dimension(1);
	assert( r_len == TMP3.dimension(1) );
	[[maybe_unused]] const int mat_len = Rho1G.dimension(2);
	assert( mat_len == TMP3.dimension(2) );
	for ( int mat = 0; mat < mat_len; mat++ ){
		for ( int r = 0; r < r_len; r++ ){
			double* TMP3_rmat = &TMP3(0, r, mat);
			const double* E1Sigma_ = &E1Sigma(0);
			const double* Rho1G_rmat = &Rho1G(0, r, mat);
			#pragma omp simd simdlen(8) aligned(TMP3_rmat, E1Sigma_, Rho1G_rmat: 64)
			for ( int g = 0; g < g_len; g++ ){
				TMP3_rmat[g] += E1Sigma_[g] * Rho1G_rmat[g];
			}
		}
	}
}
