/*
Generated by EigenEinSum

Recommended filename:
E1Sigmas_g...Rho1Grad_g,r---TMP3_g,r.hpp

Einsum expression:
E1Sigmas(g), Rho1Grad(g, r) -> TMP3(g, r)

The einsum expression is decomposed into:
E1Sigmas(g), Rho1Grad(g, r) -> TMP3(g, r)

The index paths are derived to be:
TOP
└── r
    └── g
*/
{
	[[maybe_unused]] const int g_len = E1Sigmas.dimension(0);
	assert( g_len == Rho1Grad.dimension(0) );
	assert( g_len == TMP3.dimension(0) );
	[[maybe_unused]] const int r_len = Rho1Grad.dimension(1);
	assert( r_len == TMP3.dimension(1) );
	for ( int r = 0; r < r_len; r++ ){
		for ( int g = 0; g < g_len; g++ ){
			TMP3(g, r) += E1Sigmas(g) * Rho1Grad(g, r);
		}
	}
}
