/*
Generated by EigenEinSum

Recommended filename:
E2Rho2_g...RhoG_g,mat---TMP0_g,mat.hpp

Einsum expression:
E2Rho2(g), RhoG(g, mat) -> TMP0(g, mat)

The einsum expression is decomposed into:
E2Rho2(g), RhoG(g, mat) -> TMP0(g, mat)

The index paths are derived to be:
TOP
└── mat
    └── g
*/
{
	[[maybe_unused]] const int g_len = E2Rho2.dimension(0);
	assert( g_len == RhoG.dimension(0) );
	assert( g_len == TMP0.dimension(0) );
	[[maybe_unused]] const int mat_len = RhoG.dimension(1);
	assert( mat_len == TMP0.dimension(1) );
	for ( int mat = 0; mat < mat_len; mat++ ){
		double* TMP0_mat = &TMP0(0, mat);
		const double* E2Rho2_ = &E2Rho2(0);
		const double* RhoG_mat = &RhoG(0, mat);
		#pragma omp simd simdlen(8) aligned(TMP0_mat, E2Rho2_, RhoG_mat: 64)
		for ( int g = 0; g < g_len; g++ ){
			TMP0_mat[g] += E2Rho2_[g] * RhoG_mat[g];
		}
	}
}
