/*
Generated by EigenEinSum

Recommended filename:
E2RhoSigmas_g...RhoGrads_g,t,a---TMP_g,t,a.hpp

Einsum expression:
E2RhoSigmas(g), RhoGrads(g, t, a) -> TMP(g, t, a)

The einsum expression is decomposed into:
E2RhoSigmas(g), RhoGrads(g, t, a) -> TMP(g, t, a)

The index paths are derived to be:
TOP
└── a
    └── t
        └── g
*/
{
	[[maybe_unused]] const int g_len = E2RhoSigmas.dimension(0);
	assert( g_len == RhoGrads.dimension(0) );
	assert( g_len == TMP.dimension(0) );
	[[maybe_unused]] const int t_len = RhoGrads.dimension(1);
	assert( t_len == TMP.dimension(1) );
	[[maybe_unused]] const int a_len = RhoGrads.dimension(2);
	assert( a_len == TMP.dimension(2) );
	for ( int a = 0; a < a_len; a++ ){
		for ( int t = 0; t < t_len; t++ ){
			for ( int g = 0; g < g_len; g++ ){
				TMP(g, t, a) += E2RhoSigmas(g) * RhoGrads(g, t, a);
			}
		}
	}
}
