/*
Generated by EigenEinSum

Recommended filename:
E2RhoSigma_g...RhoG_g,mat---TMP1_g,mat.hpp

Einsum expression:
E2RhoSigma(g), RhoG(g, mat) -> TMP1(g, mat)

The einsum expression is decomposed into:
E2RhoSigma(g), RhoG(g, mat) -> TMP1(g, mat)

The index paths are derived to be:
TOP
└── mat
    └── g
*/
{
	[[maybe_unused]] const int g_len = E2RhoSigma.dimension(0);
	assert( g_len == RhoG.dimension(0) );
	assert( g_len == TMP1.dimension(0) );
	[[maybe_unused]] const int mat_len = RhoG.dimension(1);
	assert( mat_len == TMP1.dimension(1) );
	for ( int mat = 0; mat < mat_len; mat++ ){
		double* TMP1_mat = &TMP1(0, mat);
		const double* E2RhoSigma_ = &E2RhoSigma(0);
		const double* RhoG_mat = &RhoG(0, mat);
		#pragma omp simd simdlen(8) aligned(TMP1_mat, E2RhoSigma_, RhoG_mat: 64)
		for ( int g = 0; g < g_len; g++ ){
			TMP1_mat[g] += E2RhoSigma_[g] * RhoG_mat[g];
		}
	}
}
