/*
Generated by EigenEinSum

Recommended filename:
E2RhoSigma_g...SigmaG_g,mat---TMP0_mat.hpp

Einsum expression:
E2RhoSigma(g), SigmaG(g, mat) -> TMP0(mat)

The einsum expression is decomposed into:
E2RhoSigma(g), SigmaG(g, mat) -> TMP0(mat)

The index paths are derived to be:
TOP
└── mat
    └── g
*/
{
	[[maybe_unused]] const int mat_len = SigmaG.dimension(1);
	assert( mat_len == TMP0.dimension(0) );
	[[maybe_unused]] const int g_len = E2RhoSigma.dimension(0);
	assert( g_len == SigmaG.dimension(0) );
	for ( int mat = 0; mat < mat_len; mat++ ){
		double TMP0mat = 0;
		const double* E2RhoSigma_ = &E2RhoSigma(0);
		const double* SigmaG_mat = &SigmaG(0, mat);
		#pragma omp simd simdlen(8) reduction(+: TMP0mat) aligned(E2RhoSigma_, SigmaG_mat: 64)
		for ( int g = 0; g < g_len; g++ ){
			TMP0mat += E2RhoSigma_[g] * SigmaG_mat[g];
		}
		TMP0(mat) += TMP0mat;
	}
}
