/*
Generated by EigenEinSum

Recommended filename:
E2Sigma2s_g...SigmaGrads_g,t,a---TMP_g,t,a.hpp

Einsum expression:
E2Sigma2s(g), SigmaGrads(g, t, a) -> TMP(g, t, a)

The einsum expression is decomposed into:
E2Sigma2s(g), SigmaGrads(g, t, a) -> TMP(g, t, a)

The index paths are derived to be:
TOP
└── a
    └── t
        └── g
*/
{
	[[maybe_unused]] const int g_len = E2Sigma2s.dimension(0);
	assert( g_len == SigmaGrads.dimension(0) );
	assert( g_len == TMP.dimension(0) );
	[[maybe_unused]] const int t_len = SigmaGrads.dimension(1);
	assert( t_len == TMP.dimension(1) );
	[[maybe_unused]] const int a_len = SigmaGrads.dimension(2);
	assert( a_len == TMP.dimension(2) );
	for ( int a = 0; a < a_len; a++ ){
		for ( int t = 0; t < t_len; t++ ){
			for ( int g = 0; g < g_len; g++ ){
				TMP(g, t, a) += E2Sigma2s(g) * SigmaGrads(g, t, a);
			}
		}
	}
}
