/*
Generated by EigenEinSum

Recommended filename:
E2Sigma2_g...SigmaG_g,mat---TMP1_g,mat.hpp

Einsum expression:
E2Sigma2(g), SigmaG(g, mat) -> TMP1(g, mat)

The einsum expression is decomposed into:
E2Sigma2(g), SigmaG(g, mat) -> TMP1(g, mat)

The index paths are derived to be:
TOP
└── mat
    └── g
*/
{
	[[maybe_unused]] const int g_len = E2Sigma2.dimension(0);
	assert( g_len == SigmaG.dimension(0) );
	assert( g_len == TMP1.dimension(0) );
	[[maybe_unused]] const int mat_len = SigmaG.dimension(1);
	assert( mat_len == TMP1.dimension(1) );
	for ( int mat = 0; mat < mat_len; mat++ ){
		double* TMP1_mat = &TMP1(0, mat);
		const double* E2Sigma2_ = &E2Sigma2(0);
		const double* SigmaG_mat = &SigmaG(0, mat);
		#pragma omp simd simdlen(8) aligned(TMP1_mat, E2Sigma2_, SigmaG_mat: 64)
		for ( int g = 0; g < g_len; g++ ){
			TMP1_mat[g] += E2Sigma2_[g] * SigmaG_mat[g];
		}
	}
}
