/*
Generated by EigenEinSum

Recommended filename:
Eps2Tau2_g,u,v...TauG_g,mat,u---TMP6_g,mat,v.hpp

Einsum expression:
Eps2Tau2(g, u, v), TauG(g, mat, u) -> TMP6(g, mat, v)

The einsum expression is decomposed into:
Eps2Tau2(g, u, v), TauG(g, mat, u) -> TMP6(g, mat, v)

The index paths are derived to be:
TOP
└── v
    └── u
        └── mat
            └── g
*/
{
	[[maybe_unused]] const int g_len = Eps2Tau2.dimension(0);
	assert( g_len == TauG.dimension(0) );
	assert( g_len == TMP6.dimension(0) );
	[[maybe_unused]] const int mat_len = TauG.dimension(1);
	assert( mat_len == TMP6.dimension(1) );
	[[maybe_unused]] const int v_len = Eps2Tau2.dimension(2);
	assert( v_len == TMP6.dimension(2) );
	[[maybe_unused]] const int u_len = Eps2Tau2.dimension(1);
	assert( u_len == TauG.dimension(2) );
	for ( int v = 0; v < v_len; v++ ){
		for ( int u = 0; u < u_len; u++ ){
			for ( int mat = 0; mat < mat_len; mat++ ){
				double* TMP6_matv = &TMP6(0, mat, v);
				const double* Eps2Tau2_uv = &Eps2Tau2(0, u, v);
				const double* TauG_matu = &TauG(0, mat, u);
				#pragma omp simd simdlen(8) aligned(TMP6_matv, Eps2Tau2_uv, TauG_matu: 64)
				for ( int g = 0; g < g_len; g++ ){
					TMP6_matv[g] += Eps2Tau2_uv[g] * TauG_matu[g];
				}
			}
		}
	}
}
