/*
Generated by EigenEinSum

Recommended filename:
Eps2RhoTau_g,u,v...TauG_g,mat,v---TMP0_g,mat,u.hpp

Einsum expression:
Eps2RhoTau(g, u, v), TauG(g, mat, v) -> TMP0(g, mat, u)

The einsum expression is decomposed into:
Eps2RhoTau(g, u, v), TauG(g, mat, v) -> TMP0(g, mat, u)

The index paths are derived to be:
TOP
└── v
    └── u
        └── mat
            └── g
*/
{
	[[maybe_unused]] const int g_len = Eps2RhoTau.dimension(0);
	assert( g_len == TauG.dimension(0) );
	assert( g_len == TMP0.dimension(0) );
	[[maybe_unused]] const int mat_len = TauG.dimension(1);
	assert( mat_len == TMP0.dimension(1) );
	[[maybe_unused]] const int u_len = Eps2RhoTau.dimension(1);
	assert( u_len == TMP0.dimension(2) );
	[[maybe_unused]] const int v_len = Eps2RhoTau.dimension(2);
	assert( v_len == TauG.dimension(2) );
	for ( int v = 0; v < v_len; v++ ){
		for ( int u = 0; u < u_len; u++ ){
			for ( int mat = 0; mat < mat_len; mat++ ){
				double* TMP0_matu = &TMP0(0, mat, u);
				const double* Eps2RhoTau_uv = &Eps2RhoTau(0, u, v);
				const double* TauG_matv = &TauG(0, mat, v);
				#pragma omp simd simdlen(8) aligned(TMP0_matu, Eps2RhoTau_uv, TauG_matv: 64)
				for ( int g = 0; g < g_len; g++ ){
					TMP0_matu[g] += Eps2RhoTau_uv[g] * TauG_matv[g];
				}
			}
		}
	}
}
