/*
Generated by EigenEinSum

Recommended filename:
Eps2SigmaTau_g,uv,w...SigmaG_g,mat,uv---TMP6_g,mat,w.hpp

Einsum expression:
Eps2SigmaTau(g, uv, w), SigmaG(g, mat, uv) -> TMP6(g, mat, w)

The einsum expression is decomposed into:
Eps2SigmaTau(g, uv, w), SigmaG(g, mat, uv) -> TMP6(g, mat, w)

The index paths are derived to be:
TOP
└── w
    └── uv
        └── mat
            └── g
*/
{
	[[maybe_unused]] const int g_len = Eps2SigmaTau.dimension(0);
	assert( g_len == SigmaG.dimension(0) );
	assert( g_len == TMP6.dimension(0) );
	[[maybe_unused]] const int mat_len = SigmaG.dimension(1);
	assert( mat_len == TMP6.dimension(1) );
	[[maybe_unused]] const int w_len = Eps2SigmaTau.dimension(2);
	assert( w_len == TMP6.dimension(2) );
	[[maybe_unused]] const int uv_len = Eps2SigmaTau.dimension(1);
	assert( uv_len == SigmaG.dimension(2) );
	for ( int w = 0; w < w_len; w++ ){
		for ( int uv = 0; uv < uv_len; uv++ ){
			for ( int mat = 0; mat < mat_len; mat++ ){
				double* TMP6_matw = &TMP6(0, mat, w);
				const double* Eps2SigmaTau_uvw = &Eps2SigmaTau(0, uv, w);
				const double* SigmaG_matuv = &SigmaG(0, mat, uv);
				#pragma omp simd simdlen(8) aligned(TMP6_matw, Eps2SigmaTau_uvw, SigmaG_matuv: 64)
				for ( int g = 0; g < g_len; g++ ){
					TMP6_matw[g] += Eps2SigmaTau_uvw[g] * SigmaG_matuv[g];
				}
			}
		}
	}
}
