/*
Generated by EigenEinSum

Recommended filename:
Eps2RhoLapl_g,u,v...LaplG_g,mat,v---TMP0_g,mat,u.hpp

Einsum expression:
Eps2RhoLapl(g, u, v), LaplG(g, mat, v) -> TMP0(g, mat, u)

The einsum expression is decomposed into:
Eps2RhoLapl(g, u, v), LaplG(g, mat, v) -> TMP0(g, mat, u)

The index paths are derived to be:
TOP
└── v
    └── u
        └── mat
            └── g
*/
{
	[[maybe_unused]] const int g_len = Eps2RhoLapl.dimension(0);
	assert( g_len == LaplG.dimension(0) );
	assert( g_len == TMP0.dimension(0) );
	[[maybe_unused]] const int mat_len = LaplG.dimension(1);
	assert( mat_len == TMP0.dimension(1) );
	[[maybe_unused]] const int u_len = Eps2RhoLapl.dimension(1);
	assert( u_len == TMP0.dimension(2) );
	[[maybe_unused]] const int v_len = Eps2RhoLapl.dimension(2);
	assert( v_len == LaplG.dimension(2) );
	for ( int v = 0; v < v_len; v++ ){
		for ( int u = 0; u < u_len; u++ ){
			for ( int mat = 0; mat < mat_len; mat++ ){
				double* TMP0_matu = &TMP0(0, mat, u);
				const double* Eps2RhoLapl_uv = &Eps2RhoLapl(0, u, v);
				const double* LaplG_matv = &LaplG(0, mat, v);
				#pragma omp simd simdlen(8) aligned(TMP0_matu, Eps2RhoLapl_uv, LaplG_matv: 64)
				for ( int g = 0; g < g_len; g++ ){
					TMP0_matu[g] += Eps2RhoLapl_uv[g] * LaplG_matv[g];
				}
			}
		}
	}
}
