/*
Generated by EigenEinSum

Recommended filename:
Eps2RhoSigma_g,w,uv...SigmaG_g,mat,uv---TMP0_g,mat,w.hpp

Einsum expression:
Eps2RhoSigma(g, w, uv), SigmaG(g, mat, uv) -> TMP0(g, mat, w)

The einsum expression is decomposed into:
Eps2RhoSigma(g, w, uv), SigmaG(g, mat, uv) -> TMP0(g, mat, w)

The index paths are derived to be:
TOP
└── uv
    └── w
        └── mat
            └── g
*/
{
	[[maybe_unused]] const int g_len = Eps2RhoSigma.dimension(0);
	assert( g_len == SigmaG.dimension(0) );
	assert( g_len == TMP0.dimension(0) );
	[[maybe_unused]] const int mat_len = SigmaG.dimension(1);
	assert( mat_len == TMP0.dimension(1) );
	[[maybe_unused]] const int w_len = Eps2RhoSigma.dimension(1);
	assert( w_len == TMP0.dimension(2) );
	[[maybe_unused]] const int uv_len = Eps2RhoSigma.dimension(2);
	assert( uv_len == SigmaG.dimension(2) );
	for ( int uv = 0; uv < uv_len; uv++ ){
		for ( int w = 0; w < w_len; w++ ){
			for ( int mat = 0; mat < mat_len; mat++ ){
				double* TMP0_matw = &TMP0(0, mat, w);
				const double* Eps2RhoSigma_wuv = &Eps2RhoSigma(0, w, uv);
				const double* SigmaG_matuv = &SigmaG(0, mat, uv);
				#pragma omp simd simdlen(8) aligned(TMP0_matw, Eps2RhoSigma_wuv, SigmaG_matuv: 64)
				for ( int g = 0; g < g_len; g++ ){
					TMP0_matw[g] += Eps2RhoSigma_wuv[g] * SigmaG_matuv[g];
				}
			}
		}
	}
}
