/*
Generated by EigenEinSum

Recommended filename:
Eps2Sigma2_g,u,v...SigmaG_g,mat,v---TMP1_g,mat,u.hpp

Einsum expression:
Eps2Sigma2(g, u, v), SigmaG(g, mat, v) -> TMP1(g, mat, u)

The einsum expression is decomposed into:
Eps2Sigma2(g, u, v), SigmaG(g, mat, v) -> TMP1(g, mat, u)

The index paths are derived to be:
TOP
└── v
    └── u
        └── mat
            └── g
*/
{
	[[maybe_unused]] const int g_len = Eps2Sigma2.dimension(0);
	assert( g_len == SigmaG.dimension(0) );
	assert( g_len == TMP1.dimension(0) );
	[[maybe_unused]] const int mat_len = SigmaG.dimension(1);
	assert( mat_len == TMP1.dimension(1) );
	[[maybe_unused]] const int u_len = Eps2Sigma2.dimension(1);
	assert( u_len == TMP1.dimension(2) );
	[[maybe_unused]] const int v_len = Eps2Sigma2.dimension(2);
	assert( v_len == SigmaG.dimension(2) );
	for ( int v = 0; v < v_len; v++ ){
		for ( int u = 0; u < u_len; u++ ){
			for ( int mat = 0; mat < mat_len; mat++ ){
				double* TMP1_matu = &TMP1(0, mat, u);
				const double* Eps2Sigma2_uv = &Eps2Sigma2(0, u, v);
				const double* SigmaG_matv = &SigmaG(0, mat, v);
				#pragma omp simd simdlen(8) aligned(TMP1_matu, Eps2Sigma2_uv, SigmaG_matv: 64)
				for ( int g = 0; g < g_len; g++ ){
					TMP1_matu[g] += Eps2Sigma2_uv[g] * SigmaG_matv[g];
				}
			}
		}
	}
}
