/*
Generated by EigenEinSum

Recommended filename:
Eps2Lapl2_g,u,v...LaplG_g,mat,u---TMP5_g,mat,v.hpp

Einsum expression:
Eps2Lapl2(g, u, v), LaplG(g, mat, u) -> TMP5(g, mat, v)

The einsum expression is decomposed into:
Eps2Lapl2(g, u, v), LaplG(g, mat, u) -> TMP5(g, mat, v)

The index paths are derived to be:
TOP
└── v
    └── u
        └── mat
            └── g
*/
{
	[[maybe_unused]] const int g_len = Eps2Lapl2.dimension(0);
	assert( g_len == LaplG.dimension(0) );
	assert( g_len == TMP5.dimension(0) );
	[[maybe_unused]] const int mat_len = LaplG.dimension(1);
	assert( mat_len == TMP5.dimension(1) );
	[[maybe_unused]] const int v_len = Eps2Lapl2.dimension(2);
	assert( v_len == TMP5.dimension(2) );
	[[maybe_unused]] const int u_len = Eps2Lapl2.dimension(1);
	assert( u_len == LaplG.dimension(2) );
	for ( int v = 0; v < v_len; v++ ){
		for ( int u = 0; u < u_len; u++ ){
			for ( int mat = 0; mat < mat_len; mat++ ){
				double* TMP5_matv = &TMP5(0, mat, v);
				const double* Eps2Lapl2_uv = &Eps2Lapl2(0, u, v);
				const double* LaplG_matu = &LaplG(0, mat, u);
				#pragma omp simd simdlen(8) aligned(TMP5_matv, Eps2Lapl2_uv, LaplG_matu: 64)
				for ( int g = 0; g < g_len; g++ ){
					TMP5_matv[g] += Eps2Lapl2_uv[g] * LaplG_matu[g];
				}
			}
		}
	}
}
