/*
Generated by EigenEinSum

Recommended filename:
Eps2RhoLapl_g,u,v...RhoG_g,mat,u---TMP5_g,mat,v.hpp

Einsum expression:
Eps2RhoLapl(g, u, v), RhoG(g, mat, u) -> TMP5(g, mat, v)

The einsum expression is decomposed into:
Eps2RhoLapl(g, u, v), RhoG(g, mat, u) -> TMP5(g, mat, v)

The index paths are derived to be:
TOP
└── v
    └── u
        └── mat
            └── g
*/
{
	[[maybe_unused]] const int g_len = Eps2RhoLapl.dimension(0);
	assert( g_len == RhoG.dimension(0) );
	assert( g_len == TMP5.dimension(0) );
	[[maybe_unused]] const int mat_len = RhoG.dimension(1);
	assert( mat_len == TMP5.dimension(1) );
	[[maybe_unused]] const int v_len = Eps2RhoLapl.dimension(2);
	assert( v_len == TMP5.dimension(2) );
	[[maybe_unused]] const int u_len = Eps2RhoLapl.dimension(1);
	assert( u_len == RhoG.dimension(2) );
	for ( int v = 0; v < v_len; v++ ){
		for ( int u = 0; u < u_len; u++ ){
			for ( int mat = 0; mat < mat_len; mat++ ){
				double* TMP5_matv = &TMP5(0, mat, v);
				const double* Eps2RhoLapl_uv = &Eps2RhoLapl(0, u, v);
				const double* RhoG_matu = &RhoG(0, mat, u);
				#pragma omp simd simdlen(8) aligned(TMP5_matv, Eps2RhoLapl_uv, RhoG_matu: 64)
				for ( int g = 0; g < g_len; g++ ){
					TMP5_matv[g] += Eps2RhoLapl_uv[g] * RhoG_matu[g];
				}
			}
		}
	}
}
