/*
Generated by EigenEinSum

Recommended filename:
Eps2SigmaLapl_g,uv,w...LaplG_g,mat,w---TMP1_g,mat,uv.hpp

Einsum expression:
Eps2SigmaLapl(g, uv, w), LaplG(g, mat, w) -> TMP1(g, mat, uv)

The einsum expression is decomposed into:
Eps2SigmaLapl(g, uv, w), LaplG(g, mat, w) -> TMP1(g, mat, uv)

The index paths are derived to be:
TOP
└── w
    └── uv
        └── mat
            └── g
*/
{
	[[maybe_unused]] const int g_len = Eps2SigmaLapl.dimension(0);
	assert( g_len == LaplG.dimension(0) );
	assert( g_len == TMP1.dimension(0) );
	[[maybe_unused]] const int mat_len = LaplG.dimension(1);
	assert( mat_len == TMP1.dimension(1) );
	[[maybe_unused]] const int uv_len = Eps2SigmaLapl.dimension(1);
	assert( uv_len == TMP1.dimension(2) );
	[[maybe_unused]] const int w_len = Eps2SigmaLapl.dimension(2);
	assert( w_len == LaplG.dimension(2) );
	for ( int w = 0; w < w_len; w++ ){
		for ( int uv = 0; uv < uv_len; uv++ ){
			for ( int mat = 0; mat < mat_len; mat++ ){
				double* TMP1_matuv = &TMP1(0, mat, uv);
				const double* Eps2SigmaLapl_uvw = &Eps2SigmaLapl(0, uv, w);
				const double* LaplG_matw = &LaplG(0, mat, w);
				#pragma omp simd simdlen(8) aligned(TMP1_matuv, Eps2SigmaLapl_uvw, LaplG_matw: 64)
				for ( int g = 0; g < g_len; g++ ){
					TMP1_matuv[g] += Eps2SigmaLapl_uvw[g] * LaplG_matw[g];
				}
			}
		}
	}
}
