/*
Generated by EigenEinSum

Recommended filename:
S_w...Eps1Sigma_g,w---ScaledEps1Sigma_g,w.hpp

Einsum expression:
S(w), Eps1Sigma(g, w) -> ScaledEps1Sigma(g, w)

The einsum expression is decomposed into:
S(w), Eps1Sigma(g, w) -> ScaledEps1Sigma(g, w)

The index paths are derived to be:
TOP
└── w
    └── g
*/
{
	[[maybe_unused]] const int g_len = Eps1Sigma.dimension(0);
	assert( g_len == ScaledEps1Sigma.dimension(0) );
	[[maybe_unused]] const int w_len = S.dimension(0);
	assert( w_len == Eps1Sigma.dimension(1) );
	assert( w_len == ScaledEps1Sigma.dimension(1) );
	for ( int w = 0; w < w_len; w++ ){
		double* ScaledEps1Sigma_w = &ScaledEps1Sigma(0, w);
		const double* Eps1Sigma_w = &Eps1Sigma(0, w);
		#pragma omp simd simdlen(8) aligned(ScaledEps1Sigma_w, Eps1Sigma_w: 64)
		for ( int g = 0; g < g_len; g++ ){
			ScaledEps1Sigma_w[g] += S(w) * Eps1Sigma_w[g];
		}
	}
}
