/*
Generated by EigenEinSum

Recommended filename:
S_x...Eps2Sigma2_g,w,x---ScaledEps2Sigma2_g,w,x.hpp

Einsum expression:
S(x), Eps2Sigma2(g, w, x) -> ScaledEps2Sigma2(g, w, x)

The einsum expression is decomposed into:
S(x), Eps2Sigma2(g, w, x) -> ScaledEps2Sigma2(g, w, x)

The index paths are derived to be:
TOP
└── x
    └── w
        └── g
*/
{
	[[maybe_unused]] const int g_len = Eps2Sigma2.dimension(0);
	assert( g_len == ScaledEps2Sigma2.dimension(0) );
	[[maybe_unused]] const int w_len = Eps2Sigma2.dimension(1);
	assert( w_len == ScaledEps2Sigma2.dimension(1) );
	[[maybe_unused]] const int x_len = S.dimension(0);
	assert( x_len == Eps2Sigma2.dimension(2) );
	assert( x_len == ScaledEps2Sigma2.dimension(2) );
	for ( int x = 0; x < x_len; x++ ){
		for ( int w = 0; w < w_len; w++ ){
			double* ScaledEps2Sigma2_wx = &ScaledEps2Sigma2(0, w, x);
			const double* Eps2Sigma2_wx = &Eps2Sigma2(0, w, x);
			#pragma omp simd simdlen(8) aligned(ScaledEps2Sigma2_wx, Eps2Sigma2_wx: 64)
			for ( int g = 0; g < g_len; g++ ){
				ScaledEps2Sigma2_wx[g] += S(x) * Eps2Sigma2_wx[g];
			}
		}
	}
}
