/*
Generated by EigenEinSum

Recommended filename:
ScaledEps1Sigma_g,u+v...Rho1G_g,r,mat,v---TMP3_g,r,mat,u.hpp

Einsum expression:
ScaledEps1Sigma(g, u+v), Rho1G(g, r, mat, v) -> TMP3(g, r, mat, u)

The einsum expression is decomposed into:
ScaledEps1Sigma(g, u+v), Rho1G(g, r, mat, v) -> TMP3(g, r, mat, u)

The index paths are derived to be:
TOP
└── v
    └── u
        └── mat
            └── r
                └── g
*/
{
	[[maybe_unused]] const int g_len = ScaledEps1Sigma.dimension(0);
	assert( g_len == Rho1G.dimension(0) );
	assert( g_len == TMP3.dimension(0) );
	[[maybe_unused]] const int r_len = Rho1G.dimension(1);
	assert( r_len == TMP3.dimension(1) );
	[[maybe_unused]] const int mat_len = Rho1G.dimension(2);
	assert( mat_len == TMP3.dimension(2) );
	[[maybe_unused]] const int u_len = TMP3.dimension(3);
	[[maybe_unused]] const int u_v_len = ScaledEps1Sigma.dimension(1);
	[[maybe_unused]] const int v_len = Rho1G.dimension(3);
	for ( int v = 0; v < v_len; v++ ){
		for ( int u = 0; u < u_len; u++ ){
			int index_array_u_v[] = {u, v}; std::sort(index_array_u_v, index_array_u_v + 2); [[maybe_unused]] const int u_v = ( index_array_u_v[0] + 0 ) / 1 + ( index_array_u_v[1] + 0 ) * ( index_array_u_v[1] + 1 ) / 2;
			for ( int mat = 0; mat < mat_len; mat++ ){
				for ( int r = 0; r < r_len; r++ ){
					double* TMP3_rmatu = &TMP3(0, r, mat, u);
					const double* ScaledEps1Sigma_u_v = &ScaledEps1Sigma(0, u_v);
					const double* Rho1G_rmatv = &Rho1G(0, r, mat, v);
					#pragma omp simd simdlen(8) aligned(TMP3_rmatu, ScaledEps1Sigma_u_v, Rho1G_rmatv: 64)
					for ( int g = 0; g < g_len; g++ ){
						TMP3_rmatu[g] += ScaledEps1Sigma_u_v[g] * Rho1G_rmatv[g];
					}
				}
			}
		}
	}
}
