/*
Generated by EigenEinSum

Recommended filename:
ScaledEps2RhoSigma_g,w,uv...RhoG_g,mat,w---TMP1_g,mat,uv.hpp

Einsum expression:
ScaledEps2RhoSigma(g, w, uv), RhoG(g, mat, w) -> TMP1(g, mat, uv)

The einsum expression is decomposed into:
ScaledEps2RhoSigma(g, w, uv), RhoG(g, mat, w) -> TMP1(g, mat, uv)

The index paths are derived to be:
TOP
└── uv
    └── w
        └── mat
            └── g
*/
{
	[[maybe_unused]] const int g_len = ScaledEps2RhoSigma.dimension(0);
	assert( g_len == RhoG.dimension(0) );
	assert( g_len == TMP1.dimension(0) );
	[[maybe_unused]] const int mat_len = RhoG.dimension(1);
	assert( mat_len == TMP1.dimension(1) );
	[[maybe_unused]] const int uv_len = ScaledEps2RhoSigma.dimension(2);
	assert( uv_len == TMP1.dimension(2) );
	[[maybe_unused]] const int w_len = ScaledEps2RhoSigma.dimension(1);
	assert( w_len == RhoG.dimension(2) );
	for ( int uv = 0; uv < uv_len; uv++ ){
		for ( int w = 0; w < w_len; w++ ){
			for ( int mat = 0; mat < mat_len; mat++ ){
				double* TMP1_matuv = &TMP1(0, mat, uv);
				const double* ScaledEps2RhoSigma_wuv = &ScaledEps2RhoSigma(0, w, uv);
				const double* RhoG_matw = &RhoG(0, mat, w);
				#pragma omp simd simdlen(8) aligned(TMP1_matuv, ScaledEps2RhoSigma_wuv, RhoG_matw: 64)
				for ( int g = 0; g < g_len; g++ ){
					TMP1_matuv[g] += ScaledEps2RhoSigma_wuv[g] * RhoG_matw[g];
				}
			}
		}
	}
}
