/*
Generated by EigenEinSum

Recommended filename:
TMP1_g,mat...Rho1_g,r---TMP2_g,r,mat.hpp

Einsum expression:
TMP1(g, mat), Rho1(g, r) -> TMP2(g, r, mat)

The einsum expression is decomposed into:
TMP1(g, mat), Rho1(g, r) -> TMP2(g, r, mat)

The index paths are derived to be:
TOP
└── mat
    └── r
        └── g
*/
{
	[[maybe_unused]] const int g_len = TMP1.dimension(0);
	assert( g_len == Rho1.dimension(0) );
	assert( g_len == TMP2.dimension(0) );
	[[maybe_unused]] const int r_len = Rho1.dimension(1);
	assert( r_len == TMP2.dimension(1) );
	[[maybe_unused]] const int mat_len = TMP1.dimension(1);
	assert( mat_len == TMP2.dimension(2) );
	for ( int mat = 0; mat < mat_len; mat++ ){
		for ( int r = 0; r < r_len; r++ ){
			double* TMP2_rmat = &TMP2(0, r, mat);
			const double* TMP1_mat = &TMP1(0, mat);
			const double* Rho1_r = &Rho1(0, r);
			#pragma omp simd simdlen(8) aligned(TMP2_rmat, TMP1_mat, Rho1_r: 64)
			for ( int g = 0; g < g_len; g++ ){
				TMP2_rmat[g] += TMP1_mat[g] * Rho1_r[g];
			}
		}
	}
}
