/*
Generated by EigenEinSum

Recommended filename:
TMP1_g,mat,u+v...Rho1_g,r,v---TMP2_g,r,mat,u.hpp

Einsum expression:
TMP1(g, mat, u+v), Rho1(g, r, v) -> TMP2(g, r, mat, u)

The einsum expression is decomposed into:
TMP1(g, mat, u+v), Rho1(g, r, v) -> TMP2(g, r, mat, u)

The index paths are derived to be:
TOP
└── v
    └── u
        └── mat
            └── r
                └── g
*/
{
	[[maybe_unused]] const int g_len = TMP1.dimension(0);
	assert( g_len == Rho1.dimension(0) );
	assert( g_len == TMP2.dimension(0) );
	[[maybe_unused]] const int r_len = Rho1.dimension(1);
	assert( r_len == TMP2.dimension(1) );
	[[maybe_unused]] const int mat_len = TMP1.dimension(1);
	assert( mat_len == TMP2.dimension(2) );
	[[maybe_unused]] const int u_len = TMP2.dimension(3);
	[[maybe_unused]] const int u_v_len = TMP1.dimension(2);
	[[maybe_unused]] const int v_len = Rho1.dimension(2);
	for ( int v = 0; v < v_len; v++ ){
		for ( int u = 0; u < u_len; u++ ){
			int index_array_u_v[] = {u, v}; std::sort(index_array_u_v, index_array_u_v + 2); [[maybe_unused]] const int u_v = ( index_array_u_v[0] + 0 ) / 1 + ( index_array_u_v[1] + 0 ) * ( index_array_u_v[1] + 1 ) / 2;
			for ( int mat = 0; mat < mat_len; mat++ ){
				for ( int r = 0; r < r_len; r++ ){
					double* TMP2_rmatu = &TMP2(0, r, mat, u);
					const double* TMP1_matu_v = &TMP1(0, mat, u_v);
					const double* Rho1_rv = &Rho1(0, r, v);
					#pragma omp simd simdlen(8) aligned(TMP2_rmatu, TMP1_matu_v, Rho1_rv: 64)
					for ( int g = 0; g < g_len; g++ ){
						TMP2_rmatu[g] += TMP1_matu_v[g] * Rho1_rv[g];
					}
				}
			}
		}
	}
}
