/*
Generated by EigenEinSum

Recommended filename:
TMP1_g...Rho1s_g,r---TMP2_g,r.hpp

Einsum expression:
TMP1(g), Rho1s(g, r) -> TMP2(g, r)

The einsum expression is decomposed into:
TMP1(g), Rho1s(g, r) -> TMP2(g, r)

The index paths are derived to be:
TOP
└── r
    └── g
*/
{
	[[maybe_unused]] const int g_len = TMP1.dimension(0);
	assert( g_len == Rho1s.dimension(0) );
	assert( g_len == TMP2.dimension(0) );
	[[maybe_unused]] const int r_len = Rho1s.dimension(1);
	assert( r_len == TMP2.dimension(1) );
	for ( int r = 0; r < r_len; r++ ){
		for ( int g = 0; g < g_len; g++ ){
			TMP2(g, r) += TMP1(g) * Rho1s(g, r);
		}
	}
}
