/*
Generated by EigenEinSum

Recommended filename:
TMP_g,t,a...Rho1s_g,r---TMP2_g,r,t,a.hpp

Einsum expression:
TMP(g, t, a), Rho1s(g, r) -> TMP2(g, r, t, a)

The einsum expression is decomposed into:
TMP(g, t, a), Rho1s(g, r) -> TMP2(g, r, t, a)

The index paths are derived to be:
TOP
└── a
    └── t
        └── r
            └── g
*/
{
	[[maybe_unused]] const int g_len = TMP.dimension(0);
	assert( g_len == Rho1s.dimension(0) );
	assert( g_len == TMP2.dimension(0) );
	[[maybe_unused]] const int r_len = Rho1s.dimension(1);
	assert( r_len == TMP2.dimension(1) );
	[[maybe_unused]] const int t_len = TMP.dimension(1);
	assert( t_len == TMP2.dimension(2) );
	[[maybe_unused]] const int a_len = TMP.dimension(2);
	assert( a_len == TMP2.dimension(3) );
	for ( int a = 0; a < a_len; a++ ){
		for ( int t = 0; t < t_len; t++ ){
			for ( int r = 0; r < r_len; r++ ){
				for ( int g = 0; g < g_len; g++ ){
					TMP2(g, r, t, a) += TMP(g, t, a) * Rho1s(g, r);
				}
			}
		}
	}
}
