/*
Generated by EigenEinSum

Recommended filename:
W_g...TMP0_g,mat,w---TMP1_g,mat,w.hpp

Einsum expression:
W(g), TMP0(g, mat, w) -> TMP1(g, mat, w)

The einsum expression is decomposed into:
W(g), TMP0(g, mat, w) -> TMP1(g, mat, w)

The index paths are derived to be:
TOP
└── w
    └── mat
        └── g
*/
{
	[[maybe_unused]] const int g_len = W.dimension(0);
	assert( g_len == TMP0.dimension(0) );
	assert( g_len == TMP1.dimension(0) );
	[[maybe_unused]] const int mat_len = TMP0.dimension(1);
	assert( mat_len == TMP1.dimension(1) );
	[[maybe_unused]] const int w_len = TMP0.dimension(2);
	assert( w_len == TMP1.dimension(2) );
	for ( int w = 0; w < w_len; w++ ){
		for ( int mat = 0; mat < mat_len; mat++ ){
			double* TMP1_matw = &TMP1(0, mat, w);
			const double* W_ = &W(0);
			const double* TMP0_matw = &TMP0(0, mat, w);
			#pragma omp simd simdlen(8) aligned(TMP1_matw, W_, TMP0_matw: 64)
			for ( int g = 0; g < g_len; g++ ){
				TMP1_matw[g] += W_[g] * TMP0_matw[g];
			}
		}
	}
}
