/*
Generated by EigenEinSum

Recommended filename:
W_g...Eps1Rho_g,w...AO1a_g,mu,t...AO_g,nu---F0a_mu,nu,t,w.hpp

Einsum expression:
W(g), Eps1Rho(g, w), AO1a(g, mu, t), AO(g, nu) -> F0a(mu, nu, t, w)

The einsum expression is decomposed into:
W(g), Eps1Rho(g, w) -> WEps1Rho(g, w)
WEps1Rho(g, w), AO1a(g, mu, t) -> WEps1RhoAO1a(g, mu, t, w)
WEps1RhoAO1a(g, mu, t, w), AO(g, nu) -> F0a(mu, nu, t, w)

The index paths are derived to be:
TOP
└── w
    ├── g
    └── t
        └── mu
            ├── g
            └── nu
                └── g
*/
{
	[[maybe_unused]] const int mu_len = AO1a.dimension(1);
	assert( mu_len == F0a.dimension(0) );
	[[maybe_unused]] const int nu_len = AO.dimension(1);
	assert( nu_len == F0a.dimension(1) );
	[[maybe_unused]] const int t_len = AO1a.dimension(2);
	assert( t_len == F0a.dimension(2) );
	[[maybe_unused]] const int w_len = Eps1Rho.dimension(1);
	assert( w_len == F0a.dimension(3) );
	[[maybe_unused]] const int g_len = W.dimension(0);
	assert( g_len == Eps1Rho.dimension(0) );
	assert( g_len == AO1a.dimension(0) );
	assert( g_len == AO.dimension(0) );
	Eigen::Tensor<double, 1> WEps1Rhow(g_len);
	Eigen::Tensor<double, 1> WEps1RhoAO1awtmu(g_len);
	for ( int w = 0; w < w_len; w++ ){
		WEps1Rhow.setZero();
		double* WEps1Rhow_ = &WEps1Rhow(0);
		const double* W_ = &W(0);
		const double* Eps1Rho_w = &Eps1Rho(0, w);
		#pragma omp simd simdlen(8) aligned(WEps1Rhow_, W_, Eps1Rho_w: 64)
		for ( int g = 0; g < g_len; g++ ){
			WEps1Rhow_[g] += W_[g] * Eps1Rho_w[g];
		}
		for ( int t = 0; t < t_len; t++ ){
			for ( int mu = 0; mu < mu_len; mu++ ){
				WEps1RhoAO1awtmu.setZero();
				double* WEps1RhoAO1awtmu_ = &WEps1RhoAO1awtmu(0);
				const double* WEps1Rhow_ = &WEps1Rhow(0);
				const double* AO1a_mut = &AO1a(0, mu, t);
				#pragma omp simd simdlen(8) aligned(WEps1RhoAO1awtmu_, WEps1Rhow_, AO1a_mut: 64)
				for ( int g = 0; g < g_len; g++ ){
					WEps1RhoAO1awtmu_[g] += WEps1Rhow_[g] * AO1a_mut[g];
				}
				for ( int nu = 0; nu < nu_len; nu++ ){
					double _F0amunutw = 0;
					const double* WEps1RhoAO1awtmu_ = &WEps1RhoAO1awtmu(0);
					const double* AO_nu = &AO(0, nu);
					#pragma omp simd simdlen(8) reduction(+: _F0amunutw) aligned(WEps1RhoAO1awtmu_, AO_nu: 64)
					for ( int g = 0; g < g_len; g++ ){
						_F0amunutw += WEps1RhoAO1awtmu_[g] * AO_nu[g];
					}
					F0a(mu, nu, t, w) += _F0amunutw;
				}
			}
		}
	}
}
