/*
Generated by EigenEinSum

Recommended filename:
W_g...E1Sigma_g...Rho1_g,r...AO1_g,mu,r...AO_g,nu---F1_mu,nu.hpp

Einsum expression:
W(g), E1Sigma(g), Rho1(g, r), AO1(g, mu, r), AO(g, nu) -> F1(mu, nu)

The einsum expression is decomposed into:
W(g), E1Sigma(g) -> WE1Sigma(g)
WE1Sigma(g), Rho1(g, r) -> WE1SigmaRho1(g, r)
WE1SigmaRho1(g, r), AO1(g, mu, r) -> WE1SigmaRho1AO1(g, mu)
WE1SigmaRho1AO1(g, mu), AO(g, nu) -> F1(mu, nu)

The index paths are derived to be:
TOP
├── g
├── r
│   └── g
├── mu
│   └── r
│       └── g
└── nu
    └── mu
        └── g
*/
{
	[[maybe_unused]] const int mu_len = AO1.dimension(1);
	assert( mu_len == F1.dimension(0) );
	[[maybe_unused]] const int nu_len = AO.dimension(1);
	assert( nu_len == F1.dimension(1) );
	[[maybe_unused]] const int g_len = W.dimension(0);
	assert( g_len == E1Sigma.dimension(0) );
	assert( g_len == Rho1.dimension(0) );
	assert( g_len == AO1.dimension(0) );
	assert( g_len == AO.dimension(0) );
	[[maybe_unused]] const int r_len = Rho1.dimension(1);
	assert( r_len == AO1.dimension(2) );
	EigenTensor<1> WE1Sigma(g_len);
	EigenTensor<2> WE1SigmaRho1(g_len, r_len);
	EigenTensor<2> WE1SigmaRho1AO1(g_len, mu_len);
	WE1Sigma.setZero();
	WE1SigmaRho1.setZero();
	WE1SigmaRho1AO1.setZero();
	double* WE1Sigma_ = &WE1Sigma(0);
	const double* W_ = &W(0);
	const double* E1Sigma_ = &E1Sigma(0);
	#pragma omp simd simdlen(8) aligned(WE1Sigma_, W_, E1Sigma_: 64)
	for ( int g = 0; g < g_len; g++ ){
		WE1Sigma_[g] += W_[g] * E1Sigma_[g];
	}
	for ( int r = 0; r < r_len; r++ ){
		double* WE1SigmaRho1_r = &WE1SigmaRho1(0, r);
		const double* WE1Sigma_ = &WE1Sigma(0);
		const double* Rho1_r = &Rho1(0, r);
		#pragma omp simd simdlen(8) aligned(WE1SigmaRho1_r, WE1Sigma_, Rho1_r: 64)
		for ( int g = 0; g < g_len; g++ ){
			WE1SigmaRho1_r[g] += WE1Sigma_[g] * Rho1_r[g];
		}
	}
	for ( int mu = 0; mu < mu_len; mu++ ){
		for ( int r = 0; r < r_len; r++ ){
			double* WE1SigmaRho1AO1_mu = &WE1SigmaRho1AO1(0, mu);
			const double* WE1SigmaRho1_r = &WE1SigmaRho1(0, r);
			const double* AO1_mur = &AO1(0, mu, r);
			#pragma omp simd simdlen(8) aligned(WE1SigmaRho1AO1_mu, WE1SigmaRho1_r, AO1_mur: 64)
			for ( int g = 0; g < g_len; g++ ){
				WE1SigmaRho1AO1_mu[g] += WE1SigmaRho1_r[g] * AO1_mur[g];
			}
		}
	}
	for ( int nu = 0; nu < nu_len; nu++ ){
		for ( int mu = 0; mu < mu_len; mu++ ){
			double F1munu = 0;
			const double* WE1SigmaRho1AO1_mu = &WE1SigmaRho1AO1(0, mu);
			const double* AO_nu = &AO(0, nu);
			#pragma omp simd simdlen(8) reduction(+: F1munu) aligned(WE1SigmaRho1AO1_mu, AO_nu: 64)
			for ( int g = 0; g < g_len; g++ ){
				F1munu += WE1SigmaRho1AO1_mu[g] * AO_nu[g];
			}
			F1(mu, nu) += F1munu;
		}
	}
}
