/*
Generated by EigenEinSum

Recommended filename:
W_g...TMP0_g,mat---TMP1_g,mat.hpp

Einsum expression:
W(g), TMP0(g, mat) -> TMP1(g, mat)

The einsum expression is decomposed into:
W(g), TMP0(g, mat) -> TMP1(g, mat)

The index paths are derived to be:
TOP
└── mat
    └── g
*/
{
	[[maybe_unused]] const int g_len = W.dimension(0);
	assert( g_len == TMP0.dimension(0) );
	assert( g_len == TMP1.dimension(0) );
	[[maybe_unused]] const int mat_len = TMP0.dimension(1);
	assert( mat_len == TMP1.dimension(1) );
	for ( int mat = 0; mat < mat_len; mat++ ){
		double* TMP1_mat = &TMP1(0, mat);
		const double* W_ = &W(0);
		const double* TMP0_mat = &TMP0(0, mat);
		#pragma omp simd simdlen(8) aligned(TMP1_mat, W_, TMP0_mat: 64)
		for ( int g = 0; g < g_len; g++ ){
			TMP1_mat[g] += W_[g] * TMP0_mat[g];
		}
	}
}
