/*
Generated by EigenEinSum

Recommended filename:
W_g...Eps1Rho_g,w...AO_g,mu...AO_g,nu---F0_mu,nu,w.hpp

Einsum expression:
W(g), Eps1Rho(g, w), AO(g, mu), AO(g, nu) -> F0(mu, nu, w)

The einsum expression is decomposed into:
W(g), Eps1Rho(g, w) -> WEps1Rho(g, w)
WEps1Rho(g, w), AO(g, mu) -> WEps1RhoAO(g, mu, w)
WEps1RhoAO(g, mu, w), AO(g, nu) -> F0(mu, nu, w)

The index paths are derived to be:
TOP
└── w
    ├── g
    └── mu
        ├── g
        └── nu
            └── g
*/
{
	[[maybe_unused]] const int mu_len = AO.dimension(1);
	assert( mu_len == F0.dimension(0) );
	[[maybe_unused]] const int nu_len = AO.dimension(1);
	assert( nu_len == F0.dimension(1) );
	[[maybe_unused]] const int w_len = Eps1Rho.dimension(1);
	assert( w_len == F0.dimension(2) );
	[[maybe_unused]] const int g_len = W.dimension(0);
	assert( g_len == Eps1Rho.dimension(0) );
	assert( g_len == AO.dimension(0) );
	Eigen::Tensor<double, 1> WEps1Rhow(g_len);
	Eigen::Tensor<double, 1> WEps1RhoAOwmu(g_len);
	for ( int w = 0; w < w_len; w++ ){
		WEps1Rhow.setZero();
		double* WEps1Rhow_ = &WEps1Rhow(0);
		const double* W_ = &W(0);
		const double* Eps1Rho_w = &Eps1Rho(0, w);
		#pragma omp simd simdlen(8) aligned(WEps1Rhow_, W_, Eps1Rho_w: 64)
		for ( int g = 0; g < g_len; g++ ){
			WEps1Rhow_[g] += W_[g] * Eps1Rho_w[g];
		}
		for ( int mu = 0; mu < mu_len; mu++ ){
			WEps1RhoAOwmu.setZero();
			double* WEps1RhoAOwmu_ = &WEps1RhoAOwmu(0);
			const double* WEps1Rhow_ = &WEps1Rhow(0);
			const double* AO_mu = &AO(0, mu);
			#pragma omp simd simdlen(8) aligned(WEps1RhoAOwmu_, WEps1Rhow_, AO_mu: 64)
			for ( int g = 0; g < g_len; g++ ){
				WEps1RhoAOwmu_[g] += WEps1Rhow_[g] * AO_mu[g];
			}
			for ( int nu = 0; nu < nu_len; nu++ ){
				double _F0munuw = 0;
				const double* WEps1RhoAOwmu_ = &WEps1RhoAOwmu(0);
				const double* AO_nu = &AO(0, nu);
				#pragma omp simd simdlen(8) reduction(+: _F0munuw) aligned(WEps1RhoAOwmu_, AO_nu: 64)
				for ( int g = 0; g < g_len; g++ ){
					_F0munuw += WEps1RhoAOwmu_[g] * AO_nu[g];
				}
				F0(mu, nu, w) += _F0munuw;
			}
		}
	}
}
