/*
Generated by EigenEinSum

Recommended filename:
W_g...Eps1Lapl_g,w...AO_g,mu...AO2L_g,nu---F2_mu,nu,w.hpp

Einsum expression:
W(g), Eps1Lapl(g, w), AO(g, mu), AO2L(g, nu) -> F2(mu, nu, w)

The einsum expression is decomposed into:
W(g), Eps1Lapl(g, w) -> WEps1Lapl(g, w)
WEps1Lapl(g, w), AO(g, mu) -> WEps1LaplAO(g, mu, w)
WEps1LaplAO(g, mu, w), AO2L(g, nu) -> F2(mu, nu, w)

The index paths are derived to be:
TOP
└── w
    ├── g
    └── mu
        ├── g
        └── nu
            └── g
*/
{
	[[maybe_unused]] const int mu_len = AO.dimension(1);
	assert( mu_len == F2.dimension(0) );
	[[maybe_unused]] const int nu_len = AO2L.dimension(1);
	assert( nu_len == F2.dimension(1) );
	[[maybe_unused]] const int w_len = Eps1Lapl.dimension(1);
	assert( w_len == F2.dimension(2) );
	[[maybe_unused]] const int g_len = W.dimension(0);
	assert( g_len == Eps1Lapl.dimension(0) );
	assert( g_len == AO.dimension(0) );
	assert( g_len == AO2L.dimension(0) );
	Eigen::Tensor<double, 1> WEps1Laplw(g_len);
	Eigen::Tensor<double, 1> WEps1LaplAOwmu(g_len);
	for ( int w = 0; w < w_len; w++ ){
		WEps1Laplw.setZero();
		double* WEps1Laplw_ = &WEps1Laplw(0);
		const double* W_ = &W(0);
		const double* Eps1Lapl_w = &Eps1Lapl(0, w);
		#pragma omp simd simdlen(8) aligned(WEps1Laplw_, W_, Eps1Lapl_w: 64)
		for ( int g = 0; g < g_len; g++ ){
			WEps1Laplw_[g] += W_[g] * Eps1Lapl_w[g];
		}
		for ( int mu = 0; mu < mu_len; mu++ ){
			WEps1LaplAOwmu.setZero();
			double* WEps1LaplAOwmu_ = &WEps1LaplAOwmu(0);
			const double* WEps1Laplw_ = &WEps1Laplw(0);
			const double* AO_mu = &AO(0, mu);
			#pragma omp simd simdlen(8) aligned(WEps1LaplAOwmu_, WEps1Laplw_, AO_mu: 64)
			for ( int g = 0; g < g_len; g++ ){
				WEps1LaplAOwmu_[g] += WEps1Laplw_[g] * AO_mu[g];
			}
			for ( int nu = 0; nu < nu_len; nu++ ){
				double _F2munuw = 0;
				const double* WEps1LaplAOwmu_ = &WEps1LaplAOwmu(0);
				const double* AO2L_nu = &AO2L(0, nu);
				#pragma omp simd simdlen(8) reduction(+: _F2munuw) aligned(WEps1LaplAOwmu_, AO2L_nu: 64)
				for ( int g = 0; g < g_len; g++ ){
					_F2munuw += WEps1LaplAOwmu_[g] * AO2L_nu[g];
				}
				F2(mu, nu, w) += _F2munuw;
			}
		}
	}
}
