/*
Generated by EigenEinSum

Recommended filename:
W_g...V_g,mat,w...AO1_g,mu,r...AO1_g,nu,r---F2_mu,nu,mat,w.hpp

Einsum expression:
W(g), V(g, mat, w), AO1(g, mu, r), AO1(g, nu, r) -> F2(mu, nu, mat, w)

The einsum expression is decomposed into:
W(g), V(g, mat, w) -> WV(g, mat, w)
WV(g, mat, w), AO1(g, mu, r) -> WVAO1(g, mu, r, mat, w)
WVAO1(g, mu, r, mat, w), AO1(g, nu, r) -> F2(mu, nu, mat, w)

The index paths are derived to be:
TOP
└── w
    └── mat
        ├── g
        └── r
            └── mu
                ├── g
                └── nu
                    └── g
*/
{
	[[maybe_unused]] const int mu_len = AO1.dimension(1);
	assert( mu_len == F2.dimension(0) );
	[[maybe_unused]] const int nu_len = AO1.dimension(1);
	assert( nu_len == F2.dimension(1) );
	[[maybe_unused]] const int mat_len = V.dimension(1);
	assert( mat_len == F2.dimension(2) );
	[[maybe_unused]] const int w_len = V.dimension(2);
	assert( w_len == F2.dimension(3) );
	[[maybe_unused]] const int g_len = W.dimension(0);
	assert( g_len == V.dimension(0) );
	assert( g_len == AO1.dimension(0) );
	[[maybe_unused]] const int r_len = AO1.dimension(2);
	assert( r_len == AO1.dimension(2) );
	Eigen::Tensor<double, 1> WVwmat(g_len);
	Eigen::Tensor<double, 1> WVAO1wmatrmu(g_len);
	for ( int w = 0; w < w_len; w++ ){
		for ( int mat = 0; mat < mat_len; mat++ ){
			WVwmat.setZero();
			double* WVwmat_ = &WVwmat(0);
			const double* W_ = &W(0);
			const double* V_matw = &V(0, mat, w);
			#pragma omp simd simdlen(8) aligned(WVwmat_, W_, V_matw: 64)
			for ( int g = 0; g < g_len; g++ ){
				WVwmat_[g] += W_[g] * V_matw[g];
			}
			for ( int r = 0; r < r_len; r++ ){
				for ( int mu = 0; mu < mu_len; mu++ ){
					WVAO1wmatrmu.setZero();
					double* WVAO1wmatrmu_ = &WVAO1wmatrmu(0);
					const double* WVwmat_ = &WVwmat(0);
					const double* AO1_mur = &AO1(0, mu, r);
					#pragma omp simd simdlen(8) aligned(WVAO1wmatrmu_, WVwmat_, AO1_mur: 64)
					for ( int g = 0; g < g_len; g++ ){
						WVAO1wmatrmu_[g] += WVwmat_[g] * AO1_mur[g];
					}
					for ( int nu = 0; nu < nu_len; nu++ ){
						double _F2munumatw = 0;
						const double* WVAO1wmatrmu_ = &WVAO1wmatrmu(0);
						const double* AO1_nur = &AO1(0, nu, r);
						#pragma omp simd simdlen(8) reduction(+: _F2munumatw) aligned(WVAO1wmatrmu_, AO1_nur: 64)
						for ( int g = 0; g < g_len; g++ ){
							_F2munumatw += WVAO1wmatrmu_[g] * AO1_nur[g];
						}
						F2(mu, nu, mat, w) += _F2munumatw;
					}
				}
			}
		}
	}
}
