/*
Generated by EigenEinSum

Recommended filename:
W_g...TMP4_g,r,mat...AO1_g,mu,r...AO_g,nu---F1_mu,nu,mat.hpp

Einsum expression:
W(g), TMP4(g, r, mat), AO1(g, mu, r), AO(g, nu) -> F1(mu, nu, mat)

The einsum expression is decomposed into:
W(g), TMP4(g, r, mat) -> WTMP4(g, r, mat)
WTMP4(g, r, mat), AO1(g, mu, r) -> WTMP4AO1(g, mu, mat)
WTMP4AO1(g, mu, mat), AO(g, nu) -> F1(mu, nu, mat)

The index paths are derived to be:
TOP
└── mat
    ├── r
    │   ├── g
    │   └── mu
    │       └── g
    └── nu
        └── mu
            └── g
*/
{
	[[maybe_unused]] const int mu_len = AO1.dimension(1);
	assert( mu_len == F1.dimension(0) );
	[[maybe_unused]] const int nu_len = AO.dimension(1);
	assert( nu_len == F1.dimension(1) );
	[[maybe_unused]] const int mat_len = TMP4.dimension(2);
	assert( mat_len == F1.dimension(2) );
	[[maybe_unused]] const int g_len = W.dimension(0);
	assert( g_len == TMP4.dimension(0) );
	assert( g_len == AO1.dimension(0) );
	assert( g_len == AO.dimension(0) );
	[[maybe_unused]] const int r_len = TMP4.dimension(1);
	assert( r_len == AO1.dimension(2) );
	EigenTensor<2> WTMP4AO1mat(g_len, mu_len);
	EigenTensor<1> WTMP4matr(g_len);
	for ( int mat = 0; mat < mat_len; mat++ ){
		WTMP4AO1mat.setZero();
		for ( int r = 0; r < r_len; r++ ){
			WTMP4matr.setZero();
			double* WTMP4matr_ = &WTMP4matr(0);
			const double* W_ = &W(0);
			const double* TMP4_rmat = &TMP4(0, r, mat);
			#pragma omp simd simdlen(8) aligned(WTMP4matr_, W_, TMP4_rmat: 64)
			for ( int g = 0; g < g_len; g++ ){
				WTMP4matr_[g] += W_[g] * TMP4_rmat[g];
			}
			for ( int mu = 0; mu < mu_len; mu++ ){
				double* WTMP4AO1mat_mu = &WTMP4AO1mat(0, mu);
				const double* WTMP4matr_ = &WTMP4matr(0);
				const double* AO1_mur = &AO1(0, mu, r);
				#pragma omp simd simdlen(8) aligned(WTMP4AO1mat_mu, WTMP4matr_, AO1_mur: 64)
				for ( int g = 0; g < g_len; g++ ){
					WTMP4AO1mat_mu[g] += WTMP4matr_[g] * AO1_mur[g];
				}
			}
		}
		for ( int nu = 0; nu < nu_len; nu++ ){
			for ( int mu = 0; mu < mu_len; mu++ ){
				double F1munumat = 0;
				const double* WTMP4AO1mat_mu = &WTMP4AO1mat(0, mu);
				const double* AO_nu = &AO(0, nu);
				#pragma omp simd simdlen(8) reduction(+: F1munumat) aligned(WTMP4AO1mat_mu, AO_nu: 64)
				for ( int g = 0; g < g_len; g++ ){
					F1munumat += WTMP4AO1mat_mu[g] * AO_nu[g];
				}
				F1(mu, nu, mat) += F1munumat;
			}
		}
	}
}
