/*
Generated by EigenEinSum

Recommended filename:
W_g...TMP5_g,mat,w...AO_g,mu...AO2L_g,nu---F2_mu,nu,mat,w.hpp

Einsum expression:
W(g), TMP5(g, mat, w), AO(g, mu), AO2L(g, nu) -> F2(mu, nu, mat, w)

The einsum expression is decomposed into:
W(g), TMP5(g, mat, w) -> WTMP5(g, mat, w)
WTMP5(g, mat, w), AO(g, mu) -> WTMP5AO(g, mu, mat, w)
WTMP5AO(g, mu, mat, w), AO2L(g, nu) -> F2(mu, nu, mat, w)

The index paths are derived to be:
TOP
└── w
    └── mat
        ├── g
        └── mu
            ├── g
            └── nu
                └── g
*/
{
	[[maybe_unused]] const int mu_len = AO.dimension(1);
	assert( mu_len == F2.dimension(0) );
	[[maybe_unused]] const int nu_len = AO2L.dimension(1);
	assert( nu_len == F2.dimension(1) );
	[[maybe_unused]] const int mat_len = TMP5.dimension(1);
	assert( mat_len == F2.dimension(2) );
	[[maybe_unused]] const int w_len = TMP5.dimension(2);
	assert( w_len == F2.dimension(3) );
	[[maybe_unused]] const int g_len = W.dimension(0);
	assert( g_len == TMP5.dimension(0) );
	assert( g_len == AO.dimension(0) );
	assert( g_len == AO2L.dimension(0) );
	Eigen::Tensor<double, 1> WTMP5wmat(g_len);
	Eigen::Tensor<double, 1> WTMP5AOwmatmu(g_len);
	for ( int w = 0; w < w_len; w++ ){
		for ( int mat = 0; mat < mat_len; mat++ ){
			WTMP5wmat.setZero();
			double* WTMP5wmat_ = &WTMP5wmat(0);
			const double* W_ = &W(0);
			const double* TMP5_matw = &TMP5(0, mat, w);
			#pragma omp simd simdlen(8) aligned(WTMP5wmat_, W_, TMP5_matw: 64)
			for ( int g = 0; g < g_len; g++ ){
				WTMP5wmat_[g] += W_[g] * TMP5_matw[g];
			}
			for ( int mu = 0; mu < mu_len; mu++ ){
				WTMP5AOwmatmu.setZero();
				double* WTMP5AOwmatmu_ = &WTMP5AOwmatmu(0);
				const double* WTMP5wmat_ = &WTMP5wmat(0);
				const double* AO_mu = &AO(0, mu);
				#pragma omp simd simdlen(8) aligned(WTMP5AOwmatmu_, WTMP5wmat_, AO_mu: 64)
				for ( int g = 0; g < g_len; g++ ){
					WTMP5AOwmatmu_[g] += WTMP5wmat_[g] * AO_mu[g];
				}
				for ( int nu = 0; nu < nu_len; nu++ ){
					double _F2munumatw = 0;
					const double* WTMP5AOwmatmu_ = &WTMP5AOwmatmu(0);
					const double* AO2L_nu = &AO2L(0, nu);
					#pragma omp simd simdlen(8) reduction(+: _F2munumatw) aligned(WTMP5AOwmatmu_, AO2L_nu: 64)
					for ( int g = 0; g < g_len; g++ ){
						_F2munumatw += WTMP5AOwmatmu_[g] * AO2L_nu[g];
					}
					F2(mu, nu, mat, w) += _F2munumatw;
				}
			}
		}
	}
}
