/*
Generated by EigenEinSum

Recommended filename:
W_g...E1Rho_g...AO_g,mu...AO_g,nu---F0_mu,nu.hpp

Einsum expression:
W(g), E1Rho(g), AO(g, mu), AO(g, nu) -> F0(mu, nu)

The einsum expression is decomposed into:
W(g), E1Rho(g) -> WE1Rho(g)
WE1Rho(g), AO(g, mu) -> WE1RhoAO(g, mu)
WE1RhoAO(g, mu), AO(g, nu) -> F0(mu, nu)

The index paths are derived to be:
TOP
├── g
├── mu
│   └── g
└── nu
    └── mu
        └── g
*/
{
	[[maybe_unused]] const int mu_len = AO.dimension(1);
	assert( mu_len == F0.dimension(0) );
	[[maybe_unused]] const int nu_len = AO.dimension(1);
	assert( nu_len == F0.dimension(1) );
	[[maybe_unused]] const int g_len = W.dimension(0);
	assert( g_len == E1Rho.dimension(0) );
	assert( g_len == AO.dimension(0) );
	EigenTensor<1> WE1Rho(g_len);
	EigenTensor<2> WE1RhoAO(g_len, mu_len);
	WE1Rho.setZero();
	WE1RhoAO.setZero();
	const double* WE1Rho_ = &WE1Rho(0);
	const double* W_ = &W(0);
	const double* E1Rho_ = &E1Rho(0);
	#pragma omp simd simdlen(8) aligned(WE1Rho_, W_, E1Rho_: 64)
	for ( int g = 0; g < g_len; g++ ){
		WE1Rho_[g] += W_[g] * E1Rho_[g];
	}
	for ( int mu = 0; mu < mu_len; mu++ ){
		double* WE1RhoAO_mu = &WE1RhoAO(0, mu);
		const double* WE1Rho_ = &WE1Rho(0);
		const double* AO_mu = &AO(0, mu);
		#pragma omp simd simdlen(8) aligned(WE1RhoAO_mu, WE1Rho_, AO_mu: 64)
		for ( int g = 0; g < g_len; g++ ){
			WE1RhoAO_mu[g] += WE1Rho_[g] * AO_mu[g];
		}
	}
	for ( int nu = 0; nu < nu_len; nu++ ){
		for ( int mu = 0; mu < mu_len; mu++ ){
			double F0munu = 0;
			const double* WE1RhoAO_mu = &WE1RhoAO(0, mu);
			const double* AO_nu = &AO(0, nu);
			#pragma omp simd simdlen(8) reduction(+: F0munu) aligned(WE1RhoAO_mu, AO_nu: 64)
			for ( int g = 0; g < g_len; g++ ){
				F0munu += WE1RhoAO_mu[g] * AO_nu[g];
			}
			F0(mu, nu) += F0munu;
		}
	}
}
