/*
Generated by EigenEinSum

Recommended filename:
W_g...E1Rho_g...AO1a_g,mu,t...AO_g,nu---F0a_mu,nu,t.hpp

Einsum expression:
W(g), E1Rho(g), AO1a(g, mu, t), AO(g, nu) -> F0a(mu, nu, t)

The einsum expression is decomposed into:
W(g), E1Rho(g) -> WE1Rho(g)
WE1Rho(g), AO1a(g, mu, t) -> WE1RhoAO1a(g, mu, t)
WE1RhoAO1a(g, mu, t), AO(g, nu) -> F0a(mu, nu, t)

The index paths are derived to be:
TOP
├── g
└── t
    ├── mu
    │   └── g
    └── nu
        └── mu
            └── g
*/
{
	[[maybe_unused]] const int mu_len = AO1a.dimension(1);
	assert( mu_len == F0a.dimension(0) );
	[[maybe_unused]] const int nu_len = AO.dimension(1);
	assert( nu_len == F0a.dimension(1) );
	[[maybe_unused]] const int t_len = AO1a.dimension(2);
	assert( t_len == F0a.dimension(2) );
	[[maybe_unused]] const int g_len = W.dimension(0);
	assert( g_len == E1Rho.dimension(0) );
	assert( g_len == AO1a.dimension(0) );
	assert( g_len == AO.dimension(0) );
	EigenTensor<1> WE1Rho(g_len);
	EigenTensor<2> WE1RhoAO1at(g_len, mu_len);
	WE1Rho.setZero();
	double* WE1Rho_ = &WE1Rho(0);
	const double* W_ = &W(0);
	const double* E1Rho_ = &E1Rho(0);
	#pragma omp simd simdlen(8) aligned(WE1Rho_, W_, E1Rho_: 64)
	for ( int g = 0; g < g_len; g++ ){
		WE1Rho_[g] += W_[g] * E1Rho_[g];
	}
	for ( int t = 0; t < t_len; t++ ){
		WE1RhoAO1at.setZero();
		for ( int mu = 0; mu < mu_len; mu++ ){
			double* WE1RhoAO1at_mu = &WE1RhoAO1at(0, mu);
			const double* WE1Rho_ = &WE1Rho(0);
			const double* AO1a_mut = &AO1a(0, mu, t);
			#pragma omp simd simdlen(8) aligned(WE1RhoAO1at_mu, WE1Rho_, AO1a_mut: 64)
			for ( int g = 0; g < g_len; g++ ){
				WE1RhoAO1at_mu[g] += WE1Rho_[g] * AO1a_mut[g];
			}
		}
		for ( int nu = 0; nu < nu_len; nu++ ){
			for ( int mu = 0; mu < mu_len; mu++ ){
				double F0amunut = 0;
				const double* WE1RhoAO1at_mu = &WE1RhoAO1at(0, mu);
				const double* AO_nu = &AO(0, nu);
				#pragma omp simd simdlen(8) reduction(+: F0amunut) aligned(WE1RhoAO1at_mu, AO_nu: 64)
				for ( int g = 0; g < g_len; g++ ){
					F0amunut += WE1RhoAO1at_mu[g] * AO_nu[g];
				}
				F0a(mu, nu, t) += F0amunut;
			}
		}
	}
}
