/*
Generated by EigenEinSum

Recommended filename:
W_g...E1Lapl_g...AO_g,mu...AO2L_g,nu---F2_mu,nu.hpp

Einsum expression:
W(g), E1Lapl(g), AO(g, mu), AO2L(g, nu) -> F2(mu, nu)

The einsum expression is decomposed into:
W(g), E1Lapl(g) -> WE1Lapl(g)
WE1Lapl(g), AO(g, mu) -> WE1LaplAO(g, mu)
WE1LaplAO(g, mu), AO2L(g, nu) -> F2(mu, nu)

The index paths are derived to be:
TOP
├── g
├── mu
│   └── g
└── nu
    └── mu
        └── g
*/
{
	[[maybe_unused]] const int mu_len = AO.dimension(1);
	assert( mu_len == F2.dimension(0) );
	[[maybe_unused]] const int nu_len = AO2L.dimension(1);
	assert( nu_len == F2.dimension(1) );
	[[maybe_unused]] const int g_len = W.dimension(0);
	assert( g_len == E1Lapl.dimension(0) );
	assert( g_len == AO.dimension(0) );
	assert( g_len == AO2L.dimension(0) );
	EigenTensor<1> WE1Lapl(g_len);
	EigenTensor<2> WE1LaplAO(g_len, mu_len);
	WE1Lapl.setZero();
	WE1LaplAO.setZero();
	double* WE1Lapl_ = &WE1Lapl(0);
	const double* W_ = &W(0);
	const double* E1Lapl_ = &E1Lapl(0);
	#pragma omp simd simdlen(8) aligned(WE1Lapl_, W_, E1Lapl_: 64)
	for ( int g = 0; g < g_len; g++ ){
		WE1Lapl_[g] += W_[g] * E1Lapl_[g];
	}
	for ( int mu = 0; mu < mu_len; mu++ ){
		double* WE1LaplAO_mu = &WE1LaplAO(0, mu);
		const double* WE1Lapl_ = &WE1Lapl(0);
		const double* AO_mu = &AO(0, mu);
		#pragma omp simd simdlen(8) aligned(WE1LaplAO_mu, WE1Lapl_, AO_mu: 64)
		for ( int g = 0; g < g_len; g++ ){
			WE1LaplAO_mu[g] += WE1Lapl_[g] * AO_mu[g];
		}
	}
	for ( int nu = 0; nu < nu_len; nu++ ){
		for ( int mu = 0; mu < mu_len; mu++ ){
			double F2munu = 0;
			const double* WE1LaplAO_mu = &WE1LaplAO(0, mu);
			const double* AO2L_nu = &AO2L(0, nu);
			#pragma omp simd simdlen(8) reduction(+: F2munu) aligned(WE1LaplAO_mu, AO2L_nu: 64)
			for ( int g = 0; g < g_len; g++ ){
				F2munu += WE1LaplAO_mu[g] * AO2L_nu[g];
			}
			F2(mu, nu) += F2munu;
		}
	}
}
