/*
Generated by EigenEinSum

Recommended filename:
W_g...V_g,w...AO1_g,mu,r...AO1_g,nu,r---F2_mu,nu,w.hpp

Einsum expression:
W(g), V(g, w), AO1(g, mu, r), AO1(g, nu, r) -> F2(mu, nu, w)

The einsum expression is decomposed into:
W(g), V(g, w) -> WV(g, w)
WV(g, w), AO1(g, mu, r) -> WVAO1(g, mu, r, w)
WVAO1(g, mu, r, w), AO1(g, nu, r) -> F2(mu, nu, w)

The index paths are derived to be:
TOP
└── w
    ├── g
    └── r
        └── mu
            ├── g
            └── nu
                └── g
*/
{
	[[maybe_unused]] const int mu_len = AO1.dimension(1);
	assert( mu_len == F2.dimension(0) );
	[[maybe_unused]] const int nu_len = AO1.dimension(1);
	assert( nu_len == F2.dimension(1) );
	[[maybe_unused]] const int w_len = V.dimension(1);
	assert( w_len == F2.dimension(2) );
	[[maybe_unused]] const int g_len = W.dimension(0);
	assert( g_len == V.dimension(0) );
	assert( g_len == AO1.dimension(0) );
	[[maybe_unused]] const int r_len = AO1.dimension(2);
	assert( r_len == AO1.dimension(2) );
	Eigen::Tensor<double, 1> WVw(g_len);
	Eigen::Tensor<double, 1> WVAO1wrmu(g_len);
	for ( int w = 0; w < w_len; w++ ){
		WVw.setZero();
		double* WVw_ = &WVw(0);
		const double* W_ = &W(0);
		const double* V_w = &V(0, w);
		#pragma omp simd simdlen(8) aligned(WVw_, W_, V_w: 64)
		for ( int g = 0; g < g_len; g++ ){
			WVw_[g] += W_[g] * V_w[g];
		}
		for ( int r = 0; r < r_len; r++ ){
			for ( int mu = 0; mu < mu_len; mu++ ){
				WVAO1wrmu.setZero();
				double* WVAO1wrmu_ = &WVAO1wrmu(0);
				const double* WVw_ = &WVw(0);
				const double* AO1_mur = &AO1(0, mu, r);
				#pragma omp simd simdlen(8) aligned(WVAO1wrmu_, WVw_, AO1_mur: 64)
				for ( int g = 0; g < g_len; g++ ){
					WVAO1wrmu_[g] += WVw_[g] * AO1_mur[g];
				}
				for ( int nu = 0; nu < nu_len; nu++ ){
					double _F2munuw = 0;
					const double* WVAO1wrmu_ = &WVAO1wrmu(0);
					const double* AO1_nur = &AO1(0, nu, r);
					#pragma omp simd simdlen(8) reduction(+: _F2munuw) aligned(WVAO1wrmu_, AO1_nur: 64)
					for ( int g = 0; g < g_len; g++ ){
						_F2munuw += WVAO1wrmu_[g] * AO1_nur[g];
					}
					F2(mu, nu, w) += _F2munuw;
				}
			}
		}
	}
}
