/*
Generated by EigenEinSum

Recommended filename:
Ws_g...E1Rhos_g...AOs_g,mu...AOs_g,nu---F0_mu,nu.hpp

Einsum expression:
Ws(g), E1Rhos(g), AOs(g, mu), AOs(g, nu) -> F0(mu, nu)

The einsum expression is decomposed into:
Ws(g), E1Rhos(g) -> WsE1Rhos(g)
WsE1Rhos(g), AOs(g, mu) -> WsE1RhosAOs(g, mu)
WsE1RhosAOs(g, mu), AOs(g, nu) -> F0(mu, nu)

The index paths are derived to be:
TOP
├── g
└── mu
    ├── g
    └── nu
        └── g
*/
{
	const int mu_len = AOs.dimension(1);
	assert( mu_len == F0.dimension(0) );
	const int nu_len = AOs.dimension(1);
	assert( nu_len == F0.dimension(1) );
	const int g_len = Ws.dimension(0);
	assert( g_len == E1Rhos.dimension(0) );
	assert( g_len == AOs.dimension(0) );
	assert( g_len == AOs.dimension(0) );
	Eigen::Tensor<double, 1> WsE1Rhos(g_len);
	WsE1Rhos.setZero();
	Eigen::Tensor<double, 1> WsE1RhosAOsmu(g_len);
	for ( int g = 0; g < g_len; g++ ){
		WsE1Rhos(g) += Ws(g) * E1Rhos(g);
	}
	for ( int mu = 0; mu < mu_len; mu++ ){
		WsE1RhosAOsmu.setZero();
		for ( int g = 0; g < g_len; g++ ){
			WsE1RhosAOsmu(g) += WsE1Rhos(g) * AOs(g, mu);
		}
		for ( int nu = 0; nu < nu_len; nu++ ){
			for ( int g = 0; g < g_len; g++ ){
				F0(mu, nu) += WsE1RhosAOsmu(g) * AOs(g, nu);
			}
		}
	}
}
