/*
Generated by EigenEinSum

Recommended filename:
Ws_g...E2RhoSigmas_g...SigmaGrads_g,t,a...AOs_g,mu...AOs_g,nu---F1_mu,nu,t,a.hpp

Einsum expression:
Ws(g), E2RhoSigmas(g), SigmaGrads(g, t, a), AOs(g, mu), AOs(g, nu) -> F1(mu, nu, t, a)

The einsum expression is decomposed into:
Ws(g), E2RhoSigmas(g) -> WsE2RhoSigmas(g)
WsE2RhoSigmas(g), SigmaGrads(g, t, a) -> WsE2RhoSigmasSigmaGrads(g, t, a)
WsE2RhoSigmasSigmaGrads(g, t, a), AOs(g, mu) -> WsE2RhoSigmasSigmaGradsAOs(g, mu, t, a)
WsE2RhoSigmasSigmaGradsAOs(g, mu, t, a), AOs(g, nu) -> F1(mu, nu, t, a)

The index paths are derived to be:
TOP
├── g
└── a
    └── t
        ├── g
        └── mu
            ├── g
            └── nu
                └── g
*/
{
	const int mu_len = AOs.dimensions()[1];
	assert( mu_len == F1.dimensions()[0] );
	const int nu_len = AOs.dimensions()[1];
	assert( nu_len == F1.dimensions()[1] );
	const int t_len = SigmaGrads.dimensions()[1];
	assert( t_len == F1.dimensions()[2] );
	const int a_len = SigmaGrads.dimensions()[2];
	assert( a_len == F1.dimensions()[3] );
	const int g_len = Ws.dimensions()[0];
	assert( g_len == E2RhoSigmas.dimensions()[0] );
	assert( g_len == SigmaGrads.dimensions()[0] );
	assert( g_len == AOs.dimensions()[0] );
	assert( g_len == AOs.dimensions()[0] );
	Eigen::Tensor<double, 1> WsE2RhoSigmas(g_len);
	WsE2RhoSigmas.setZero();
	Eigen::Tensor<double, 1> WsE2RhoSigmasSigmaGradsat(g_len);
	Eigen::Tensor<double, 1> WsE2RhoSigmasSigmaGradsAOsatmu(g_len);
	for ( int g = 0; g < g_len; g++ ){
		WsE2RhoSigmas(g) += Ws(g) * E2RhoSigmas(g);
	}
	for ( int a = 0; a < a_len; a++ ){
		for ( int t = 0; t < t_len; t++ ){
			WsE2RhoSigmasSigmaGradsat.setZero();
			for ( int g = 0; g < g_len; g++ ){
				WsE2RhoSigmasSigmaGradsat(g) += WsE2RhoSigmas(g) * SigmaGrads(g, t, a);
			}
			for ( int mu = 0; mu < mu_len; mu++ ){
				WsE2RhoSigmasSigmaGradsAOsatmu.setZero();
				for ( int g = 0; g < g_len; g++ ){
					WsE2RhoSigmasSigmaGradsAOsatmu(g) += WsE2RhoSigmasSigmaGradsat(g) * AOs(g, mu);
				}
				for ( int nu = 0; nu < nu_len; nu++ ){
					for ( int g = 0; g < g_len; g++ ){
						F1(mu, nu, t, a) += WsE2RhoSigmasSigmaGradsAOsatmu(g) * AOs(g, nu);
					}
				}
			}
		}
	}
}
