/*
Generated by EigenEinSum

Recommended filename:
Ws_g...E1Sigmas_g...Rho1Grads_g,r,t,a...AO1s_g,mu,r...AOs_g,nu---F1_mu,nu,t,a.hpp

Einsum expression:
Ws(g), E1Sigmas(g), Rho1Grads(g, r, t, a), AO1s(g, mu, r), AOs(g, nu) -> F1(mu, nu, t, a)

The einsum expression is decomposed into:
Ws(g), E1Sigmas(g) -> WsE1Sigmas(g)
WsE1Sigmas(g), Rho1Grads(g, r, t, a) -> WsE1SigmasRho1Grads(g, r, t, a)
WsE1SigmasRho1Grads(g, r, t, a), AO1s(g, mu, r) -> WsE1SigmasRho1GradsAO1s(g, mu, t, a)
WsE1SigmasRho1GradsAO1s(g, mu, t, a), AOs(g, nu) -> F1(mu, nu, t, a)

The index paths are derived to be:
TOP
├── g
└── a
    └── t
        ├── r
        │   └── g
        └── mu
            ├── r
            │   └── g
            └── nu
                └── g
*/
{
	const int mu_len = AO1s.dimension(1);
	assert( mu_len == F1.dimension(0) );
	const int nu_len = AOs.dimension(1);
	assert( nu_len == F1.dimension(1) );
	const int t_len = Rho1Grads.dimension(2);
	assert( t_len == F1.dimension(2) );
	const int a_len = Rho1Grads.dimension(3);
	assert( a_len == F1.dimension(3) );
	const int g_len = Ws.dimension(0);
	assert( g_len == E1Sigmas.dimension(0) );
	assert( g_len == Rho1Grads.dimension(0) );
	assert( g_len == AO1s.dimension(0) );
	assert( g_len == AOs.dimension(0) );
	const int r_len = Rho1Grads.dimension(1);
	assert( r_len == AO1s.dimension(2) );
	Eigen::Tensor<double, 1> WsE1Sigmas(g_len);
	WsE1Sigmas.setZero();
	Eigen::Tensor<double, 2> WsE1SigmasRho1Gradsat(g_len, r_len);
	Eigen::Tensor<double, 1> WsE1SigmasRho1GradsAO1satmu(g_len);
	for ( int g = 0; g < g_len; g++ ){
		WsE1Sigmas(g) += Ws(g) * E1Sigmas(g);
	}
	for ( int a = 0; a < a_len; a++ ){
		for ( int t = 0; t < t_len; t++ ){
			WsE1SigmasRho1Gradsat.setZero();
			for ( int r = 0; r < r_len; r++ ){
				for ( int g = 0; g < g_len; g++ ){
					WsE1SigmasRho1Gradsat(g, r) += WsE1Sigmas(g) * Rho1Grads(g, r, t, a);
				}
			}
			for ( int mu = 0; mu < mu_len; mu++ ){
				WsE1SigmasRho1GradsAO1satmu.setZero();
				for ( int r = 0; r < r_len; r++ ){
					for ( int g = 0; g < g_len; g++ ){
						WsE1SigmasRho1GradsAO1satmu(g) += WsE1SigmasRho1Gradsat(g, r) * AO1s(g, mu, r);
					}
				}
				for ( int nu = 0; nu < nu_len; nu++ ){
					for ( int g = 0; g < g_len; g++ ){
						F1(mu, nu, t, a) += WsE1SigmasRho1GradsAO1satmu(g) * AOs(g, nu);
					}
				}
			}
		}
	}
}
