/*
Generated by EigenEinSum

Recommended filename:
S_u,v...Eps1Sigma_g,u+v---ScaledEps1Sigma_g,u,v.hpp

Einsum expression:
S(u, v), Eps1Sigma(g, u+v) -> ScaledEps1Sigma(g, u, v)

The einsum expression is decomposed into:
S(u, v), Eps1Sigma(g, u+v) -> ScaledEps1Sigma(g, u, v)

The index paths are derived to be:
TOP
└── v
    └── u
        └── g
*/
{
	[[maybe_unused]] const int g_len = Eps1Sigma.dimension(0);
	assert( g_len == ScaledEps1Sigma.dimension(0) );
	[[maybe_unused]] const int u_len = S.dimension(0);
	assert( u_len == ScaledEps1Sigma.dimension(1) );
	[[maybe_unused]] const int v_len = S.dimension(1);
	assert( v_len == ScaledEps1Sigma.dimension(2) );
	[[maybe_unused]] const int u_v_len = Eps1Sigma.dimension(1);
	for ( int v = 0; v < v_len; v++ ){
		for ( int u = 0; u < u_len; u++ ){
			int index_array_u_v[] = {u, v}; std::sort(index_array_u_v, index_array_u_v + 2); [[maybe_unused]] const int u_v = ( index_array_u_v[0] + 0 ) / 1 + ( index_array_u_v[1] + 0 ) * ( index_array_u_v[1] + 1 ) / 2;
			double* ScaledEps1Sigma_uv = &ScaledEps1Sigma(0, u, v);
			const double* Eps1Sigma_u_v = &Eps1Sigma(0, u_v);
			#pragma omp simd simdlen(8) aligned(ScaledEps1Sigma_uv, Eps1Sigma_u_v: 64)
			for ( int g = 0; g < g_len; g++ ){
				ScaledEps1Sigma_uv[g] += S(u, v) * Eps1Sigma_u_v[g];
			}
		}
	}
}
