/*
Generated by EigenEinSum

Recommended filename:
W_g...E1Rho_g...RhoGrad_g,t,a---G_t,a.hpp

Einsum expression:
W(g), E1Rho(g), RhoGrad(g, t, a) -> G(t, a)

The einsum expression is decomposed into:
W(g), E1Rho(g) -> WE1Rho(g)
WE1Rho(g), RhoGrad(g, t, a) -> G(t, a)

The index paths are derived to be:
TOP
├── g
└── a
    └── t
        └── g
*/
{
	[[maybe_unused]] const int t_len = RhoGrad.dimension(1);
	assert( t_len == G.dimension(0) );
	[[maybe_unused]] const int a_len = RhoGrad.dimension(2);
	assert( a_len == G.dimension(1) );
	[[maybe_unused]] const int g_len = W.dimension(0);
	assert( g_len == E1Rho.dimension(0) );
	assert( g_len == RhoGrad.dimension(0) );
	EigenTensor<1> WE1Rho(g_len);
	WE1Rho.setZero();
	double* WE1Rho_ = &WE1Rho(0);
	const double* W_ = &W(0);
	const double* E1Rho_ = &E1Rho(0);
	#pragma omp simd simdlen(8) aligned(WE1Rho_, W_, E1Rho_: 64)
	for ( int g = 0; g < g_len; g++ ){
		WE1Rho_[g] += W_[g] * E1Rho_[g];
	}
	for ( int a = 0; a < a_len; a++ ){
		for ( int t = 0; t < t_len; t++ ){
			double Gta = 0;
			const double* WE1Rho_ = &WE1Rho(0);
			const double* RhoGrad_ta = &RhoGrad(0, t, a);
			#pragma omp simd simdlen(8) reduction(+: Gta) aligned(WE1Rho_, RhoGrad_ta: 64)
			for ( int g = 0; g < g_len; g++ ){
				Gta += WE1Rho_[g] * RhoGrad_ta[g];
			}
			G(t, a) += Gta;
		}
	}
}
