/*
Generated by EigenEinSum

Recommended filename:
W_g...ScaledEps1Sigma_g,u,v...SigmaGrad_g,t,a,v+v---E_t,a.hpp

Einsum expression:
W(g), ScaledEps1Sigma(g, u, v), SigmaGrad(g, t, a, v+v) -> E(t, a)

The einsum expression is decomposed into:
W(g), ScaledEps1Sigma(g, u, v) -> WScaledEps1Sigma(g, v)
WScaledEps1Sigma(g, v), SigmaGrad(g, t, a, v+v) -> E(t, a)

The index paths are derived to be:
TOP
└── v
    ├── u
    │   └── g
    └── a
        └── t
            └── g
*/
{
	[[maybe_unused]] const int t_len = SigmaGrad.dimension(1);
	assert( t_len == E.dimension(0) );
	[[maybe_unused]] const int a_len = SigmaGrad.dimension(2);
	assert( a_len == E.dimension(1) );
	[[maybe_unused]] const int g_len = W.dimension(0);
	assert( g_len == ScaledEps1Sigma.dimension(0) );
	assert( g_len == SigmaGrad.dimension(0) );
	[[maybe_unused]] const int u_len = ScaledEps1Sigma.dimension(1);
	[[maybe_unused]] const int v_len = ScaledEps1Sigma.dimension(2);
	[[maybe_unused]] const int v_v_len = SigmaGrad.dimension(3);
	Eigen::Tensor<double, 1> WScaledEps1Sigmav(g_len);
	for ( int v = 0; v < v_len; v++ ){
		int index_array_v_v[] = {v, v}; std::sort(index_array_v_v, index_array_v_v + 2); [[maybe_unused]] const int v_v = ( index_array_v_v[0] + 0 ) / 1 + ( index_array_v_v[1] + 0 ) * ( index_array_v_v[1] + 1 ) / 2;
		WScaledEps1Sigmav.setZero();
		for ( int u = 0; u < u_len; u++ ){
			double* WScaledEps1Sigmav_ = &WScaledEps1Sigmav(0);
			const double* W_ = &W(0);
			const double* ScaledEps1Sigma_uv = &ScaledEps1Sigma(0, u, v);
			#pragma omp simd simdlen(8) aligned(WScaledEps1Sigmav_, W_, ScaledEps1Sigma_uv: 64)
			for ( int g = 0; g < g_len; g++ ){
				WScaledEps1Sigmav_[g] += W_[g] * ScaledEps1Sigma_uv[g];
			}
		}
		for ( int a = 0; a < a_len; a++ ){
			for ( int t = 0; t < t_len; t++ ){
				double _Eta = 0;
				const double* WScaledEps1Sigmav_ = &WScaledEps1Sigmav(0);
				const double* SigmaGrad_tav_v = &SigmaGrad(0, t, a, v_v);
				#pragma omp simd simdlen(8) reduction(+: _Eta) aligned(WScaledEps1Sigmav_, SigmaGrad_tav_v: 64)
				for ( int g = 0; g < g_len; g++ ){
					_Eta += WScaledEps1Sigmav_[g] * SigmaGrad_tav_v[g];
				}
				E(t, a) += _Eta;
			}
		}
	}
}
