/*
Generated by EigenEinSum

Recommended filename:
W_g...Rho_g,w...Eps_g---E_.hpp

Einsum expression:
W(g), Rho(g, w), Eps(g) -> E()

The einsum expression is decomposed into:
W(g), Rho(g, w) -> WRho(g)
WRho(g), Eps(g) -> E()

The index paths are derived to be:
TOP
├── w
│   └── g
└── g
*/
{
	[[maybe_unused]] const int g_len = W.dimension(0);
	assert( g_len == Rho.dimension(0) );
	assert( g_len == Eps.dimension(0) );
	[[maybe_unused]] const int w_len = Rho.dimension(1);
	Eigen::Tensor<double, 1> WRho(g_len);
	WRho.setZero();
	for ( int w = 0; w < w_len; w++ ){
		double* WRho_ = &WRho(0);
		const double* W_ = &W(0);
		const double* Rho_w = &Rho(0, w);
		#pragma omp simd simdlen(8) aligned(WRho_, W_, Rho_w: 64)
		for ( int g = 0; g < g_len; g++ ){
			WRho_[g] += W_[g] * Rho_w[g];
		}
	}
	double _E = 0;
	const double* WRho_ = &WRho(0);
	const double* Eps_ = &Eps(0);
	#pragma omp simd simdlen(8) reduction(+: _E) aligned(WRho_, Eps_: 64)
	for ( int g = 0; g < g_len; g++ ){
		_E += WRho_[g] * Eps_[g];
	}
	E() += _E;
}
