/*
Generated by EigenEinSum

Recommended filename:
W_g...Eps2RhoSigma_g,w,v...RhoGrad_g,t,a,w...SigmaGrad_g,s,b,v---E1_t,a,s,b.hpp

Einsum expression:
W(g), Eps2RhoSigma(g, w, v), RhoGrad(g, t, a, w), SigmaGrad(g, s, b, v) -> E1(t, a, s, b)

The einsum expression is decomposed into:
W(g), Eps2RhoSigma(g, w, v) -> WEps2RhoSigma(g, w, v)
WEps2RhoSigma(g, w, v), RhoGrad(g, t, a, w) -> WEps2RhoSigmaRhoGrad(g, t, a, v)
WEps2RhoSigmaRhoGrad(g, t, a, v), SigmaGrad(g, s, b, v) -> E1(t, a, s, b)

The index paths are derived to be:
TOP
└── v
    ├── w
    │   ├── g
    │   └── a
    │       └── t
    │           └── g
    └── b
        └── s
            └── a
                └── t
                    └── g
*/
{
	[[maybe_unused]] const int t_len = RhoGrad.dimension(1);
	assert( t_len == E1.dimension(0) );
	[[maybe_unused]] const int a_len = RhoGrad.dimension(2);
	assert( a_len == E1.dimension(1) );
	[[maybe_unused]] const int s_len = SigmaGrad.dimension(1);
	assert( s_len == E1.dimension(2) );
	[[maybe_unused]] const int b_len = SigmaGrad.dimension(2);
	assert( b_len == E1.dimension(3) );
	[[maybe_unused]] const int g_len = W.dimension(0);
	assert( g_len == Eps2RhoSigma.dimension(0) );
	assert( g_len == RhoGrad.dimension(0) );
	assert( g_len == SigmaGrad.dimension(0) );
	[[maybe_unused]] const int w_len = Eps2RhoSigma.dimension(1);
	assert( w_len == RhoGrad.dimension(3) );
	[[maybe_unused]] const int v_len = Eps2RhoSigma.dimension(2);
	assert( v_len == SigmaGrad.dimension(3) );
	Eigen::Tensor<double, 3> WEps2RhoSigmaRhoGradv(g_len, t_len, a_len);
	Eigen::Tensor<double, 1> WEps2RhoSigmavw(g_len);
	for ( int v = 0; v < v_len; v++ ){
		WEps2RhoSigmaRhoGradv.setZero();
		for ( int w = 0; w < w_len; w++ ){
			WEps2RhoSigmavw.setZero();
			double* WEps2RhoSigmavw_ = &WEps2RhoSigmavw(0);
			const double* W_ = &W(0);
			const double* Eps2RhoSigma_wv = &Eps2RhoSigma(0, w, v);
			#pragma omp simd simdlen(8) aligned(WEps2RhoSigmavw_, W_, Eps2RhoSigma_wv: 64)
			for ( int g = 0; g < g_len; g++ ){
				WEps2RhoSigmavw_[g] += W_[g] * Eps2RhoSigma_wv[g];
			}
			for ( int a = 0; a < a_len; a++ ){
				for ( int t = 0; t < t_len; t++ ){
					double* WEps2RhoSigmaRhoGradv_ta = &WEps2RhoSigmaRhoGradv(0, t, a);
					const double* WEps2RhoSigmavw_ = &WEps2RhoSigmavw(0);
					const double* RhoGrad_taw = &RhoGrad(0, t, a, w);
					#pragma omp simd simdlen(8) aligned(WEps2RhoSigmaRhoGradv_ta, WEps2RhoSigmavw_, RhoGrad_taw: 64)
					for ( int g = 0; g < g_len; g++ ){
						WEps2RhoSigmaRhoGradv_ta[g] += WEps2RhoSigmavw_[g] * RhoGrad_taw[g];
					}
				}
			}
		}
		for ( int b = 0; b < b_len; b++ ){
			for ( int s = 0; s < s_len; s++ ){
				for ( int a = 0; a < a_len; a++ ){
					for ( int t = 0; t < t_len; t++ ){
						double _E1tasb = 0;
						const double* WEps2RhoSigmaRhoGradv_ta = &WEps2RhoSigmaRhoGradv(0, t, a);
						const double* SigmaGrad_sbv = &SigmaGrad(0, s, b, v);
						#pragma omp simd simdlen(8) reduction(+: _E1tasb) aligned(WEps2RhoSigmaRhoGradv_ta, SigmaGrad_sbv: 64)
						for ( int g = 0; g < g_len; g++ ){
							_E1tasb += WEps2RhoSigmaRhoGradv_ta[g] * SigmaGrad_sbv[g];
						}
						E1(t, a, s, b) += _E1tasb;
					}
				}
			}
		}
	}
}
