/*
Generated by EigenEinSum

Recommended filename:
W_g...Eps2Rho2_g,u,v...RhoGrad_g,t,a,u...RhoGrad_g,s,b,v---E_t,a,s,b.hpp

Einsum expression:
W(g), Eps2Rho2(g, u, v), RhoGrad(g, t, a, u), RhoGrad(g, s, b, v) -> E(t, a, s, b)

The einsum expression is decomposed into:
W(g), Eps2Rho2(g, u, v) -> WEps2Rho2(g, u, v)
WEps2Rho2(g, u, v), RhoGrad(g, t, a, u) -> WEps2Rho2RhoGrad(g, t, a, v)
WEps2Rho2RhoGrad(g, t, a, v), RhoGrad(g, s, b, v) -> E(t, a, s, b)

The index paths are derived to be:
TOP
└── v
    ├── u
    │   ├── g
    │   └── a
    │       └── t
    │           └── g
    └── b
        └── s
            └── a
                └── t
                    └── g
*/
{
	[[maybe_unused]] const int t_len = RhoGrad.dimension(1);
	assert( t_len == E.dimension(0) );
	[[maybe_unused]] const int a_len = RhoGrad.dimension(2);
	assert( a_len == E.dimension(1) );
	[[maybe_unused]] const int s_len = RhoGrad.dimension(1);
	assert( s_len == E.dimension(2) );
	[[maybe_unused]] const int b_len = RhoGrad.dimension(2);
	assert( b_len == E.dimension(3) );
	[[maybe_unused]] const int g_len = W.dimension(0);
	assert( g_len == Eps2Rho2.dimension(0) );
	assert( g_len == RhoGrad.dimension(0) );
	[[maybe_unused]] const int u_len = Eps2Rho2.dimension(1);
	assert( u_len == RhoGrad.dimension(3) );
	[[maybe_unused]] const int v_len = Eps2Rho2.dimension(2);
	assert( v_len == RhoGrad.dimension(3) );
	Eigen::Tensor<double, 3> WEps2Rho2RhoGradv(g_len, t_len, a_len);
	Eigen::Tensor<double, 1> WEps2Rho2vu(g_len);
	for ( int v = 0; v < v_len; v++ ){
		WEps2Rho2RhoGradv.setZero();
		for ( int u = 0; u < u_len; u++ ){
			WEps2Rho2vu.setZero();
			double* WEps2Rho2vu_ = &WEps2Rho2vu(0);
			const double* W_ = &W(0);
			const double* Eps2Rho2_uv = &Eps2Rho2(0, u, v);
			#pragma omp simd simdlen(8) aligned(WEps2Rho2vu_, W_, Eps2Rho2_uv: 64)
			for ( int g = 0; g < g_len; g++ ){
				WEps2Rho2vu_[g] += W_[g] * Eps2Rho2_uv[g];
			}
			for ( int a = 0; a < a_len; a++ ){
				for ( int t = 0; t < t_len; t++ ){
					double* WEps2Rho2RhoGradv_ta = &WEps2Rho2RhoGradv(0, t, a);
					const double* WEps2Rho2vu_ = &WEps2Rho2vu(0);
					const double* RhoGrad_tau = &RhoGrad(0, t, a, u);
					#pragma omp simd simdlen(8) aligned(WEps2Rho2RhoGradv_ta, WEps2Rho2vu_, RhoGrad_tau: 64)
					for ( int g = 0; g < g_len; g++ ){
						WEps2Rho2RhoGradv_ta[g] += WEps2Rho2vu_[g] * RhoGrad_tau[g];
					}
				}
			}
		}
		for ( int b = 0; b < b_len; b++ ){
			for ( int s = 0; s < s_len; s++ ){
				for ( int a = 0; a < a_len; a++ ){
					for ( int t = 0; t < t_len; t++ ){
						double _Etasb = 0;
						const double* WEps2Rho2RhoGradv_ta = &WEps2Rho2RhoGradv(0, t, a);
						const double* RhoGrad_sbv = &RhoGrad(0, s, b, v);
						#pragma omp simd simdlen(8) reduction(+: _Etasb) aligned(WEps2Rho2RhoGradv_ta, RhoGrad_sbv: 64)
						for ( int g = 0; g < g_len; g++ ){
							_Etasb += WEps2Rho2RhoGradv_ta[g] * RhoGrad_sbv[g];
						}
						E(t, a, s, b) += _Etasb;
					}
				}
			}
		}
	}
}
