/*
Generated by EigenEinSum

Recommended filename:
W_g...Rho_g,w...Eps_g,w---E_.hpp

Einsum expression:
W(g), Rho(g, w), Eps(g, w) -> E()

The einsum expression is decomposed into:
W(g), Rho(g, w) -> WRho(g, w)
WRho(g, w), Eps(g, w) -> E()

The index paths are derived to be:
TOP
└── w
    └── g
*/
{
	[[maybe_unused]] const int g_len = W.dimension(0);
	assert( g_len == Rho.dimension(0) );
	assert( g_len == Eps.dimension(0) );
	[[maybe_unused]] const int w_len = Rho.dimension(1);
	assert( w_len == Eps.dimension(1) );
	Eigen::Tensor<double, 2> WRho(g_len, w_len);
	WRho.setZero();
	for ( int w = 0; w < w_len; w++ ){
		double* WRho_w = &WRho(0, w);
		const double* W_ = &W(0);
		const double* Rho_w = &Rho(0, w);
		#pragma omp simd simdlen(8) aligned(WRho_w, W_, Rho_w: 64)
		for ( int g = 0; g < g_len; g++ ){
			WRho_w[g] += W_[g] * Rho_w[g];
		}
		double _E = 0;
		const double* Eps_w = &Eps(0, w);
		#pragma omp simd simdlen(8) reduction(+: _E) aligned(WRho_w, Eps_w: 64)
		for ( int g = 0; g < g_len; g++ ){
			_E += WRho_w[g] * Eps_w[g];
		}
		E() += _E;
	}
}
