/*
Generated by EigenEinSum

Recommended filename:
W_g...E1Rho_g...RhoHess_g,t,a,s,b---H_t,a,s,b.hpp

Einsum expression:
W(g), E1Rho(g), RhoHess(g, t, a, s, b) -> H(t, a, s, b)

The einsum expression is decomposed into:
W(g), E1Rho(g) -> WE1Rho(g)
WE1Rho(g), RhoHess(g, t, a, s, b) -> H(t, a, s, b)

The index paths are derived to be:
TOP
├── g
└── b
    └── s
        └── a
            └── t
                └── g
*/
{
	[[maybe_unused]] const int t_len = RhoHess.dimension(1);
	assert( t_len == H.dimension(0) );
	[[maybe_unused]] const int a_len = RhoHess.dimension(2);
	assert( a_len == H.dimension(1) );
	[[maybe_unused]] const int s_len = RhoHess.dimension(3);
	assert( s_len == H.dimension(2) );
	[[maybe_unused]] const int b_len = RhoHess.dimension(4);
	assert( b_len == H.dimension(3) );
	[[maybe_unused]] const int g_len = W.dimension(0);
	assert( g_len == E1Rho.dimension(0) );
	assert( g_len == RhoHess.dimension(0) );
	EigenTensor<1> WE1Rho(g_len);
	WE1Rho.setZero();
	double* WE1Rho_ = &WE1Rho(0);
	const double* W_ = &W(0);
	const double* E1Rho_ = &E1Rho(0);
	#pragma omp simd simdlen(8) aligned(WE1Rho_, W_, E1Rho_: 64)
	for ( int g = 0; g < g_len; g++ ){
		WE1Rho_[g] += W_[g] * E1Rho_[g];
	}
	for ( int b = 0; b < b_len; b++ ){
		for ( int s = 0; s < s_len; s++ ){
			for ( int a = 0; a < a_len; a++ ){
				for ( int t = 0; t < t_len; t++ ){
					double Htasb = 0;
					const double* WE1Rho_ = &WE1Rho(0);
					const double* RhoHess_tasb = &RhoHess(0, t, a, s, b);
					#pragma omp simd simdlen(8) reduction(+: Htasb) aligned(WE1Rho_, RhoHess_tasb: 64)
					for ( int g = 0; g < g_len; g++ ){
						Htasb += WE1Rho_[g] * RhoHess_tasb[g];
					}
					H(t, a, s, b) += Htasb;
				}
			}
		}
	}
}
