/*
Generated by EigenEinSum

Recommended filename:
W_g...Eps1Rho_g,w...RhoHess_g,t,a,s,b,w---E_t,a,s,b.hpp

Einsum expression:
W(g), Eps1Rho(g, w), RhoHess(g, t, a, s, b, w) -> E(t, a, s, b)

The einsum expression is decomposed into:
W(g), Eps1Rho(g, w) -> WEps1Rho(g, w)
WEps1Rho(g, w), RhoHess(g, t, a, s, b, w) -> E(t, a, s, b)

The index paths are derived to be:
TOP
└── w
    ├── g
    └── b
        └── s
            └── a
                └── t
                    └── g
*/
{
	[[maybe_unused]] const int t_len = RhoHess.dimension(1);
	assert( t_len == E.dimension(0) );
	[[maybe_unused]] const int a_len = RhoHess.dimension(2);
	assert( a_len == E.dimension(1) );
	[[maybe_unused]] const int s_len = RhoHess.dimension(3);
	assert( s_len == E.dimension(2) );
	[[maybe_unused]] const int b_len = RhoHess.dimension(4);
	assert( b_len == E.dimension(3) );
	[[maybe_unused]] const int g_len = W.dimension(0);
	assert( g_len == Eps1Rho.dimension(0) );
	assert( g_len == RhoHess.dimension(0) );
	[[maybe_unused]] const int w_len = Eps1Rho.dimension(1);
	assert( w_len == RhoHess.dimension(5) );
	Eigen::Tensor<double, 1> WEps1Rhow(g_len);
	for ( int w = 0; w < w_len; w++ ){
		WEps1Rhow.setZero();
		double* WEps1Rhow_ = &WEps1Rhow(0);
		const double* W_ = &W(0);
		const double* Eps1Rho_w = &Eps1Rho(0, w);
		#pragma omp simd simdlen(8) aligned(WEps1Rhow_, W_, Eps1Rho_w: 64)
		for ( int g = 0; g < g_len; g++ ){
			WEps1Rhow_[g] += W_[g] * Eps1Rho_w[g];
		}
		for ( int b = 0; b < b_len; b++ ){
			for ( int s = 0; s < s_len; s++ ){
				for ( int a = 0; a < a_len; a++ ){
					for ( int t = 0; t < t_len; t++ ){
						double _Etasb = 0;
						const double* WEps1Rhow_ = &WEps1Rhow(0);
						const double* RhoHess_tasbw = &RhoHess(0, t, a, s, b, w);
						#pragma omp simd simdlen(8) reduction(+: _Etasb) aligned(WEps1Rhow_, RhoHess_tasbw: 64)
						for ( int g = 0; g < g_len; g++ ){
							_Etasb += WEps1Rhow_[g] * RhoHess_tasbw[g];
						}
						E(t, a, s, b) += _Etasb;
					}
				}
			}
		}
	}
}
