/*
Generated by EigenEinSum

Recommended filename:
W_g...Eps1Sigma_g,u...SigmaHess_g,t,a,s,b,u---E_t,a,s,b.hpp

Einsum expression:
W(g), Eps1Sigma(g, u), SigmaHess(g, t, a, s, b, u) -> E(t, a, s, b)

The einsum expression is decomposed into:
W(g), Eps1Sigma(g, u) -> WEps1Sigma(g, u)
WEps1Sigma(g, u), SigmaHess(g, t, a, s, b, u) -> E(t, a, s, b)

The index paths are derived to be:
TOP
└── u
    ├── g
    └── b
        └── s
            └── a
                └── t
                    └── g
*/
{
	[[maybe_unused]] const int t_len = SigmaHess.dimension(1);
	assert( t_len == E.dimension(0) );
	[[maybe_unused]] const int a_len = SigmaHess.dimension(2);
	assert( a_len == E.dimension(1) );
	[[maybe_unused]] const int s_len = SigmaHess.dimension(3);
	assert( s_len == E.dimension(2) );
	[[maybe_unused]] const int b_len = SigmaHess.dimension(4);
	assert( b_len == E.dimension(3) );
	[[maybe_unused]] const int g_len = W.dimension(0);
	assert( g_len == Eps1Sigma.dimension(0) );
	assert( g_len == SigmaHess.dimension(0) );
	[[maybe_unused]] const int u_len = Eps1Sigma.dimension(1);
	assert( u_len == SigmaHess.dimension(5) );
	Eigen::Tensor<double, 1> WEps1Sigmau(g_len);
	for ( int u = 0; u < u_len; u++ ){
		WEps1Sigmau.setZero();
		double* WEps1Sigmau_ = &WEps1Sigmau(0);
		const double* W_ = &W(0);
		const double* Eps1Sigma_u = &Eps1Sigma(0, u);
		#pragma omp simd simdlen(8) aligned(WEps1Sigmau_, W_, Eps1Sigma_u: 64)
		for ( int g = 0; g < g_len; g++ ){
			WEps1Sigmau_[g] += W_[g] * Eps1Sigma_u[g];
		}
		for ( int b = 0; b < b_len; b++ ){
			for ( int s = 0; s < s_len; s++ ){
				for ( int a = 0; a < a_len; a++ ){
					for ( int t = 0; t < t_len; t++ ){
						double _Etasb = 0;
						const double* WEps1Sigmau_ = &WEps1Sigmau(0);
						const double* SigmaHess_tasbu = &SigmaHess(0, t, a, s, b, u);
						#pragma omp simd simdlen(8) reduction(+: _Etasb) aligned(WEps1Sigmau_, SigmaHess_tasbu: 64)
						for ( int g = 0; g < g_len; g++ ){
							_Etasb += WEps1Sigmau_[g] * SigmaHess_tasbu[g];
						}
						E(t, a, s, b) += _Etasb;
					}
				}
			}
		}
	}
}
