/*
Generated by EigenEinSum

Recommended filename:
W_g...E2Rho2_g...RhoGrad_g,t,a...RhoGrad_g,s,b---H_t,a,s,b.hpp

Einsum expression:
W(g), E2Rho2(g), RhoGrad(g, t, a), RhoGrad(g, s, b) -> H(t, a, s, b)

The einsum expression is decomposed into:
W(g), E2Rho2(g) -> WE2Rho2(g)
WE2Rho2(g), RhoGrad(g, t, a) -> WE2Rho2RhoGrad(g, t, a)
WE2Rho2RhoGrad(g, t, a), RhoGrad(g, s, b) -> H(t, a, s, b)

The index paths are derived to be:
TOP
├── g
├── a
│   └── t
│       └── g
└── b
    └── s
        └── a
            └── t
                └── g
*/
{
	[[maybe_unused]] const int t_len = RhoGrad.dimension(1);
	assert( t_len == H.dimension(0) );
	[[maybe_unused]] const int a_len = RhoGrad.dimension(2);
	assert( a_len == H.dimension(1) );
	[[maybe_unused]] const int s_len = RhoGrad.dimension(1);
	assert( s_len == H.dimension(2) );
	[[maybe_unused]] const int b_len = RhoGrad.dimension(2);
	assert( b_len == H.dimension(3) );
	[[maybe_unused]] const int g_len = W.dimension(0);
	assert( g_len == E2Rho2.dimension(0) );
	assert( g_len == RhoGrad.dimension(0) );
	EigenTensor<1> WE2Rho2(g_len);
	EigenTensor<3> WE2Rho2RhoGrad(g_len, t_len, a_len);
	WE2Rho2.setZero();
	WE2Rho2RhoGrad.setZero();
	double* WE2Rho2_ = &WE2Rho2(0);
	const double* W_ = &W(0);
	const double* E2Rho2_ = &E2Rho2(0);
	#pragma omp simd simdlen(8) aligned(WE2Rho2_, W_, E2Rho2_: 64)
	for ( int g = 0; g < g_len; g++ ){
		WE2Rho2_[g] += W_[g] * E2Rho2_[g];
	}
	for ( int a = 0; a < a_len; a++ ){
		for ( int t = 0; t < t_len; t++ ){
			double* WE2Rho2RhoGrad_ta = &WE2Rho2RhoGrad(0, t, a);
			const double* WE2Rho2_ = &WE2Rho2(0);
			const double* RhoGrad_ta = &RhoGrad(0, t, a);
			#pragma omp simd simdlen(8) aligned(WE2Rho2RhoGrad_ta, WE2Rho2_, RhoGrad_ta: 64)
			for ( int g = 0; g < g_len; g++ ){
				WE2Rho2RhoGrad_ta[g] += WE2Rho2_[g] * RhoGrad_ta[g];
			}
		}
	}
	for ( int b = 0; b < b_len; b++ ){
		for ( int s = 0; s < s_len; s++ ){
			for ( int a = 0; a < a_len; a++ ){
				for ( int t = 0; t < t_len; t++ ){
					double Htasb = 0;
					const double* WE2Rho2RhoGrad_ta = &WE2Rho2RhoGrad(0, t, a);
					const double* RhoGrad_sb = &RhoGrad(0, s, b);
					#pragma omp simd simdlen(8) reduction(+: Htasb) aligned(WE2Rho2RhoGrad_ta, RhoGrad_sb: 64)
					for ( int g = 0; g < g_len; g++ ){
						Htasb += WE2Rho2RhoGrad_ta[g] * RhoGrad_sb[g];
					}
					H(t, a, s, b) += Htasb;
				}
			}
		}
	}
}
