/*
Generated by EigenEinSum

Recommended filename:
W_g...Eps1Rho_g,w...RhoGrad_g,t,a,w---E_t,a.hpp

Einsum expression:
W(g), Eps1Rho(g, w), RhoGrad(g, t, a, w) -> E(t, a)

The einsum expression is decomposed into:
W(g), Eps1Rho(g, w) -> WEps1Rho(g, w)
WEps1Rho(g, w), RhoGrad(g, t, a, w) -> E(t, a)

The index paths are derived to be:
TOP
└── w
    ├── g
    └── a
        └── t
            └── g
*/
{
	[[maybe_unused]] const int t_len = RhoGrad.dimension(1);
	assert( t_len == E.dimension(0) );
	[[maybe_unused]] const int a_len = RhoGrad.dimension(2);
	assert( a_len == E.dimension(1) );
	[[maybe_unused]] const int g_len = W.dimension(0);
	assert( g_len == Eps1Rho.dimension(0) );
	assert( g_len == RhoGrad.dimension(0) );
	[[maybe_unused]] const int w_len = Eps1Rho.dimension(1);
	assert( w_len == RhoGrad.dimension(3) );
	Eigen::Tensor<double, 1> WEps1Rhow(g_len);
	for ( int w = 0; w < w_len; w++ ){
		WEps1Rhow.setZero();
		double* WEps1Rhow_ = &WEps1Rhow(0);
		const double* W_ = &W(0);
		const double* Eps1Rho_w = &Eps1Rho(0, w);
		#pragma omp simd simdlen(8) aligned(WEps1Rhow_, W_, Eps1Rho_w: 64)
		for ( int g = 0; g < g_len; g++ ){
			WEps1Rhow_[g] += W_[g] * Eps1Rho_w[g];
		}
		for ( int a = 0; a < a_len; a++ ){
			for ( int t = 0; t < t_len; t++ ){
				double _Eta = 0;
				const double* WEps1Rhow_ = &WEps1Rhow(0);
				const double* RhoGrad_taw = &RhoGrad(0, t, a, w);
				#pragma omp simd simdlen(8) reduction(+: _Eta) aligned(WEps1Rhow_, RhoGrad_taw: 64)
				for ( int g = 0; g < g_len; g++ ){
					_Eta += WEps1Rhow_[g] * RhoGrad_taw[g];
				}
				E(t, a) += _Eta;
			}
		}
	}
}
