/*
Generated by EigenEinSum

Recommended filename:
W_g...E2RhoSigma_g...RhoGrad_g,t,a...SigmaGrad_g,s,b---H1_t,a,s,b.hpp

Einsum expression:
W(g), E2RhoSigma(g), RhoGrad(g, t, a), SigmaGrad(g, s, b) -> H1(t, a, s, b)

The einsum expression is decomposed into:
W(g), E2RhoSigma(g) -> WE2RhoSigma(g)
WE2RhoSigma(g), RhoGrad(g, t, a) -> WE2RhoSigmaRhoGrad(g, t, a)
WE2RhoSigmaRhoGrad(g, t, a), SigmaGrad(g, s, b) -> H1(t, a, s, b)

The index paths are derived to be:
TOP
├── g
├── a
│   └── t
│       └── g
└── b
    └── s
        └── a
            └── t
                └── g
*/
{
	[[maybe_unused]] const int t_len = RhoGrad.dimension(1);
	assert( t_len == H1.dimension(0) );
	[[maybe_unused]] const int a_len = RhoGrad.dimension(2);
	assert( a_len == H1.dimension(1) );
	[[maybe_unused]] const int s_len = SigmaGrad.dimension(1);
	assert( s_len == H1.dimension(2) );
	[[maybe_unused]] const int b_len = SigmaGrad.dimension(2);
	assert( b_len == H1.dimension(3) );
	[[maybe_unused]] const int g_len = W.dimension(0);
	assert( g_len == E2RhoSigma.dimension(0) );
	assert( g_len == RhoGrad.dimension(0) );
	assert( g_len == SigmaGrad.dimension(0) );
	EigenTensor<1> WE2RhoSigma(g_len);
	EigenTensor<3> WE2RhoSigmaRhoGrad(g_len, t_len, a_len);
	WE2RhoSigma.setZero();
	WE2RhoSigmaRhoGrad.setZero();
	double* WE2RhoSigma_ = &WE2RhoSigma(0);
	const double* W_ = &W(0);
	const double* E2RhoSigma_ = &E2RhoSigma(0);
	#pragma omp simd simdlen(8) aligned(WE2RhoSigma_, W_, E2RhoSigma_: 64)
	for ( int g = 0; g < g_len; g++ ){
		WE2RhoSigma_[g] += W_[g] * E2RhoSigma_[g];
	}
	for ( int a = 0; a < a_len; a++ ){
		for ( int t = 0; t < t_len; t++ ){
			double* WE2RhoSigmaRhoGrad_ta = &WE2RhoSigmaRhoGrad(0, t, a);
			const double* WE2RhoSigma_ = &WE2RhoSigma(0);
			const double* RhoGrad_ta = &RhoGrad(0, t, a);
			#pragma omp simd simdlen(8) aligned(WE2RhoSigmaRhoGrad_ta, WE2RhoSigma_, RhoGrad_ta: 64)
			for ( int g = 0; g < g_len; g++ ){
				WE2RhoSigmaRhoGrad_ta[g] += WE2RhoSigma_[g] * RhoGrad_ta[g];
			}
		}
	}
	for ( int b = 0; b < b_len; b++ ){
		for ( int s = 0; s < s_len; s++ ){
			for ( int a = 0; a < a_len; a++ ){
				for ( int t = 0; t < t_len; t++ ){
					double H1tasb = 0;
					const double* WE2RhoSigmaRhoGrad_ta = &WE2RhoSigmaRhoGrad(0, t, a);
					const double* SigmaGrad_sb = &SigmaGrad(0, s, b);
					#pragma omp simd simdlen(8) reduction(+: H1tasb) aligned(WE2RhoSigmaRhoGrad_ta, SigmaGrad_sb: 64)
					for ( int g = 0; g < g_len; g++ ){
						H1tasb += WE2RhoSigmaRhoGrad_ta[g] * SigmaGrad_sb[g];
					}
					H1(t, a, s, b) += H1tasb;
				}
			}
		}
	}
}
