/*
Generated by EigenEinSum

Recommended filename:
W_g...E2Sigma2_g...SigmaGrad_g,t,a...SigmaGrad_g,s,b---H_t,a,s,b.hpp

Einsum expression:
W(g), E2Sigma2(g), SigmaGrad(g, t, a), SigmaGrad(g, s, b) -> H(t, a, s, b)

The einsum expression is decomposed into:
W(g), E2Sigma2(g) -> WE2Sigma2(g)
WE2Sigma2(g), SigmaGrad(g, t, a) -> WE2Sigma2SigmaGrad(g, t, a)
WE2Sigma2SigmaGrad(g, t, a), SigmaGrad(g, s, b) -> H(t, a, s, b)

The index paths are derived to be:
TOP
├── g
├── a
│   └── t
│       └── g
└── b
    └── s
        └── a
            └── t
                └── g
*/
{
	[[maybe_unused]] const int t_len = SigmaGrad.dimension(1);
	assert( t_len == H.dimension(0) );
	[[maybe_unused]] const int a_len = SigmaGrad.dimension(2);
	assert( a_len == H.dimension(1) );
	[[maybe_unused]] const int s_len = SigmaGrad.dimension(1);
	assert( s_len == H.dimension(2) );
	[[maybe_unused]] const int b_len = SigmaGrad.dimension(2);
	assert( b_len == H.dimension(3) );
	[[maybe_unused]] const int g_len = W.dimension(0);
	assert( g_len == E2Sigma2.dimension(0) );
	assert( g_len == SigmaGrad.dimension(0) );
	EigenTensor<1> WE2Sigma2(g_len);
	EigenTensor<3> WE2Sigma2SigmaGrad(g_len, t_len, a_len);
	WE2Sigma2.setZero();
	WE2Sigma2SigmaGrad.setZero();
	double* WE2Sigma2_ = &WE2Sigma2(0);
	const double* W_ = &W(0);
	const double* E2Sigma2_ = &E2Sigma2(0);
	#pragma omp simd simdlen(8) aligned(WE2Sigma2_, W_, E2Sigma2_: 64)
	for ( int g = 0; g < g_len; g++ ){
		WE2Sigma2_[g] += W_[g] * E2Sigma2_[g];
	}
	for ( int a = 0; a < a_len; a++ ){
		for ( int t = 0; t < t_len; t++ ){
			double* WE2Sigma2SigmaGrad_ta = &WE2Sigma2SigmaGrad(0, t, a);
			const double* WE2Sigma2_ = &WE2Sigma2(0);
			const double* SigmaGrad_ta = &SigmaGrad(0, t, a);
			#pragma omp simd simdlen(8) aligned(WE2Sigma2SigmaGrad_ta, WE2Sigma2_, SigmaGrad_ta: 64)
			for ( int g = 0; g < g_len; g++ ){
				WE2Sigma2SigmaGrad_ta[g] += WE2Sigma2_[g] * SigmaGrad_ta[g];
			}
		}
	}
	for ( int b = 0; b < b_len; b++ ){
		for ( int s = 0; s < s_len; s++ ){
			for ( int a = 0; a < a_len; a++ ){
				for ( int t = 0; t < t_len; t++ ){
					double Htasb = 0;
					const double* WE2Sigma2SigmaGrad_ta = &WE2Sigma2SigmaGrad(0, t, a);
					const double* SigmaGrad_sb = &SigmaGrad(0, s, b);
					#pragma omp simd simdlen(8) reduction(+: Htasb) aligned(WE2Sigma2SigmaGrad_ta, SigmaGrad_sb: 64)
					for ( int g = 0; g < g_len; g++ ){
						Htasb += WE2Sigma2SigmaGrad_ta[g] * SigmaGrad_sb[g];
					}
					H(t, a, s, b) += Htasb;
				}
			}
		}
	}
}
