/*
Generated by EigenEinSum

Recommended filename:
W_g...E1Sigma_g...SigmaGrad_g,t,a---G_t,a.hpp

Einsum expression:
W(g), E1Sigma(g), SigmaGrad(g, t, a) -> G(t, a)

The einsum expression is decomposed into:
W(g), E1Sigma(g) -> WE1Sigma(g)
WE1Sigma(g), SigmaGrad(g, t, a) -> G(t, a)

The index paths are derived to be:
TOP
├── g
└── a
    └── t
        └── g
*/
{
	[[maybe_unused]] const int t_len = SigmaGrad.dimension(1);
	assert( t_len == G.dimension(0) );
	[[maybe_unused]] const int a_len = SigmaGrad.dimension(2);
	assert( a_len == G.dimension(1) );
	[[maybe_unused]] const int g_len = W.dimension(0);
	assert( g_len == E1Sigma.dimension(0) );
	assert( g_len == SigmaGrad.dimension(0) );
	EigenTensor<1> WE1Sigma(g_len);
	WE1Sigma.setZero();
	double* WE1Sigma_ = &WE1Sigma(0);
	const double* W_ = &W(0);
	const double* E1Sigma_ = &E1Sigma(0);
	#pragma omp simd simdlen(8) aligned(WE1Sigma_, W_, E1Sigma_: 64)
	for ( int g = 0; g < g_len; g++ ){
		WE1Sigma_[g] += W_[g] * E1Sigma_[g];
	}
	for ( int a = 0; a < a_len; a++ ){
		for ( int t = 0; t < t_len; t++ ){
			double Gta = 0;
			const double* WE1Sigma_ = &WE1Sigma(0);
			const double* SigmaGrad_ta = &SigmaGrad(0, t, a);
			#pragma omp simd simdlen(8) reduction(+: Gta) aligned(WE1Sigma_, SigmaGrad_ta: 64)
			for ( int g = 0; g < g_len; g++ ){
				Gta += WE1Sigma_[g] * SigmaGrad_ta[g];
			}
			G(t, a) += Gta;
		}
	}
}
