/*
Generated by EigenEinSum

Recommended filename:
Ws_g...E1Sigmas_g...SigmaHesss_g,t,a,s,b---H_t,a,s,b.hpp

Einsum expression:
Ws(g), E1Sigmas(g), SigmaHesss(g, t, a, s, b) -> H(t, a, s, b)

The einsum expression is decomposed into:
Ws(g), E1Sigmas(g) -> WsE1Sigmas(g)
WsE1Sigmas(g), SigmaHesss(g, t, a, s, b) -> H(t, a, s, b)

The index paths are derived to be:
TOP
├── g
└── a
    └── t
        └── b
            └── s
                └── g
*/
{
	const int t_len = SigmaHesss.dimensions()[1];
	assert( t_len == H.dimensions()[0] );
	const int a_len = SigmaHesss.dimensions()[2];
	assert( a_len == H.dimensions()[1] );
	const int s_len = SigmaHesss.dimensions()[3];
	assert( s_len == H.dimensions()[2] );
	const int b_len = SigmaHesss.dimensions()[4];
	assert( b_len == H.dimensions()[3] );
	const int g_len = Ws.dimensions()[0];
	assert( g_len == E1Sigmas.dimensions()[0] );
	assert( g_len == SigmaHesss.dimensions()[0] );
	Eigen::Tensor<double, 1> WsE1Sigmas(g_len);
	WsE1Sigmas.setZero();
	for ( int g = 0; g < g_len; g++ ){
		WsE1Sigmas(g) += Ws(g) * E1Sigmas(g);
	}
	for ( int a = 0; a < a_len; a++ ){
		for ( int t = 0; t < t_len; t++ ){
			for ( int b = 0; b < b_len; b++ ){
				for ( int s = 0; s < s_len; s++ ){
					for ( int g = 0; g < g_len; g++ ){
						H(t, a, s, b) += WsE1Sigmas(g) * SigmaHesss(g, t, a, s, b);
					}
				}
			}
		}
	}
}
