/*
Generated by EigenEinSum

Recommended filename:
Ws_g...E2Rho2s_g...RhoGrads_g,t,a...RhoGrads_g,s,b---H_t,a,s,b.hpp

Einsum expression:
Ws(g), E2Rho2s(g), RhoGrads(g, t, a), RhoGrads(g, s, b) -> H(t, a, s, b)

The einsum expression is decomposed into:
Ws(g), E2Rho2s(g) -> WsE2Rho2s(g)
WsE2Rho2s(g), RhoGrads(g, t, a) -> WsE2Rho2sRhoGrads(g, t, a)
WsE2Rho2sRhoGrads(g, t, a), RhoGrads(g, s, b) -> H(t, a, s, b)

The index paths are derived to be:
TOP
├── g
└── a
    └── t
        ├── g
        └── b
            └── s
                └── g
*/
{
	const int t_len = RhoGrads.dimensions()[1];
	assert( t_len == H.dimensions()[0] );
	const int a_len = RhoGrads.dimensions()[2];
	assert( a_len == H.dimensions()[1] );
	const int s_len = RhoGrads.dimensions()[1];
	assert( s_len == H.dimensions()[2] );
	const int b_len = RhoGrads.dimensions()[2];
	assert( b_len == H.dimensions()[3] );
	const int g_len = Ws.dimensions()[0];
	assert( g_len == E2Rho2s.dimensions()[0] );
	assert( g_len == RhoGrads.dimensions()[0] );
	assert( g_len == RhoGrads.dimensions()[0] );
	Eigen::Tensor<double, 1> WsE2Rho2s(g_len);
	WsE2Rho2s.setZero();
	Eigen::Tensor<double, 1> WsE2Rho2sRhoGradsat(g_len);
	for ( int g = 0; g < g_len; g++ ){
		WsE2Rho2s(g) += Ws(g) * E2Rho2s(g);
	}
	for ( int a = 0; a < a_len; a++ ){
		for ( int t = 0; t < t_len; t++ ){
			WsE2Rho2sRhoGradsat.setZero();
			for ( int g = 0; g < g_len; g++ ){
				WsE2Rho2sRhoGradsat(g) += WsE2Rho2s(g) * RhoGrads(g, t, a);
			}
			for ( int b = 0; b < b_len; b++ ){
				for ( int s = 0; s < s_len; s++ ){
					for ( int g = 0; g < g_len; g++ ){
						H(t, a, s, b) += WsE2Rho2sRhoGradsat(g) * RhoGrads(g, s, b);
					}
				}
			}
		}
	}
}
