/*
Generated by EigenEinSum

Recommended filename:
Ws_g...E1Rhos_g...RhoHesss_g,t,a,s,b---H_t,a,s,b.hpp

Einsum expression:
Ws(g), E1Rhos(g), RhoHesss(g, t, a, s, b) -> H(t, a, s, b)

The einsum expression is decomposed into:
Ws(g), E1Rhos(g) -> WsE1Rhos(g)
WsE1Rhos(g), RhoHesss(g, t, a, s, b) -> H(t, a, s, b)

The index paths are derived to be:
TOP
├── g
└── a
    └── t
        └── b
            └── s
                └── g
*/
{
	const int t_len = RhoHesss.dimensions()[1];
	assert( t_len == H.dimensions()[0] );
	const int a_len = RhoHesss.dimensions()[2];
	assert( a_len == H.dimensions()[1] );
	const int s_len = RhoHesss.dimensions()[3];
	assert( s_len == H.dimensions()[2] );
	const int b_len = RhoHesss.dimensions()[4];
	assert( b_len == H.dimensions()[3] );
	const int g_len = Ws.dimensions()[0];
	assert( g_len == E1Rhos.dimensions()[0] );
	assert( g_len == RhoHesss.dimensions()[0] );
	Eigen::Tensor<double, 1> WsE1Rhos(g_len);
	WsE1Rhos.setZero();
	for ( int g = 0; g < g_len; g++ ){
		WsE1Rhos(g) += Ws(g) * E1Rhos(g);
	}
	for ( int a = 0; a < a_len; a++ ){
		for ( int t = 0; t < t_len; t++ ){
			for ( int b = 0; b < b_len; b++ ){
				for ( int s = 0; s < s_len; s++ ){
					for ( int g = 0; g < g_len; g++ ){
						H(t, a, s, b) += WsE1Rhos(g) * RhoHesss(g, t, a, s, b);
					}
				}
			}
		}
	}
}
